### ISSUE TITLE
Logo request 

### ISSUE THREAD

**Issue by birajkarmakar** [mozilla/OpenDesign#101]
## Goal: 
A new campaign on Firefox Nightly  in India. 

## Info: 
It would be used on swags during the campaign.

## Style Information: 
Very simple logo. It would be round. There would be simple nightly logo, then white round border would be there. On that border "India uses Firefox Nightly" * "https://nightly.mozilla.org" * "#INUsesFxNightly" would be written. 

## Deadline: 
It's kind of urgent! Need it by 5 Apr, 2017

## Tag: 
@parag9d @yofiesetiawan @elioqoshi @Aastha14  @radhika1210

**Comment by birajkarmakar** [comment]
Due to some urgency, I have created the sticker. 
![sticker_sample](https://cloud.githubusercontent.com/assets/1511026/24555904/5b8e4568-1650-11e7-820c-81f8d70102ee.png)

**Comment by pascalchevrel** [comment]
That's fine and as Biraj said, we are short in time 👍

**Comment by quizzycal** [comment]
The sticker looks awesome!! @birajkarmakar

**Comment by elioqoshi** [comment]
@birajkarmakar Thanks for that. Usually requests with that kind of urgency are hard but it seems you did it! Can you please upload the source files to the repo?

**Comment by elioqoshi** [comment]
@birajkarmakar reminder for the source files :)

**Comment by birajkarmakar** [comment]
I tried to upload the psd file which I have. But I can't upload it here.

**Comment by elioqoshi** [comment]
@birajkarmakar push it to the repo/ pull request.

**Comment by barrosgeraldo** [comment]
Hello @birajkarmakar, let me know if you need any help to push and feel free to contact us on the [Telegram group](https://t.me/opendesign).
