### ISSUE TITLE
irc://irc.mozilla.org/#opendesign is empty

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/OpenDesign#102]
https://github.com/mozilla/OpenDesign directs readers: 

>  IRC: #opendesign on irc.mozilla.org

I'm the only person there.

**Comment by elioqoshi** [comment]
Thanks @grahamperrin, that's one of the things we want to address this month. I'm thinking to add a Telegram Bridge to IRC since there are 140 members on Telegram.

**Comment by grahamperrin** [comment]
Was irc://irc.mozilla.org/#opendesign intended to be specific to the Mozilla community? 

Or a broader open design community that just happened to be hosted in the mozilla.org domain? 

irc://irc.mozilla.org/#opennews exists with reference to https://opennews.org/ and https://opennews.org/who/ explains: 

> … Incubated at Mozilla from 2011-2016, OpenNews is now a project of Community Partners. 

– so I assumed that #opennews was born from the incubation of #opendesign 

Without me using Telegram, what can you tell us about the group of 140? 

## Open design; open source design

I read this issue `#102` alongside: 

- https://github.com/opensourcedesign/organization/issues/15 (Chat Room Requirements)
- https://github.com/opensourcedesign/organization/issues/70 for one of the web interfaces to ircs://chat.freenode.net/#opensourcedesign
- https://github.com/opensourcedesign/organization/issues/73 (Strategy for OSD's goals, user base, platform and growth)

**Comment by grahamperrin** [comment]
[Launching an Independent OpenNews Program - The Mozilla Blog](https://blog.mozilla.org/blog/2017/02/09/launching-an-independent-opennews-program/) (2017-02-09) puts OpenNews in context. 

My guess about the death (emptiness) of irc://irc.mozilla.org/#opendesign in relation to the birth of irc://irc.mozilla.org/#opennews was probably wrong, sorry; it was a wild guess based on the few rooms at irc.mozilla.org that have _open_ in their names.

**Comment by elioqoshi** [comment]
Yeah, we never really used the channel at the first place, hence. But for openness reasons, we want to create an IRC <> Telegram bridge at least. Yep, it's Mozilla specific, otherwise we would use the #opensourcedesign room :)

**Comment by grahamperrin** [comment]
Spun off from private chat in Telegram

The introduction at https://telegram.me/opendesign is not suitably open, there's a requirement for protocol-specific clients (no web interface): 

![telegram contact opendesign](https://cloud.githubusercontent.com/assets/192271/24589763/f53e3f14-17d7-11e7-9daf-faab4bf7d1d7.png)

Only **after** finding a way to https://web.telegram.org/#/im?p=@opendesign does https://telegram.me/opendesign improve itself to offer the web interface. 

I'll change the topic in IRC to show https://web.telegram.org/#/im?p=@opendesign in lieu of tg://resolve?domain=opendesign

**Comment by Ryuno-Ki** [comment]
See https://github.com/zhukov/webogram/issues/594 for technical background on Telegram Web.

**Comment by elioqoshi** [comment]
discussed with @hmitsch to set up a Telegram Bridge

**Comment by grahamperrin** [comment]
A point of reference, for discussion in the Telegram interface to `#opendesign`:

- Mozilla has 134 people across _open-leadership-training_ and six other rooms at https://gitter.im/mozilla

**Comment by grahamperrin** [comment]
## Suggested change of topic for the room

`bridged with https://web.telegram.org/#/im?p=@opendesign for Mozilla OpenDesign – https://blog.mozilla.org/OpenDesign`

**Comment by bunnybooboo** [comment]
IRC Bridge now fully implemented as reflected on https://github.com/mozilla/OpenDesign , living/breathing channel in IRC, and fully functioning telegram_bot. To be marked closed?

**Comment by grahamperrin** [comment]
Thanks, at a glance (with Matrix) it looks OK with the exception of the outdated topic: 

![a matrix view of the room](https://cloud.githubusercontent.com/assets/192271/25558099/906e6ee2-2d17-11e7-9f46-574871e1b2c7.png)

**Comment by grahamperrin** [comment]
> … fully functioning telegram_bot …

A notification that I received from Telegram was empty –

![notification from telegram](https://cloud.githubusercontent.com/assets/192271/25558148/4d60b708-2d18-11e7-8330-9a62adb77e2b.png)

 – the subsequent browser view of Telegram was OK. I assume that this bug involves Telegram more than the bridge, I'm happy to treat it as negligible. 

(I used Telegram for nothing other than Mozilla Open Design. As there's now the bridge with IRC I'll prefer to be present via Matrix.)

**Comment by bunnybooboo** [comment]
This is perhaps due to the bridge in Matrix? Some are very specific for each service. I have tested Riot myself https://github.com/decentech/tutorials/blob/master/riot.im-beta-setup.md and found my reserved username a bit of an issue. Really freaking awesome platform though, I agree.

Your issue therefore seems to be growing in its scope. The Topic can be arbitrarily changed by an op/mod in IRC. The Matrix bridge might be down to the fact the bridge in Mozilla use right now does not include Telegram. Spotted one here which also adds Mattermost (currently in use by MoFo), and Slack, etc. https://github.com/42wim/matterbridge Not a bug, perhaps a feature request?

**Comment by grahamperrin** [comment]
Thanks, 

> … Your issue therefore seems to be growing in its scope. …

I've been using IRC for decades but to be honest, I know next to nothing about the bridging technologies :-) I just wanted to flag those two things (in the two screenshots) in case either one prompted someone who _does_ have the knowledge to perform any additional checks. 

Closing now, thanks; I don't foresee a need to reopen (the room is pleasantly populated).

**Comment by bunnybooboo** [comment]
I know you haven't asked, but I took the opportunity to investigate this myself, as I've seen a lot of attention at Mozilla regarding communication channels. And I ultimately didn't fully understand what a bridge was either.. so here goes:

From my understanding any 'bridge' is simply an integration of APIs. Early adoption can mean some are run a very specific task (like Matrix IRC bridge), with later ones often collecting these specific tasks into one fully integrated solution (like MatterBridge).

For example, If you look at the [Matrix IRC Bridge](https://github.com/matrix-org/matrix-appservice-irc), you'll see the code is written in Node.js; the core code found in app.js (50 lines of code), /bin/main.js (173 lines), and /lib/bridge/IrcBridge.js (899 lines of hard grunt). 

To implement such code requires server access. A bridge could be considered a layer. For example, the bridging of IRC to Matrix only shows pure IRC, without the additional bridged API layer/s. Each service's API would need a separate bridge to get/push to each connected service: 
```
Telegram   + additional API layers: {irc bridge}{matrix bridge}
IRC        + additional API layers: {telegram bridge}{matrix bridge}
Matrix     + additional API layers: {telegram bridge}{irc bridge}
```
Additional service needs like identity management (mod status, account editing, banning, etc) look to be found in /scripts (at least in the IRC bridge example). 

I wholeheartedly share with your excitement of Matrix, reflected in your desire to integrate another service. There is recognised focus seen within Mozilla to unify the silos of its community's messaging tools (Slack, email, IRC, Mattermost, Telegram, Discourse, Gitter, and I'm sure I've missed some). Whilst Matrix does indeed seem a great solution, and there are inroads through at least testing this, its setup is still a little clunky for the average user during the beta phase. Not to mention the initiative, and resources, needed by each core team to implement the public testing of a beta solution.

Ultimately it's great to get excited by Open Source solutions which, seemingly, provide ease to our day to day pains. The possibilities never cease to be inspiring!
