### ISSUE TITLE
A-Frame Stickers

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#103]
Added the A-Frame sticker designs here:
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/A-Frame%20Icon%20Stickers

I recreated the vector icon as it wasn't available (or even rendered in 3D).}

![sticker preview](https://cloud.githubusercontent.com/assets/5436686/24610695/e274f5a0-187f-11e7-95b1-267b9a1b43ad.jpg)

**Comment by barrosgeraldo** [comment]
Great, I used this to print my buttons for workshops at Brazil, thank you.
