### ISSUE TITLE
Phonebook Icon/Branding

### ISSUE THREAD

**Issue by m-branson** [mozilla/OpenDesign#106]
## Goal: 
An icon/new branding for [Phonebook](https://phonebook.mozilla.org/)

## Info: 
This request has come out of the current (work in progress) redesign of the SSO (Okta) Dashboard. See below. Currently all Mozilla sites are represented by the black highlight Zilla treatment. This is a placeholder until icons are available.

Yulia (Brand) is the originator of this request and should be kept apprised of progress/requests for feedback and direction.

![landing](https://cloud.githubusercontent.com/assets/18686986/24779166/6aadde9a-1ae3-11e7-9396-e1891293ac83.png)

## Style Information: 
Under the new brand the Dino will be used as the icon for MDN only. A new, single color icon that can be used with or without a wordmark is preferable. Please default to Yulia for further direction. Also, the site owner/team should be consulted for conceptual direction.

## Deadline: 
Initial Beta release for the SSO (Auth0) Dashboard is slated for April 21st 2017. If this can be ready by then for initial release implementation, fantastic! Though understandable if that timeline is too aggressive and can not be met. We will have regular releases/feature enhancements and can integrate icon(s) updates as they are available.

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
Thanks @m-branson!

Gave this a go based on the latest direction we had. Might be worth giving it some thought next week with the others :)

![phonebook](https://cloud.githubusercontent.com/assets/5436686/24823320/6cec6454-1bfd-11e7-9cef-63b6c3d4148a.jpg)

**Comment by m-branson** [comment]
Thanks Elio, I think this icon option is strong. Would it be possible to see explorations of the icons without their wordmark(s) too? We will want to use them separately for internal entities like the SSO dashboard, though on the actual sites a lockup most likely be needed.

Similar feedback here re: the text highlight as black rather than in color(s). The icon in yellow with wordmark highlights that are black would be a good next iteration. Nice work!

**Comment by comzeradd** [comment]
I like it :) One minor comment/suggestion: We could probably skip the mozilla wordmark here. The intended audience of that logo is exclusively paid staff. So it should be clear that the phonebook refers to Mozilla's internal phonebook.

**Comment by elioqoshi** [comment]
![1](https://cloud.githubusercontent.com/assets/5436686/25312023/7b4bf1a0-280e-11e7-8fd6-323f2f8e9f5b.jpg)

Thanks! I updated this with the updated direction we are taking. One of the more vertical versions should fit here. @m-branson ?

**Comment by m-branson** [comment]
Thanks @elioqoshi these are looking great. 😄  We've been talking via slack so I think you'll know already a bit what I will say here...

- icon > phonebook (all on one line).
- a darker yellow so that the icon and phonebook can be transparent (cut out) and allow whatever background color there is to come through.
- whether or not we use the mozilla logo beneath phonebook is honestly up to the brand team. If we do, it would be smaller and in black as a supplement to the lock up. Let's check in with Yulia about that?

Thanks for doing such great work on these!
