### ISSUE TITLE
The Hub Icon/Branding

### ISSUE THREAD

**Issue by m-branson** [mozilla/OpenDesign#107]
## Goal: 
An icon/new branding for [The Hub](https://mozilla.service-now.com/)

## Info: 
This request has come out of the current (work in progress) redesign of the SSO (Okta) Dashboard. See below. Currently all Mozilla sites are represented by the black highlight Zilla treatment. This is a placeholder until icons are available.

Yulia (Brand) is the originator of this request and should be kept apprised of progress/requests for feedback and direction.

![landing](https://cloud.githubusercontent.com/assets/18686986/24779166/6aadde9a-1ae3-11e7-9396-e1891293ac83.png)

## Style Information: 
A single color icon that can be used with or without a wordmark is preferable. Please default to Yulia for further direction. Also, the site owner/team should be consulted for conceptual direction.

## Deadline: 
Initial Beta release for the SSO (Auth0) Dashboard is slated for April 21st 2017. If this can be ready by then for initial release implementation, fantastic! Though understandable if that timeline is too aggressive and can not be met. We will have regular releases/feature enhancements and can integrate icon(s) updates as they are available.

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
Gave this a go with an icon to spark off the conversation

![screenshot from 2017-04-08 23-04-37](https://cloud.githubusercontent.com/assets/5436686/24832406/ca80675c-1caf-11e7-9745-c4c9c4859581.png)

**Comment by m-branson** [comment]
Nice Elio, I think the icon is headed in the right direction. What if the coloring for the icon was a darker shade of red? Thinking that if the icon was used on its own, it would still be readily associated with The Hub if the coloring match a bit more.

Also, same note here re: posting this in Slack for wider brand team review. I believe we won't be using the text highlight in a color other than black.

**Comment by elioqoshi** [comment]
@m-branson, yeah we can try that. I just thought we should use the defined color swatches but that would make sense

**Comment by m-branson** [comment]
@elioqoshi I thought we had a darker, secondary shade of the coral/pink color that could be utilized? Not recommending that we go outside of the color palette.
