### ISSUE TITLE
T Shirt Design + Logo for Mozilla QA Bangladesh Community Meetup

### ISSUE THREAD

**Issue by hossainalikram** [mozilla/OpenDesign#110]
## Goal: 
A T Shirt Design and a logo that can be used as stickers for Firefox Team's Upcoming QA Training Workshop "Mozilla QA Bangladesh Community Meetup"

## Info: 
This will be used for creating  T Shirt for Meetup attendees and Logo will be used for creating Stickers or used anywhere digitally ( example https://github.com/mozilla/OpenDesign/issues/80#issuecomment-236361659 ).

## Style Information: 
The Text would be "Mozilla Bangladesh QA Community Meetup, 17" and for stickers, we would like to feature "Shaheed Minar, Dhaka - https://en.wikipedia.org/wiki/Shaheed_Minar,_Dhaka "

## Deadline: 
April 25, 2017

## Tag: 
[Design Needed]

**Comment by elioqoshi** [comment]
@hossainalikram Sorry, but we will be unable to create the logo as we don't have the community styleguides yet, which will be created in the coming months. Do you have the event set up yet?

We might be able to do a sticker though.

**Comment by elioqoshi** [comment]
That would be the text illustration. What do you think?

![screenshot from 2017-04-08 22-25-15](https://cloud.githubusercontent.com/assets/5436686/24832187/51513b18-1caa-11e7-853b-5ec322f0b54c.png)

**Comment by hossainalikram** [comment]
This looks good to me. Yes, The event is set at 11-14 May.

We currently need the Sticker and design for T Shirt, and would be helpful for this two.

The Text Looks good to me :D

**Comment by elioqoshi** [comment]
Okay, we might be able to do something.

@parag9d can you do an illustration?

**Comment by hossainalikram** [comment]
A gentle reminder on this, We are quite short in time. Any updates?

**Comment by elioqoshi** [comment]
Hmm I can't help with more than branding here. If anyone else can help with design we can move this forward

**Comment by yofiesetiawan** [comment]
![laptop](https://cloud.githubusercontent.com/assets/2810823/25538142/a87a2ea6-2c6b-11e7-8be7-9d48859f3f5d.jpg)
![tshirt](https://cloud.githubusercontent.com/assets/2810823/25538141/a87657b8-2c6b-11e7-945b-93d6ba78a952.jpg)

**Comment by hossainalikram** [comment]
@elioqoshi , Can you help me to have the text this way

**Comment by hossainalikram** [comment]
@elioqoshi , Can you help me to look the text this way 
mozilla
bangladesh
qa community
meetup, 17

**Comment by elioqoshi** [comment]
@yofiesetiawan looks great, thanks!

@hossainalikram will do that as I said :)

**Comment by elioqoshi** [comment]
@hossainalikram here we go:
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/QA_Bangladesh_2017_Meetup

**Comment by SufiAhmedHamim** [comment]
**Mozilla bangladesh qa community meetup, 17- Batch Design:**

![lalbag fort 3](https://cloud.githubusercontent.com/assets/19908532/25676831/5cfbc9be-3065-11e7-8cb8-7cf85db712f5.png)

![shahid minar](https://cloud.githubusercontent.com/assets/19908532/25676836/6725460e-3065-11e7-9ec6-416a17cdadc7.png)

**Main flie link:**[https://drive.google.com/open?id=0BzaFlqta9aHebnRnYkVqblhXWUk](url)

**Comment by elioqoshi** [comment]
@hossainalikram source files are here:
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/QA_Bangladesh_2017_Meetup
