### ISSUE TITLE
#RainOfRUST Campaign

### ISSUE THREAD

**Issue by prathameshchavan** [mozilla/OpenDesign#111]
## Goal: 
A campaign logo which would be used in all the social media posts and other areas. 

## Info: 
#RainOfRUST would be a campaign in India (primarily) (could be global if possible) in the month of June 2017 whose primary objective is to increase the RUST awareness, form local/regional RUST communities and increase RUST users.

## Style Information: 
Design should include the RUST logo and if possible, something that would relate to India.

## Deadline: 
30th April 2017

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
![rainofrust_color](https://cloud.githubusercontent.com/assets/5436686/25566712/37310042-2ddf-11e7-8a04-f565fadac30a.png)

There we go:
https://github.com/mozilla/OpenDesign/tree/master/2017/Logos%26Branding/RainOfRust

I think it would be best to not keep this India exclusive so it can be reused :)

Good luck!
