### ISSUE TITLE
3x3 inch WebVR logo design

### ISSUE THREAD

**Issue by umeshagarwal** [mozilla/OpenDesign#114]
## Goal: 
3x3 inch WebVR logo design

## Info: 
I already have a logo but it does not have a border which makes it look weird. So need just the border added to the logo.

## Style Information: 
Same as Mozilla Style guide
## Deadline: 

[When would you like this done by]
In next two weeks
![mozvr](https://cloud.githubusercontent.com/assets/3319062/25553227/81d393cc-2ccb-11e7-97cb-e1c97ebf95a2.png)

## Tag: @elioqoshi @kelimuttu @couci 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by elioqoshi** [comment]
@umeshagarwal is this what you are looking for?
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/A-Frame%20Icon%20Stickers

Also, I don't understand what you are asking here. Is it a sticker or a logo? Please provide details on usage and more info. You mention WebVR but attached is a design from A-Frame

**Comment by umeshagarwal** [comment]
It's a sticker. I will make 3x3 round stickers. Yes its A Frame and we need that. It doesn't have a border so doesn't look good as a sticker.

**Comment by elioqoshi** [comment]
Have you seen the link I shared? ^

**Comment by elioqoshi** [comment]
Okay, seems these design work for this purpose. Closing this :)
