### ISSUE TITLE
One In A Mozillian T-Shirt Design

### ISSUE THREAD

**Issue by umeshagarwal** [mozilla/OpenDesign#115]
## Goal: 
Need to recreate A4 design to print on black T-Shirt

## Info: 
I have the design ready but it have gradient/graphics which cannot be printed by screen printing. So need only solid colours. 

## Style Information: 
https://mozilla.ninja/gallery/
"One in a Mozillian"

## Deadline: 
By next 2 weeks

## Tag: @elioqoshi @couci @kelimuttu 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by umeshagarwal** [comment]
![mozillian-01](https://cloud.githubusercontent.com/assets/3319062/25553260/45b7f1de-2ccc-11e7-9ace-50a1c93f9351.png)

**Comment by elioqoshi** [comment]
@umeshagarwal here we go:
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/One_In_A_Mozillian

Preview:
![preview](https://cloud.githubusercontent.com/assets/5436686/25566417/7cdf3980-2dd8-11e7-903f-3a49b87c548e.jpg)

**Comment by kelimuttu** [comment]
I love this one. The background color is simpler so it's easier to read the sentence. Thanks for opening the issue @umeshagarwal and @elioqoshi thanks as well for the design.
