### ISSUE TITLE
Hacksheet for Firefox add-ons

### ISSUE THREAD

**Issue by viswanathamsantosh** [mozilla/OpenDesign#116]
## Goal: 
A hacksheet for Mozilla add-ons which could be used for events and conferences.

## Info: 
It will be used/distributed at events, technology conferences, workshops with all the required information on it .

## Style Information: 
I think you know this better than me. ;-) But use a web-extension logo atleast once.

## Deadline: 
May 5th. However it is completely fine if we miss the deadline.

## Tag: 
Design needed

**Comment by viswanathamsantosh** [comment]
[addons.pdf](https://github.com/mozilla/OpenDesign/files/966128/addons.pdf)
Here goes the content cum sample that is required for the Hacksheet.

**Comment by elioqoshi** [comment]
@viswanathamsantosh I will do this next week as some other issues have priority. Thanks for the patience :)

**Comment by caitmuenster** [comment]
👍

@elioqoshi, thank you for helping pick this up next week!  

@viswanathamsantosh, I had a few more thoughts for this (and I apologize for thinking of them so late): 
- on page 1, there should probably be a card title, like "Mozilla Add-ons." 
- on page 1, retitle 'Code' to 'Build Your Own Extension'
- move the Community section to the top of the page and put Social Media beneath it
- Under Social Media, add a line for, "Visit https://wiki.mozilla.org/Add-ons/Contribute for more ways to contribute to the add-ons community." 

Amy and I are going to take a look at the final product to make sure it meets [brand guidelines](https://mozilla.ninja/) and then I think this will be good to go.

**Comment by Srushtika** [comment]
@viswanathamsantosh @elioqoshi 
**This not an actual design**, but I wanted to share the idea of including the required links in a format similar to this. Since all the links are important and they are very long, it would be easier to check these out manually from a printed HackSheet, if broken down in this manner. What do you think?
![screen shot 2017-05-02 at 9 54 02 am](https://cloud.githubusercontent.com/assets/5900152/25603861/5e285fee-2f1d-11e7-9330-a2ad46e2c3f0.png)

**Comment by elioqoshi** [comment]
@caitmuenster Sure! Also no worries, I'm part of the Creative Team and am aware of the Brand Guidelines (at least that much as one can be, we are still experimenting on some directions). The Mozilla.ninja website is not really up to date either, we are working on getting updates done.

P.S: Do you have the AddOn icon in a vector format?

@Srushtika love that direction! Thanks for suggesting it. I will try that.

**Comment by caitmuenster** [comment]
@elioqoshi Awesome! Also, thanks for the heads up about updates being needed for mozilla.ninja. :) I'm still looking for a vector file the icon -- hopefully I'll be able to have more information about it today. 

@Srushtika, I love your idea! It fits with the extension theme perfectly and it is a ton of fun.

**Comment by caitmuenster** [comment]
Sorry, all -- there are another few late updates. :) 

On page 2, the Telegram information should read: 

**Telegram**
Join @addonschat to chat about add-ons 
Join @addons for updates about add-ons

Thank you!

**Comment by caitmuenster** [comment]
Attached is a vector file for the Foxface. 

[addons-foxface.eps.zip](https://github.com/mozilla/OpenDesign/files/977415/addons-foxface.eps.zip)

**Comment by elioqoshi** [comment]
@viswanathamsantosh @caitmuenster Here are the source files :)
https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/WebExtensions_Cheatsheets

**Comment by viswanathamsantosh** [comment]
Right on time! These are beautiful and clear. Thank you so much @elioqoshi :)

**Comment by elioqoshi** [comment]
A6 versions here :)
https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/WebExtensions_Cheatsheets/A6

**Comment by caitmuenster** [comment]
Hey @elioqoshi, this is awesome. I have a dumb question -- what's the best way to submit edits to these files? 

Also, apologies for being late in submitting these changes. @viswanathamsantosh, if you have already printed the current version, that's fine. I just want to get the edits in for the next round. :)

**Comment by viswanathamsantosh** [comment]
We needed A6 for printing which we got a couple of days before. So we haven't printed them yet.  \o/

**Comment by elioqoshi** [comment]
@caitmuenster Pull Requests are fine! Otherwise let me know what changes and I can do them

**Comment by caitmuenster** [comment]
Thanks @elioqoshi! My visual editing skills aren't quite up to the task of submitting a PR. :( This looks like a long list, but I think that we won't have changes for awhile after this. Changes would apply both to the .pdf and to the A6 card. 

**Pages one and two**, top right corner: 
Change "add-ons" to "addons.mozilla.org"

**Page one:** 

All API's should be "APIs"

Capitalize "Your Own" on "Build Your Own WebExtension" 

Capitalize "Publishing your WebExtension" to "Publishing Your Add-on." 

Convert websites into shortened addresses (with apologies to @viswanathamsantosh -- I had reversed this idea during an earlier draft) 
- Tutorial: https://mzl.la/webextensions
-Building Experimental APIs: http://bit.ly/webextensionexperiments
-Publishing Your Add-on: http://bit.ly/publishextension
-APIs: http://bit.ly/jsapis
-Port Chrome  Extensions: http://bit.ly/portextensions

**Page two**
Reorder IRC channels to the following: 
-#extdev
-#addons
-#webextensions

Replace address for mailing list with "http://bit.ly/devaddons" 

Is there room to add the sentence, "To see more ways to contribute to Mozilla's add-ons community, visit http://bit.ly/addonscontribute." If there isn't, no worries -- it can be left off.

**Comment by elioqoshi** [comment]
@caitmuenster Thanks! I will have to have a look next week :)
