### ISSUE TITLE
Illustration for Reps FB Experiment

### ISSUE THREAD

**Issue by Srushtika** [mozilla/OpenDesign#117]
## Goal: 
An illustration/design that captures the idea of the new feedback system that was introduced for the MozActivate activities (mzl.la/howwasit)

## Info: 
This will be posted on the Reps FB page and twitter handle in order to have a greater reach and better spread the news.

## Style Information: 
Anything that does the job but should represent Mozilla Reps.

## Deadline: 
As soon as possible.

## Tag: 
@couci @yofie

**Comment by elioqoshi** [comment]
@Srushtika a bit of more details would be appreciate, as any designer who isn't involved in Reps right now doesn't have any context. As of now, I have no clue either what is requested here.

I can help with this but I'm not sure if I understand what's asked here.

**Comment by Srushtika** [comment]
Hey @elioqoshi !
The design (a poster essentially) I wanted needs to reflect the new feedback system for MozActivate (mzl.la/howwasit). It might be something on the lines of https://thumb7.shutterstock.com/display_pic_with_logo/3295814/371548105/stock-vector-vector-feedback-concept-illustration-can-use-for-web-banner-poster-feedback-or-rating-system-371548105.jpg but this image is only for the concept and not a design idea.

However, it needs to be related to Reps and MozActivate (will help if the logos of these are included). On this design, there'll be text "Did you ever want to measure the IMPACT you created in your event?".

I'm new to specifying design requirements, please ask me if you need any more information.

**Comment by Srushtika** [comment]
![screen shot 2017-04-28 at 9 34 17 am](https://cloud.githubusercontent.com/assets/5900152/25566296/b94cb5bc-2df3-11e7-9f33-cbd5fcea66b1.png)
Or maybe something like this? I know this design is very wrong. But I'm just using it as a way to share the concept and ideation. @elioqoshi

**Comment by elioqoshi** [comment]
@Srushtika That was helpful. Let me mull a bit over it and get back here.
