### ISSUE TITLE
Create Mozilla QA logo with new branding

### ISSUE THREAD

**Issue by hossainalikram** [mozilla/OpenDesign#119]
## Goal: 
Mozilla QA logo

## Info: 
This will be used in different QA specific designs ( in Tshirt/ STickers/ square buttons)
 
## Deadline: 
6 May, 17

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by elioqoshi** [comment]
Thanks for the request. 6 May is impossible. We can aim for the end of the month here.

**Comment by jpswizzle** [comment]
Hi @hossainalikram & @elioqoshi I'm a UX designer and I'm interested in helping out! Would love to chat about this. If interested, please schedule time to talk (30-min video chat preferable): http://calendly.com/jules-monza

**Comment by elioqoshi** [comment]
@jpswizzle Let's chat some time, I am pretty busy in the next days but will get back!

**Comment by jpswizzle** [comment]
Okay, sounds good!

>

**Comment by hossainalikram** [comment]
Pinging as this request is still valid

**Comment by elioqoshi** [comment]
This needs to go through the QA team. Do we have any employee there?

**Comment by barrosgeraldo** [comment]
Hi @elioqoshi, what do you think about an icon using a "check", "double check" or a "check" around a circle?

When we are developing a product, developers coding and make simple tests until the product is good and acceptable (MVP), after the quality team **double-checks in several ways** to ensure that the product is good to start going to the Beta version or release. This is a bit of the context I understand about QA.

**Comment by barrosgeraldo** [comment]
Something like this:
![qa-logo](https://user-images.githubusercontent.com/14970832/29342115-58cf21f6-81ff-11e7-9340-16b754b29f2d.png)

**Comment by barrosgeraldo** [comment]
ping
