### ISSUE TITLE
Logo for Pi Reel due before MozSprint.

### ISSUE THREAD

**Issue by KipOmaha** [mozilla/OpenDesign#121]
## Goal: 
A logo/icon for Pi Reel, an animator made for science and engineering.

## Info: 
It will be used for web pages.

# Style Information: 
A link to the current work is [here](https://pireel.github.io/PiReel-Website/img/pireel.png)  
I would like to change it up a little, because it really doesn't explain itself.

## Deadline: 
MozSprint: June 1, 2017

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
@KipOmaha This is what it would be with Mozilla's branding guidelines :)

![pi reel](https://cloud.githubusercontent.com/assets/5436686/25779583/90aa3728-331c-11e7-92ed-a2173b73962e.jpg)

**Comment by KipOmaha** [comment]
@elioqoshi, thanks for the work. 

I like the symbol for pi you used, would you mind if I used it for other stuff? 
Also I am going to make the background changing.  Except for the Mozilla logo of course. 
I'll send some examples.

**Comment by elioqoshi** [comment]
@KipOmaha sorry what do you mean? Not sure if I understood right.

**Comment by KipOmaha** [comment]
@elioqoshi,
 I meant to ask what font you were using for the pi reel lettering. So I can show you an example.

**Comment by elioqoshi** [comment]
It's Zilla by Mozilla. It's not out yet so we have to wait a bit. If it's a Mozilla project it needs to be in a similar manner like I showed you here, to adhere to guidelines.

**Comment by KipOmaha** [comment]
Thanks, I thought it looked similar to fira
