### ISSUE TITLE
Name badge design for Mozilla Activate events at Sao Paulo/BR

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/OpenDesign#123]
## Goal: 
Name badge design for Mozilla Activate events.

## Info: 
Theses name badge will used in all workshops/events of the campaign (Rust, WebVR, Web Extensions, Web Compatibility, Tech Speakers), they are needed to identify people who are at a Mozilla event , here at Sao Paulo.

We are wanting to produce a large amount and use at all Mozilla community events here in São Paulo, so we want something generic for now that can be used in all community events, especially the Activate campaign.

## Style Information: 
I would love a name badge with the new Mozilla brand, including logo, font and any other relevant drawing/element to illustrate and have a simple and beautiful name badge.

The name badge we want to print has the following characteristics: A6 size, front and back.

Front: Mozilla logo and website, an interesting art/drawing/illustration, free space to add name and twitter handle.
Back: Here it would be interesting to be simple by adding a link to the campaign feedback form (https://mzl.la/howwasit) and a standard email  (saopaulo@mozillabr.org) for participants to reach us later if they need.

Similar l10n badge: https://github.com/mozilla/OpenDesign/blob/master/2016/Swag%26Printouts/l10n-Event-Resources/Name%20Badge-01.jpg

## Deadline: 
1-2 months, when this is ready we will print and use them from the next workshops.

## Tag: 
Design Needed, Staff Support Needed

**Comment by elioqoshi** [comment]
@barrosgeraldo sorry for the delay here, I will try to tackle this next
