### ISSUE TITLE
Mozilla localization digital certificate of participation template

### ISSUE THREAD

**Issue by gueroJeff** [mozilla/OpenDesign#124]
## Goal: 
In some regions of the world, certification of participation in an open source project is valuable to contributors. It is used as a means of validating the fact that the individual participated in the project and can be taken to potential employers as evidence of experience. We need a template certificate of participation for localization that we can give to localizers to acknowledge their involvement and recognize their effort. This initial template doesn't need to include any specific information beyond the ability to insert a name, a project name, a language, and a length of time involved.

## Info: 
It will be sent to individuals who request it (as an attachment in an email) and will live in the shared l10n-drivers Google Drive folder for each l10n-driver to access.

## Style Information: 
I don't really have anything in mind. I'd like it to be uniquely Mozilla, but I'm not sure what that means in this context.

## Deadline: 
End of June?

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by foxt7ot** [comment]
@elioqoshi Can we have your valuable insights on this. Thanks

**Comment by elioqoshi** [comment]
@foxt7ot what insights do you need here?

@gueroJeff  Perfect, thanks Jeff. Should be able to do within the given timeframe. Others are free to take this on though if anyone likes.

**Comment by ranjithrajvasam** [comment]
@gueroJeff Thanks for coming up with this great idea. (Our localization team recently discussed about the same, and I was about to open a issue on this.)

I request the design team to take this as a priority issue as few other l10n teams in India(could be in other countries too) are also looking for this.

**Comment by irvin** [comment]
https://www.dropbox.com/s/ynz5t17haofdht5/Student%20Contributor%20Letter.pdf?dl=0

This is the contribution recognition letter I'd used for many years. 

It came from a really old team (CBT or CDT?) and I'd made it into a PDF form that you can directly filled and signed with your own title. (I singed this for students as rep, for example.)

**Comment by barrosgeraldo** [comment]
Hi @gueroJeff!
I created a draft template here, very basic, I do not know if that was your expectation because I had no recourse on the functional team background/history.

In general the text is just an example, I need you to write the correct text to be added, I created this short text based on your comments, but I am Brazilian and I am not fluent in English, so not sure about the text, hahaha.

The color/logo is the same as [l10n Twitter's design profile](https://twitter.com/mozilla_l10n), but I can add another color palette if you wish, oh and if you have a newer team logo, I can add it as well and any other art you wish. Okay?

The files are here:
 [l10n_certificate_template.pdf](https://github.com/mozilla/OpenDesign/files/1149921/l10n_certificate_template.copiar.pdf)
![l10n_certificate_template](https://user-images.githubusercontent.com/14970832/28235095-e0e04b5a-68dd-11e7-8bd0-3c23a1d767d0.png)

**Comment by barrosgeraldo** [comment]
Per Jeff's recommendations, I'm adding two options with Firefox logo, color and black in the background.
![l10n_certificate_template_firefox_colors](https://user-images.githubusercontent.com/14970832/28235925-4913a1f2-68ef-11e7-8b03-6aa319e5a96f.png)
![l10n_certificate_template_firefox_dark](https://user-images.githubusercontent.com/14970832/28235926-4914c1f4-68ef-11e7-8cc5-cb0213f810ce.png)

**Comment by barrosgeraldo** [comment]
And here, a dark option based on Mozilla's website.
[l10n_certificate_template_dark.pdf](https://github.com/mozilla/OpenDesign/files/1150058/l10n_certificate_template_dark.pdf)
![l10n_certificate_template_dark](https://user-images.githubusercontent.com/14970832/28236266-1a8ba556-68f8-11e7-9ef0-1433348bbc21.png)

**Comment by barrosgeraldo** [comment]
[l10n_certificate_template_dark.pdf](https://github.com/mozilla/OpenDesign/files/1150071/l10n_certificate_template_dark.pdf)
![Uploading l10n_certificate_template_dark.png…]()

**Comment by zilmarr** [comment]
I'd like to add that it would be of great value if we could send a localized certificate also. Many employers or educational institutions doesn't accept or recognize english certificates.

**Comment by petercpg** [comment]
Thanks for the nice design. 

One cent to add: I know it's a bit longer, but would it be informal/jargonized if we use 'L10n' instead of full 'Localization' in the headline?

**Comment by drashti4** [comment]
It would be better if we can add role of contributor in team or some more specific detail regarding performance.

**Comment by bobreyes** [comment]
I agree. People reading the certificate might not understand what "L10n" mean (they may even read is as Lion).

**Comment by barrosgeraldo** [comment]
Hi everyone!
I added the suggestions here:
[l10n_certificate_template_dark.pdf](https://github.com/mozilla/OpenDesign/files/1150463/l10n_certificate_template_dark.pdf)
![l10n_certificate_template_dark](https://user-images.githubusercontent.com/14970832/28240934-8873af24-6960-11e7-976d-da72f18e5160.png)

**Comment by elioqoshi** [comment]
Love this one, very great job @barrosgeraldo! I have nothing to nitpick, it looks very aligned to our guidelines! One thing which I might suggest would be making the name of the receiver in Zilla Highlight and a bit bigger. What do you think?

**Comment by barrosgeraldo** [comment]
It's a great idea because that might highlight the volunteer's name. I'll add now.

Merci,

**Comment by barrosgeraldo** [comment]
The art has been pushed.
