### ISSUE TITLE
Mozilla Indonesia Community Mascot - Vector File

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/OpenDesign#125]
This is Mozilla Indonesia Community Mascot, called Dimo, vector files...

[mozilla-indonesia-mascot.zip](https://github.com/mozilla/OpenDesign/files/1035237/mozilla-indonesia-mascot.zip)

**Comment by barrosgeraldo** [comment]
Hi @yofiesetiawan,
This mascot is awesome! You could push this to the repository?

**Comment by barrosgeraldo** [comment]
ops, I saw on repository.
