### ISSUE TITLE
Add HSL/RGB values next to Hex on https://mozilla.ninja/visualelements/

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/OpenDesign#129]
Since some designers prefer other representations than Hex, it would be handy to have the RGB or HSL values standing on https://mozilla.ninja/visualelements/, too. Otherwise they would need to compute it on their own time and again.

## Tag: 
[Developer Needed, Staff Support Needed]

**Comment by aswinmohanme** [comment]
I would love to take this up, but where it the source of the website ?

**Comment by elioqoshi** [comment]
I don't think the source is on GitHub. We plan to add the values once we update the website.
