### ISSUE TITLE
Add colour contrast on https://mozilla.ninja/visualelements/

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/OpenDesign#130]
For the colour swatches on https://mozilla.ninja/visualelements/ it would be handy to have the contrast ratio listed.

This way, the legibility can be taken into account when deciding on a pair. In some countries there are constraints like reaching at least a AA on contrast (with respect to the formula provided by WCAG). You can use [Lea Verou's contrast ratio tool](https://leaverou.github.io/contrast-ratio/) for computation.
## Tag: 
[Developer Needed, Staff Support Needed]

**Comment by barrosgeraldo** [comment]
Hi @Ryuno-Ki! The guidelines have been updated recently, see the colors here: https://mozilla.ninja/visualelements/.

**Comment by Ryuno-Ki** [comment]
@barrosgeraldo I couldn't find any information concerning concrete contrast ratio there. It only states, that one should ensure, that is high enough …

So I'd like to ask you to re-open this issue.

**Comment by elioqoshi** [comment]
Closing this for now since there is no update
