### ISSUE TITLE
Poster for Mozilla l10n Community Meet-ups

### ISSUE THREAD

**Issue by ranjithrajvasam** [mozilla/OpenDesign#134]
## Goal: 
Common template for Mozilla l10n Community Meet-ups

## Info: 
This will be used by regional l10n communities to adopt the template and localize it to their requirement. [Community meet-ups generally goes with the agenda like preparing roadmap, inviting new contributors, l10n sprints, quality checks etc]

## Style Information: 
Follow the new branding guidelines of Mozilla
Suggested to watch other issues related to 10n in this repo
Mind that text in these templates will be localized into different languages.

## Deadline: 
ASAP

## Tag: 
[Design Needed, svg, branding, graphic design]

**Comment by elioqoshi** [comment]
Sorry, what do you mean with "Template" ? Template for what?

Please be specific when you file issues and post related examples which could help understand the context. As it looks right now it's impossible to understand what your needs are.

**Comment by barrosgeraldo** [comment]
@ranjithrajvasam ping

**Comment by elioqoshi** [comment]
Closing this. Please file an issue with more specific description in the future.
