### ISSUE TITLE
mozilla security logo under new mozilla brand

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/OpenDesign#135]
## Goal: 
Mozilla Security logo, with the new brand

## Info: 
There are various security teams within Mozilla. I assume most of them are interested.

## Style Information: 
Given that the new mozilla brand is stylized as a URL, I suppose a lock icon would make sense.
Not sure if this is OK with the brand team, but as an anology to https, moz**s**://a would be ... interesting?

## Deadline: 
no deadline.

## Tag: 
Design Needed

CCing @elioqoshi as discussed IRL

**Comment by elioqoshi** [comment]
@mozfreddyb Thanks for the request! mozs://a would be a no go so sorry :P

Would this be fine with you?
![1](https://user-images.githubusercontent.com/5436686/27913153-782c9598-625f-11e7-8d06-0378d874d4cf.jpg)


Otherwise there are other directions like these:
![2](https://user-images.githubusercontent.com/5436686/27913154-7a178cdc-625f-11e7-9ce9-c22de73399b6.jpg)

**Comment by elioqoshi** [comment]
![3-01](https://user-images.githubusercontent.com/5436686/27913507-a6190e22-6260-11e7-99f9-b9ba66ad6ef1.jpg)

**Comment by mozfreddyb** [comment]
I'm German my feedback will be terse and direct. brace for impact. 

OK, here we go.

1) my favorite. could we also try a lock? ;D
2) sort of looks like an emoticon to me. an unhappy emoticon
3) I don't understand the blocks around the `m`, really.

**Comment by elioqoshi** [comment]
![4-01](https://user-images.githubusercontent.com/5436686/27915040-5cc547ae-6265-11e7-8541-f59c6bdb15ef.jpg)

Locks and shields are so cheesy but hey, there aren't many other alternatives. This one might make it a little more special though (this is also my favourite)

**Comment by jvehent** [comment]
Lock is the international symbol for security, so it makes sense to me.
Would there be a clever way to put the lock inside `moz://a`?

**Comment by jonathanKingston** [comment]
The padlock on it's own would likely make a cool sticker too. (The feedback I get from stickers is it's always too big)

**Comment by elioqoshi** [comment]
@jvehen That would be against guidelines, sorry.

**Comment by groovecoder** [comment]
FWIW I like the shield or lock icon best.

**Comment by jonathanKingston** [comment]
I know everyone is super busy however it would be super cool if we could get this signed off for swag/staff stuff at MozFest.

**Comment by elioqoshi** [comment]
@mozfreddyb as said, from what the creative team said, the teams won't get any icons, just wordmarks. So nothing more than "mozilla security". We have to close this I suppose.
