### ISSUE TITLE
mozilla release engineering team logo with new mozilla brand

### ISSUE THREAD

**Issue by garbas** [mozilla/OpenDesign#136]
## Goal: 

Mozilla Release Engineering logo with new brand.

## Info: 

We would use it all accross our internal tools under https://mozilla-releng.net

## Style Information: 

How to style team logos is described at https://mozilla.ninja/logosystem.

## Deadline: 

no real deadline, but it would be nice to switch to new mozilla brand.

## Tag: 

Design Needed

**Comment by elioqoshi** [comment]
Thanks @garbas I will have a look at this within this month :)

**Comment by elioqoshi** [comment]
The reason this was not done is that the new branding decided for teams to not have any icons. Teams will have a wordmark which can be written in Zilla Slab Highlight.

**Comment by garbas** [comment]
@elioqoshi do you maybe have (know of) some example is can borrow?

**Comment by elioqoshi** [comment]
@garbas you can do this by using only Zilla Slab Bold Highlight and Regular Highlight:

![image](https://user-images.githubusercontent.com/5436686/32861864-6cf0a84a-ca56-11e7-9963-df7b2a63cc35.png)

**Comment by elioqoshi** [comment]
@garbas apologies if I closed this too early. If you are okay with having a wordmark logo I can do it for you, however it's supposed to be very easy for anyone to do themselves, so you can basically write it down in Zilla like:

mozilla
RelEng

and it appears the same as what I showed before. Make sure to use colors from the style guide at https://mozilla.ninja as well

Let me know if you need help!

**Comment by garbas** [comment]
@elioqoshi tnx for helping me. Looking at the mozilla.ninja, should I pay attention to the size of the text? What is the spacing? I'm not sure I even know how to do that properly in CSS.

I would definitely make it much easier if I could copy paste the some html/css and change the text to RelEng. Do you know some other team/project that is already using logo like this?

**Comment by elioqoshi** [comment]
@garbas Yeah check out:

https://thimble.mozilla.org
https://mozillafestival.org/
https://developer.mozilla.org

Can't remember any team website right now, but from what I see the sites mostly use SVG instead of styling the text directly in CSS.

Might be a valid way to do it simiarly. Want me to export SVG's for you?

**Comment by garbas** [comment]
> Might be a valid way to do it simiarly. Want me to export SVG's for you?

@elioqoshi that would help a lot. I'm also ok with using the CSS approach, whatever is easier for you.

**Comment by barrosgeraldo** [comment]
@elioqoshi, please, could you send it to repository so we can close it. Thanks.

**Comment by kindavishal** [comment]
Hey everyone! Is the issue resolved or do you need any help with it anymore?
