### ISSUE TITLE
Need card templates recreated: Frightful Five, Firefox Five

### ISSUE THREAD

**Issue by peiying2** [mozilla/OpenDesign#137]
## Goal: 
The card I got at the marketing closing meeting at SF all hands

## Info: 
The l10n communities would like to see this as a template so they create the localized versions.  Chances are they will print the card locally or post the images on various social media channels. 

## Style Information: 
If the original template(s) can't be located, then please create something close to this, postcard size, double sided.

## Deadline: 
Not urgent, but hopefully soon.

**Comment by barrosgeraldo** [comment]
Hi @peiying2, do you have a picture of this card?

**Comment by peiying2** [comment]
Here you go:
[Firefox5.pdf](https://github.com/mozilla/OpenDesign/files/1157849/Firefox5.pdf)
[Frightful5.pdf](https://github.com/mozilla/OpenDesign/files/1157850/Frightful5.pdf)

**Comment by barrosgeraldo** [comment]
Hi @peiying2, thank you.

These are simply easy to recreate in Illustrator, I'll just ping @elioqoshi to see if it's the branding or marketing team that has the source file. However, if it does not, I can recreate it next week.

**Comment by peiying2** [comment]
@barrosgeraldo Thanks to YOU!

**Comment by barrosgeraldo** [comment]
Hi @peiying2, We did not find this art anywhere, but I've recreated it now and it's already available here in our repository.

Thank you for your request and have a nice day. :D

![card_frightful_five_firefox_five_1](https://user-images.githubusercontent.com/14970832/28400472-b4007e88-6ce9-11e7-89bd-4c378480f07e.png)
![card_frightful_five_firefox_five_2](https://user-images.githubusercontent.com/14970832/28400471-b2e9d2d8-6ce9-11e7-870b-2a6369bf2e8c.png)

**Comment by peiying2** [comment]
@barrosgeraldo The l10n communities thank you!!

**Comment by barrosgeraldo** [comment]
Heey, you're welcome. 

I found 2 typos, in the word "Firefox" and "That's", I'll fix tomorrow, I'm sorry.

**Comment by barrosgeraldo** [comment]
Heey, you're welcome. :)

Fixed for now.
![card_frightful_five_firefox_five_1](https://user-images.githubusercontent.com/14970832/28401354-cc7a7008-6cef-11e7-8c08-8f1ccd8f9825.png)
![card_frightful_five_firefox_five_2](https://user-images.githubusercontent.com/14970832/28401355-ccd27686-6cef-11e7-87eb-5b3fff572b07.png)
