### ISSUE TITLE
Need Graphics for Independence Day [India] 

### ISSUE THREAD

**Issue by cbaba20** [mozilla/OpenDesign#141]
## Goal: 
Need two graphics for Independence day celebration in India.
## Info: 
It will showcased on 15-August (which is our country Independence day) on different social media channel . Such as Mozilla India Fb and Twitter. See Ref: https://en.wikipedia.org/wiki/Independence_Day_(India)
## Style Information: 
It should reflect our rich culture along with diversity and bond with rest of world via Mozilla. Ref for Indian flag : 
https://en.wikipedia.org/wiki/Flag_of_India
## Deadline: 
13-August 2017. So even if few things can incorporated at-least a day before.

## Tag: 

#Design Needed #IndependenceDay17 #CoverImage #DesignerNeeded

**Comment by barrosgeraldo** [comment]
Over this to @elioqoshi :-)

The simple draft is here. Thank you @cbaba20 for your guidance today.

[india_independence_day.pdf](https://github.com/mozilla/OpenDesign/files/1219143/india_independence_day.pdf)
![india_independence_day](https://user-images.githubusercontent.com/14970832/29232776-d8ece74a-7ec3-11e7-9488-a17c60ce727f.png)

**Comment by cbaba20** [comment]
Thank you @barrosgeraldo and @elioqoshi for your unmatched energetic support (y) . Here is one updated version : 
![photo5798686564270844518](https://user-images.githubusercontent.com/8758288/29241087-2af97220-7f27-11e7-9179-e9ae84131cf7.jpg) 
which looks fine  and most probably with few more tweaks it will be perfect fit for the objective.

**Comment by barrosgeraldo** [comment]
Thank you for your request. You're welcome. Pushing and closing this one.

**Comment by elioqoshi** [comment]
@barrosgeraldo please don't push this to the Repo. The design used here required attribution and is incompatible with the license. Delete it again if required. It should be fine for the usage here but not for reusing it.

**Comment by barrosgeraldo** [comment]
Okiedokie. Removed. :)
