### ISSUE TITLE
Need a graphics for Ed-al-Adha 

### ISSUE THREAD

**Issue by cbaba20** [mozilla/OpenDesign#142]
## Goal: 
Need a graphics for Ed-al-Adha 2017

## Info: 
It will be used on Mozilla India Social Media Channels on the respective day.  

## Style Information: 
Second Last year we have [This](http://bit.ly/2vstFcQ) graphics ,so more or less it will be similar (portrait the objective ) Ref : [Wiki](http://bit.ly/1KUn9fC)

## Deadline: 
28-August-2017

## Tag: 

#DesignNeeded #DeveloperNeeded

**Comment by tanzeelkhan** [comment]
I will work on it :)

**Comment by cbaba20** [comment]
Thanks @tanzeelkhan . You owe a cookie 💯
