### ISSUE TITLE
Firefox Nightly Champions marketing design for Mozilla Brazil community

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/OpenDesign#143]
## Goal: 
We're need 5-8 images for Facebook and Twitter to promote Firefox Nightly and having more people using Nightly in Brazilian lands.

## Info: 
We need 5-8 images about Firefox Nightly, simple and objective, ready to post to our Brazilian accounts. We do not need covers or profile images.

## Style Information: 
Inside the Firefox Nightly branding

## Deadline: 
31/Aug

**Comment by barrosgeraldo** [comment]
I'm opening this one to add the artwork and get feedback when they are ready.

**Comment by barrosgeraldo** [comment]
![prancheta 7firefox_nightly_champions](https://user-images.githubusercontent.com/14970832/29235957-916a23d0-7eda-11e7-81f6-a42e3b9518c6.png)
![prancheta 8firefox_nightly_champions](https://user-images.githubusercontent.com/14970832/29235956-91691f76-7eda-11e7-9721-57279051fddc.png)

**Comment by elioqoshi** [comment]
Love this @barrosgeraldo! Great job!
