### ISSUE TITLE
Presentation slides for Internet Health Report aligned with Mozilla branding

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/OpenDesign#144]
## Goal: 
We need slide decks for [The Internet Health Report](https://internethealthreport.org/v01/) aligned with the Mozilla branding.

## Info: 
This will be used in online and offline presentations about the report in countries around the world.

## Style Information: 
https://docs.google.com/document/d/1iQ3eLc8Q9yoUoHa9cDlvtzZYwb-dbR8iTAuEtIGw51I/edit#heading=h.jocmb9ty4f8h

https://docs.google.com/presentation/d/1wNFCmav3wxCHxz7efJXzop-ak8XKLGs518cIf8KefeU/edit#slide=id.p4

Old slide decks embedded at [[Mozilla at] CryptoRave 2017 — 24 hours for privacy and freedom in the network](https://geraldobarros.me/mozilla-cryptorave-2017-24-hours-privacy-freedom-network/)

## Deadline: 
31/Aug

## Tag: 
[Design Needed]

**Comment by barrosgeraldo** [comment]
working on it into week.

**Comment by elioqoshi** [comment]
@barrosgeraldo you good to take this on?

**Comment by barrosgeraldo** [comment]
Hi @elioqoshi, you can see the [work progress](https://github.com/mozilla/OpenDesign/blob/master/2017/Slide%20Decks/Internet%20Health%20Report/mozilla_internet_health_report_speaker_decks.pdf) here, the slide decks is provide by Solana, the report editor, the guidelines is on [mozilla.ninja](https://mozilla.ninja) and the [newest report is here](https://internethealthreport.org/).

My work will be based on Mozilla's official website > Internet Health Report Website + Mozilla's Branding Guidelines. I can get feedback with Solana since we are already working to grow Internet Health activities in Brazil.

**Comment by barrosgeraldo** [comment]
All ready, unfortunately I can not add here because Github does not accept files larger than 100mb, if anyone is interested, you can [download from my Dropbox account](https://www.dropbox.com/s/1t8h8ffoqloigas/mozilla_internet_health_report_speaker_decks.pdf?dl=0).

**Comment by barrosgeraldo** [comment]
Backup: https://mega.nz/#!054jnKoZ!1ITun5_rT0QUctVOXNyvrO7xdz-jqNHqdWOoQXNCEm4
