### ISSUE TITLE
Feedback needed for MozActivate Website design

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/OpenDesign#148]
## Goal: 
We have gathered quality feedback to launch the new branding of activate.mozilla.community.

## Info: 
Please give feedback on https://github.com/mozilla/activate.mozilla.community/issues/283 . All necessary screenshots are there as well as a quick explanation.

## Deadline: 
August 22nd

## Tag: 
[Feedback needed]

**Comment by barrosgeraldo** [comment]
Hi @MichaelKohler,

I really appreciate your coming on our team for feedback.

And as Elio said earlier, I believe working on a website similar to Mozilla Festival can be interesting and aligned, it's a simple and clean website.

Anyway, I would like to work this week on a **simple draft drawing** based on MozFest website that's open and then can be easy to create a remix, **maybe**.

**Comment by barrosgeraldo** [comment]
![mozactivate_2017_ui_draft](https://user-images.githubusercontent.com/14970832/29299231-92ed5bbc-8143-11e7-8a13-d55fe94ace23.png)

**Comment by barrosgeraldo** [comment]
I think had plenty of time for feedback on that. Closing, if necessary we can reopen.
