### ISSUE TITLE
Design a logo for MozGuj - Mozilla Gujarat community.

### ISSUE THREAD

**Issue by moingshaikh** [mozilla/OpenDesign#151]
## Goal: 
Design a logo for MozGuj - the Mozilla Gujarat community. The logo will be used as a representational identity for the community.

## Info: 
We have already designed the logo that you can refer 
and would like some improvement in it especially in the "Gujarat" part.

## Style Information: 

We have already designed the initial version of the logo which you can see below:

![final-high-resol-logo](https://user-images.githubusercontent.com/7282553/29425420-d137d9b0-83a0-11e7-8581-c3ce25e40c99.png)

The logo is made up of two words strings - MOZILLA and GUJARAT.
Here's what we are actually looking to get help with:
- We would like some rework and more creative thoughts input on the string/word GUJARAT which is represented in a English-Gujarati dialect language.
- The GUJARAT word in English-Gujarati dialect reflects the Gujarat's cross-culture and living style and we would like to make it further creative and more eloquent.
- The logo should be reworked on by following the [Mozilla Style Guidelines.](https://mozilla.ninja/)
## Deadline: 
31st August 2017.

## Tag: 
[Design Needed, Logo Design Needed, MozGuj, Mozilla Gujarat]

**Comment by moinshaikh** [comment]
@rowdymehul

**Comment by barrosgeraldo** [comment]
Hi @ moinshaikh, thank you for your request. Mozilla branding team is working on guidelines for community logos, so when it's available we'll return back here with updates.

**Comment by moinshaikh** [comment]
Thank you @barrosgeraldo for the update! Looking forward to see the community logo guidelines soon :) 
+1:

**Comment by pransh15** [comment]
@barrosgeraldo Any updates?
Please close this issue if it's done.

**Comment by kindavishal** [comment]
@pransh15 I guess the community has started using a logo as I can see on the social media handles, you'll know that better. We can close this issue if you can verify.

**Comment by pransh15** [comment]
Oh, yes! It's all settled.
Closing the issue. 🎆
