### ISSUE TITLE
Update Mozilla Hispano's logo with new branding

### ISSUE THREAD

**Issue by Skatox** [mozilla/OpenDesign#153]
## Goal: 
Hello, I'm writing you to get an updated version of Mozilla Hispano's logo with the new Mozilla font/branding.

## Info: 
We use 2 logos, a font only version and a version with the gecko. We would like to have both versions with the new branding.

## Style Information: 
Here you can get all information about the logo in spanish: https://www.mozilla-hispano.org/marca/
You can download logos from these urls:
https://www.mozilla-hispano.org/archivos/marca/mh-banner.svg
https://www.mozilla-hispano.org/archivos/marca/mh-banner-v.svg
https://www.mozilla-hispano.org/archivos/marca/mh-brand.svg

## Deadline: 
It would great to have in the next month so we can update all our site with the new branding.

## Tag: 
Design Needed

**Comment by barrosgeraldo** [comment]
Hi @Skatox, thank you for your request. Mozilla branding team is working on guidelines for community logos, so when it's available we'll return back here with updates.

**Comment by karlalhdz** [comment]
Here I leave a proposal that took some time, I design it based on what's in https://mozilla.ninja/, adapt a little to the gecko to fit better and what's the rectangle a little easier the stroke but without losing the essence of what they already had. In case it is useful.

![seleccion_134](https://user-images.githubusercontent.com/2287630/32029582-cfa19e4a-b9b2-11e7-938a-73d9c5236648.png)

**Comment by Skatox** [comment]
Awesome! I love them :D

**Comment by elioqoshi** [comment]
@karlalhdz that looks good! The hispano part is not aligned as it should be vertically and horizontally and you might want to consider using more colors (green?). Can you share the source files here?

In any case, seems the branding team has never got back to us regarding community branding so I'm unsure of what to do. Might be worth just going with this for now.

**Comment by karlalhdz** [comment]
@elioqoshi thank you! yeah If you still do not put community branding for now I base myself on the logos that have been officially published as those of MDN and Ninja. 

And if I think we'll have to wait for now we're working on Hispano to adjust the design of the page and the logo, with the colors so if there is a proposal with the colors of the branding that can be downloaded under the taste of each whoever wants to use it will all be available.
![photo_2017-11-13_10-42-58](https://user-images.githubusercontent.com/2287630/32737374-7a5bdeb2-c85f-11e7-9914-1720f1545f51.jpg)
