### ISSUE TITLE
Stickers for the Accessibility Design Drive

### ISSUE THREAD

**Issue by rosanardila** [mozilla/OpenDesign#154]
## Goal:
Format: Stickers

The team is looking to have a visual point of cohesion around the experiment. Stickers are valuable for participants and so can be used both for getting people together around something, word of mouth and prizes. 

## Info:
The open innovation team is running a decentralized ideation experiment with Stanford University: https://mzl.la/a11ydesign

We would like to have exclusive stickers for the participants of this design sprint!

## Style Information:
We would like it to be standard stickers
Ideas here: https://app.mural.ly/t/osclubs0536/m/osclubs0536/1502715200518

## Deadline:
September 15th

## Tag:
Design Needed.

**Comment by barrosgeraldo** [comment]
Hi @rosanardila, great see you here!

The link for ideas is broken. :(

**Comment by elioqoshi** [comment]
@rosanardila Seems there is some time for this. Thanks for requesting this early. Can you fix the link so we can brainstorm more?

**Comment by the207life** [comment]
Out of curiosity, is this still happening? Took part and would love one.

**Comment by newenglandfall** [comment]
Out of curiosity, is this still happening? Took part, and would love one.

**Comment by pari0770** [comment]
Here's a concept!
![mozilla_sticker](https://user-images.githubusercontent.com/12581562/30345497-e53c94f0-9822-11e7-918a-dfdafd3b2827.jpg)

**Comment by barrosgeraldo** [comment]
Hi @pari0770,
Awesome work! I've two suggestions to align this to Mozilla Branding:

- Use Zilla Highlight Regular on project name.
- Try and show some exemples using [Mozilla colors on Visual elements](https://mozilla.ninja/visualelements/).

Cheers,

**Comment by pari0770** [comment]
Hey @barrosgeraldo thanks for the feedback
Here's an iteration with the changes you've suggested, and I have used Mozilla's brand colors to create some different variants.    
![artboard copy 2](https://user-images.githubusercontent.com/12581562/30388997-34a8ff22-98cf-11e7-82c5-e67635d0ff30.jpg)
![artboard copy 3](https://user-images.githubusercontent.com/12581562/30388998-34da6fa8-98cf-11e7-8d63-5c21381c5da8.jpg)
![artboard copy](https://user-images.githubusercontent.com/12581562/30388999-34e6f534-98cf-11e7-95b6-4332653f1d14.jpg)
![artboard](https://user-images.githubusercontent.com/12581562/30389000-35002ebe-98cf-11e7-822a-d1c899cd8ffd.jpg)

**Comment by barrosgeraldo** [comment]
Aweeesome! Great work! Could you add (send a pull request) the source file (svg, AI, EPS ...) and png to the repository? Let me know if you need any help.

**Comment by barrosgeraldo** [comment]
Hi @rosanardila, [the stickers are ready on repository](https://github.com/mozilla/OpenDesign/tree/master/2017/Swag%26Printouts/Accessibility%20Design%20Drive), do you approve or need any review/change?

**Comment by rosanardila** [comment]
Wow, these look great, thank you so much @pari0770!
Apologies for not getting back to you earlier, the notifications got lost in my inbox.
Also thank you so much @elioqoshi and @barrosgeraldo!
I think we will go on and print the green ones :) Thank you sooo much!!

**Comment by newenglandfall** [comment]
That green design looks awesome.

**Comment by pari0770** [comment]
@rosanardila @newenglandfall Thank you!
