### ISSUE TITLE
Infographic of Mozilla localization processes

### ISSUE THREAD

**Issue by gueroJeff** [mozilla/OpenDesign#155]
## Goal: 
We would like to have an infographic/diagram of the various localization processes as Mozilla. Ideally, this graphic would be translatable, accurate, and comprehensive. It could be shared online and available for print.

## Info: 
This graphic will be used within Mozilla documentation for localization and as training materials for anyone recruiting new localizers.

## Style Information: 
Localizer documentation can be found here: https://github.com/mozilla-l10n/localizer-documentation . Each PM from the l10n-drivers is willing to join a call with designers to answer questions and clarify process details. If the processes aren't clear from the documentation, it would be helpful to us to know in order to simplify and improve it.

## Deadline: 
September 22, 2017

## Tag: 
[Design Needed, Staff Support Needed]

**Comment by elioqoshi** [comment]
@gueroJeff this got left behind, sorry about that. :(
