### ISSUE TITLE
Mozilla Andhra Pradesh and Telangana Logo

### ISSUE THREAD

**Issue by bhavabhuthi** [mozilla/OpenDesign#156]
## Intro:
Andhra Pradesh and Telangana are two states in India with a combined population of around 85 million with Telugu as common language.

## Goal: 
Mozilla Andhra Pradesh and Telangana is an emerging community with active volunteers in different cities/towns. Branding would help promote and increase the outreach of this community. 

## Info: 
For any Mozilla activities in the states.

## Style Information: 
The logo could represent the commonalities between the states, something like Telugu Language. 

## Deadline: 
No Deadline [appreciated if done as soon as possible]

## Tag: 
[Design Needed, Logo Needed, Regional Group]

**Comment by kshithijiyer** [comment]
There are not many similarities why not make a logo which gives equal importance to both the states?

**Comment by barrosgeraldo** [comment]
Hi @kshithijiyer, thank you for your request. Mozilla branding team is working on guidelines for community logos, so when it's available we'll return back here with updates.

**Comment by cbaba20** [comment]
@kshithijiyer you can watch updates from here #159

**Comment by sainithin95** [comment]
![ap tslogo](https://user-images.githubusercontent.com/12968789/31336241-9776dc5c-ad13-11e7-8e38-0c999375fdb7.png)

**Comment by sainithin95** [comment]
i have written in Telugu because 
Telugu is the language used in both the states which can help every one in the state to reach easily

**Comment by sainithin95** [comment]
[ap&tslogo.pdf](https://github.com/mozilla/OpenDesign/files/1369470/ap.tslogo.pdf)

with Multiple Telugu fonts

**Comment by kindavishal** [comment]
Hey @bhavabhuthi!
Thanks for the issue! I see the community has started using the logo in English version of the same logo posted above.
If no other inputs are needed, I'll close this issue, let me know at the earliest!
Thanks :sparkles:
