### ISSUE TITLE
Alignment with Mozilla Branding team to start designing community logos

### ISSUE THREAD

**Issue by cbaba20** [mozilla/OpenDesign#159]
## Goal: 
Alignment with Mozilla Branding team to start designing community logos

## Info: 
Community logos are now outdated and required to adapt new according to new brand guidelines.

## Style Information: 
Not Required

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by barrosgeraldo** [comment]
Hey @cbaba20, thanks here. I mailed to Branding updates mailing list (brand-updates@mozilla.org) and Yuliya. This issue will only be updated when I receive a reply.

**Comment by cbaba20** [comment]
Thanks @barrosgeraldo for the update. I will keep a watch on this bug.

**Comment by barrosgeraldo** [comment]
Note here: anyone reply from branding team not has been made until now.

**Comment by barrosgeraldo** [comment]
@cbaba20, anyone has replied me, I no longer have hopes that they will do this, so I believe we can consider creating logos based on [current guidance](https://mozilla.ninja/expression/).
