### ISSUE TITLE
Firefox Onramp Site Improvements

### ISSUE THREAD

**Issue by mhoye** [mozilla/OpenDesign#16]
I've ginned up this site:

http://areweeveryoneyet.org/onramp/

... as a choose-your-own-adventure to help get people involved in developing for the core Mozilla products. 

It could use a lot of love. 

The code lives here:
https://github.com/mhoye/onramp

and the community's assistance in making it work and flow well would be greatly appreciated.

**Comment by LucyeoH** [comment]
Hey @mhoye what kind of design do you need here?

**Comment by mhoye** [comment]
I'd like to keep the general choose-your-own-adventure and step-by-step formats intact, so what I'm really looking for here is:

- Dramatic improvements to the appearance
- The addition of this community to the other-options section, and
- any additional exit points we can add to that page added as well.

**Comment by elioqoshi** [comment]
Thanks @mhoye !
I think Jan Dittrich should be interested in this (can't find his username)

**Comment by seeam** [comment]
Hi, I am interested to help with the visual improvements of appearance. But as I am not a coder I can only provide an image mockup/preview. May be in PSD/ JPG format. Will it help, @mhoye?

**Comment by elioqoshi** [comment]
@seeam I believe that would be highly helpful :)

**Comment by anistuhin** [comment]
Great @seam go on. I will be helping as developer, hopefully.

**Comment by jdittrich** [comment]
Hi, I am the mentioned @jdittrich

**Comment by jdittrich** [comment]
I'm not sure if I am the right person to help here (mainly do usability & target group needs, but less UI) and the tasks asked for seem to be more geared towards UI/Graphic Design (?)

**Comment by mhoye** [comment]
I think so, yes - graphics design would be much appreciated. Even a nominal amount of good taste would help!

**Comment by jdittrich** [comment]
From my experience, it could be really helpful to show some video snippets with the tasks to do. (It would be great btw. if one could get early feedback from people who use the page. E.g. one could make the "deal" to observe first and help if they can't do it themselves. Could be a win-win situation)

**Comment by mhoye** [comment]
We have some of those here, I think:

http://www.codefirefox.com/

Maybe we can use them?

**Comment by mhoye** [comment]
ARGH MISCLICKED.

NOBODY LEAVE.

**Comment by jdittrich** [comment]
The videos you linked would be totally right. 

Maybe you could collaborate or mirror each other's content? It would be a great match.

**Comment by elioqoshi** [comment]
@yofiesetiawan can you chime in here?

**Comment by seeam** [comment]
Hello @mhoye, I was busy with personal projects. Here is my try to improve the visual look of homepage. I have tried to follow the community sandstone guideline and grid. What do you think about it?  
![homepage](https://cloud.githubusercontent.com/assets/7550283/12774130/004a9516-ca6c-11e5-9305-6b57d420f2b5.jpg)

**Comment by yofiesetiawan** [comment]
Hi, i'm interested to pitch here...

![firefox-onramp](https://cloud.githubusercontent.com/assets/2810823/12775206/c0df0fc0-ca7e-11e5-851a-451fbb8a2d51.png)

**Comment by LucyeoH** [comment]
@mhoye looks like you have two awesome pitches! What do you think?

**Comment by Mte90** [comment]
What is the developer help required?

**Comment by elioqoshi** [comment]
@Mte90 We probably need help to turn the design into code

**Comment by elioqoshi** [comment]
P.S: Love the suggestions guys! I prefer the one by @yofiesetiawan slightly, it looks really solid

**Comment by anistuhin** [comment]
Btw guys, we have several pages to design for this, right?? So, are we just choosing the homepage first and will go up based on that or having mocks for all at once will look better or get it understood clearly?? And I second @elioqoshi on the one done by @yofiesetiawan

**Comment by elioqoshi** [comment]
@anistuhin we can design only 2 or 3 pages which will work like a template I guess?

**Comment by mhoye** [comment]
I'm pretty sure that if you click around the site, you'll find that you need three at most, and more likely just two - one for the introductory page, and one for all the choices further down the tree.

**Comment by elioqoshi** [comment]
@mhoye which mockup do you prefer?

**Comment by anistuhin** [comment]
Yeah, my bad. I didn't go through the contents but only the GitHub repo :P There really are only two to work on.

**Comment by Mte90** [comment]
I can help for the code. I will wait for the confirm of the design.

**Comment by LucyeoH** [comment]
@mhoye can you confirm the design??

**Comment by mhoye** [comment]
Man, how did I miss these? They both look great, but I'm leaning towards @yofiesetiawan's proposal.

**Comment by yofiesetiawan** [comment]
@mhoye hi, here is the psd file, can someone help to slice and code? i'm just a psd guy...
sorry i've tried to drag and drop the file here, but it says it doesn't support, not sure why, it's a zip file. Please download from this dropbox link https://dl.dropboxusercontent.com/u/4450713/mozilla/firefox-onramp.zip

**Comment by mmhyamin** [comment]
@mhoye and @yofiesetiawan so, this is final? @Mte90 how about a helping hand?

**Comment by yofiesetiawan** [comment]
@mmhyamin usually after slicing and make it online, we need some adjustment.. i would love to help to do revisions needed if there's any...

**Comment by mmhyamin** [comment]
@Mte90 I will be able to start coding from 28th February. I will use 

1. Package Management System: Bower
2. CSS Preprocessor: SCSS
3. CSS Framework: Bootstrap 3.

If you have any suggestion let me know.

**Comment by Mte90** [comment]
For me is ok do you will use grunt or gulp?
I can help you in that ticket when you start to work on that.
I keep in touch with you by email in case if there are problems.

**Comment by mmhyamin** [comment]
Here is the demo site link: [http://mmhyamin.github.io/onramp-test/](http://mmhyamin.github.io/onramp-test/)
Source: [https://github.com/mmhyamin/onramp](https://github.com/mmhyamin/onramp)

**Comment by yofiesetiawan** [comment]
@mhoye do you need inside pages?

**Comment by mhoye** [comment]
I don't think so, but let me get this stood up on the site tomorrow and I'll tell you for sure.

**Comment by elioqoshi** [comment]
Amazing teamwork guys! @mhoye let me know if you need anything else here :)

**Comment by elioqoshi** [comment]
Oh, also don't forget to push the source files to our repo and/or link on here after finished

**Comment by elioqoshi** [comment]
What's the state of this @mhoye ?

**Comment by Mte90** [comment]
The state that we are waiting a code review of the code from @mhoye

**Comment by elioqoshi** [comment]
Please update @mhoye
