### ISSUE TITLE
T-shirt for Firefox 57 Sprint campaign

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/OpenDesign#161]
## Goal: 
A t-shirt design

## Info: 
Firefox 57 Sprint campaign (http://firefoxsprint.mozilla.community/)

## Style Information: 
I don't have specific things in mind. Talked with Elio and he agree to help here. So I'll leave it to him. 

## Deadline: 
18 September 2017

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
![draft-01](https://user-images.githubusercontent.com/5436686/30483351-f1fc977a-9a26-11e7-9bbd-6b7c3fdf1918.jpg)

Here are a few variations. What do you think @kelimuttu ?

**Comment by kelimuttu** [comment]
Looks nice. I like both the blue and the black one. I agree we should keep the design simple and not particular to the campaign. 

@couci what do you think?

**Comment by couci** [comment]
I like blue and black as well (maybe blue a little bit more). Yes let's keep it simple so we can reuse it.

thanks @elioqoshi

**Comment by kelimuttu** [comment]
Alright. I think we're good here. 

Thankssss @elioqoshi

**Comment by elioqoshi** [comment]
@kelimuttu Do you need any thing for the printer? The designs are separate, but you have them I guess. They just need to be arranged on the T-Shirt. I guess the mockup should be enough for the printer.

**Comment by kelimuttu** [comment]
@elioqoshi Yep. I send them to the vendor already. I hope that will be enough. I'll let you know in case it's not.
