### ISSUE TITLE
Image/poster/collage with Firefox Quantum headlines

### ISSUE THREAD

**Issue by nukeador** [mozilla/OpenDesign#172]
## Goal: 
We were talking at Hispano community that since there are so many positive articles from big media in Spanish, we should do a collage with all the headlines with a nice design.

## Info: 
Ideally a template file will be generated so people can add their local headlines in their language.

## Style Information: 
Quantum/Photon style :-P

## Deadline: 
It would be idea to have something to publish by the end of today.

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
@nukeador wrapped up and pushed here:
https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/Firefox-Quantum-Headlines-Spanish
