### ISSUE TITLE
Logo for Coding foundation

### ISSUE THREAD

**Issue by trallard** [mozilla/OpenDesign#175]
## Goal: 
We are [coding foundation](https://github.com/trallard/Coding-foundation) a Mozilla Open Leaders project (woohoo)! Our main goal is to increase the number of female and queer individuals in computer science and similar degrees. We plan to do so by creating a welcoming and supportive community, showcase role models, and collect resources that could help these individuals to increase their technical skills and confidence.
 We will be launching our website soon and we'll be then ready to start engaging more people within the community. We are in the quest for a suitable logo for our project. 

## Info: 
We encourage contributions of logos that can be used in the following ways:
- banner for the website
- stickers

## Style Information: 
We are a project aimed to increase the number of female and queer individuals enrolling in computer science degrees and tech-related areas all over the world. So we want a logo that reflects such community building and inclusivity efforts.
We love colourful things so feel free to be creative!
Ideally, we'd love to have hex stickers (see [StickerSpec](https://github.com/terinjokes/StickerConstructorSpec))

## Deadline: 
Mid-December (we are aiming to launch the website by then)

## Tag: 
[Design needed]

**Comment by elioqoshi** [comment]
@trallard thanks for your request!

Some more details regarding what you'd like to see implemented would be ideal.  I did a proposal here, let me know if this direction works or whether it's not fitting:

![image](https://user-images.githubusercontent.com/5436686/33628705-ef7a2ad8-da01-11e7-80d4-154450f971b1.png)

**Comment by trallard** [comment]
Hi @elioqoshi thanks a lot for your proposal :blush: I did not want to give too much details as not to constraint it too much. But I like what you have come up with. This should work great for banner purposes and general logo.

Would it be possible to generate a condensed version of this so that it can fit in stickers (see above) apart from that I am quite happy with this :grin: thanks again!!! 

Also is these could be shared in .PNG or .SVG would be ideal

**Comment by elioqoshi** [comment]
@trallard Splendid!

Is this fine for the stickers?
![image](https://user-images.githubusercontent.com/5436686/33633215-4efa48cc-da10-11e7-93aa-0ceaeb09b607.png)

**Comment by trallard** [comment]
@elioqoshi I like the way the things are organised.... however it seems there is too much colour going on there, apologies for the extra request. Would it be possible to have the colors the following way around:

- green outline
- orange logo
- grey wordings
- white background

That way it would be more in line with the banner logo and has a high contrast! 😃 Thanks so much for all your help!

**Comment by AnXh3L0** [comment]
Hi @trallard 

Is this what you had in mind?
![image](https://user-images.githubusercontent.com/25004151/33662674-01414a04-da8d-11e7-8abe-b09f9a532522.png)

**Comment by AnXh3L0** [comment]
@trallard Awesome then, if you don't need smth else I'm uploading the source files [here](https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/Coding_Foundation). There you will find the complete sources, the logo in horizontal, vertical and the icon itself (color, black, white versions) and the hexagon stickers :)

**Comment by elioqoshi** [comment]
Thanks @AnXh3L0 closing this.

@trallard good luck!
