### ISSUE TITLE
Sticker/logo design for "Scientific Computing for the Rest of Us"

### ISSUE THREAD

**Issue by tpoisot** [mozilla/OpenDesign#176]
## Goal: 

I'd like to have a logo for the [Scientific Computing for the Rest of Us][scru] project. The project goal is to help researchers develop good practices when writing code, to make sure that we can *trust* the results.

The issue re. logos is here: https://github.com/tpoisot/ScientificComputingForTheRestOfUs/issues/17

[scru]: https://github.com/tpoisot/ScientificComputingForTheRestOfUs

## Info: 

It will be used for hex stickers, with (most likely) a larger version with text at the side.

## Style Information: 

The logo should be usable on a hex sticker: https://github.com/terinjokes/StickerConstructorSpec

## Deadline: 

Sometime in January would be excellent.

## Tag: 
Design Needed

**Comment by barrosgeraldo** [comment]
Hi @tpoisot, I think you've a great proposal made by @juanvillada on https://github.com/tpoisot/ScientificComputingForTheRestOfUs/issues/17. Let us know if this is enough or if you need something different.

**Comment by barrosgeraldo** [comment]
Any update here?
