### ISSUE TITLE
Profile Picture frame

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/OpenDesign#177]
## Goal: 
Create a profile pic frame with the slogan "Once a mozillian, always a mozillian." with Mozilla logo.

## Info: 
This frame can be used for facebook profile pictures.

## Style Information: 
Check https://www.facebook.com/profilepicframes for existing profile pic frames.

## Deadline: 
Dec 31, 2017.

## Tag: 
[Design Needed, frame]

**Comment by sai-bhavani** [comment]
![frame](https://user-images.githubusercontent.com/21965145/33514458-501a10ea-d77a-11e7-9852-5f8708439485.jpg)

**Comment by biswajeet619** [comment]
![img_20171204_232343](https://user-images.githubusercontent.com/21312954/33568010-03d2f7f6-d94b-11e7-9889-22e31a27f5bd.jpg)

**Comment by biswajeet619** [comment]
![img_20171204_232343](https://user-images.githubusercontent.com/21312954/33568055-288bfdfe-d94b-11e7-93cc-8bfe5f88efa1.jpg)

**Comment by priyankapulluri** [comment]
![frame4](https://user-images.githubusercontent.com/34267723/33601370-0769f234-d9d2-11e7-9a1f-592300620099.jpeg)
![frame3](https://user-images.githubusercontent.com/34267723/33601371-07aa9294-d9d2-11e7-9c12-78753706b64f.jpeg)
![frame2](https://user-images.githubusercontent.com/34267723/33601372-07e56e14-d9d2-11e7-9cd5-a84d75327415.jpeg)
![frame1](https://user-images.githubusercontent.com/34267723/33601373-081fed1e-d9d2-11e7-9871-21f01bf36138.jpeg)

**Comment by SRenukaR** [comment]
![moz](https://user-images.githubusercontent.com/29282929/33611490-8da08a8a-d9f4-11e7-83a7-5b36a65bd083.jpeg)

**Comment by biswajeet619** [comment]
![img_20171205_231401](https://user-images.githubusercontent.com/21312954/33621844-1a025fc2-da12-11e7-9b1b-14d1c4ca2ec8.jpg)

**Comment by tsriyeswanth** [comment]
![img_20171206_111707_hht](https://user-images.githubusercontent.com/18646444/33646727-12018f90-da77-11e7-9bcf-d4bc1b09f342.jpg)

**Comment by tsriyeswanth** [comment]
![151253932389740923149](https://user-images.githubusercontent.com/18646444/33646755-40a1144c-da77-11e7-8333-486765584dd8.jpg)

**Comment by sainithin95** [comment]
![mozilla](https://user-images.githubusercontent.com/12968789/33648098-47cbe826-da7e-11e7-8e2c-1c0b8cac1505.png)

**Comment by karlalhdz** [comment]
This would be my proposal of the captures of the different views ... :-D

![mozillaframeoncealways1](https://user-images.githubusercontent.com/2287630/33970079-a19a9470-e036-11e7-9140-3129ddebe625.png)

![seleccion_191](https://user-images.githubusercontent.com/2287630/33970065-91777f18-e036-11e7-91d5-ec833a05f4d8.png)
![seleccion_190](https://user-images.githubusercontent.com/2287630/33970066-9190227a-e036-11e7-8137-d197a718b29d.png)
![seleccion_189](https://user-images.githubusercontent.com/2287630/33970067-91ab48b6-e036-11e7-8536-68b4eef7a71b.png)

**Comment by reinhart1010** [comment]
This is nice, but Facebook also crops profile pictures into circles in most parts of the Facebook app.
![Sample of cropped images](https://user-images.githubusercontent.com/17312341/34012093-052f7b2c-e145-11e7-9fbe-d74dec333ae3.png)

**Comment by sanjitschouhan** [comment]
@karlalhdz Can we have the png of elements.

**Comment by barrosgeraldo** [comment]
I love these proposals and suggestions!

@karlalhdz, awesome, you already have a solid proposal, love it, I suggested removing "://", I do not see the need for this in the image, the two titles lined up near to the icon would be awesome!

Let me know if this makes sense, and do not forget to send the source files via [pull request](https://help.github.com/articles/about-pull-requests/) to this repository. 

Have a nice new year folks! 👯 👯

**Comment by barrosgeraldo** [comment]
Any update here?

**Comment by pransh15** [comment]
I've tried re-creating what @karlalhdz did. Looks good to me. What do you say?

![mozillian_profileframe](https://user-images.githubusercontent.com/18158596/35046523-36ea9cea-fbbd-11e7-9427-cefccda789b3.png)
![screen](https://user-images.githubusercontent.com/18158596/35046524-37360c48-fbbd-11e7-821c-3b75a65c50ee.JPG)

**Comment by barrosgeraldo** [comment]
looks great for me.

**Comment by pransh15** [comment]
Awesome, how shall we proceed?

**Comment by barrosgeraldo** [comment]
@ranjithrajv

**Comment by ranjithrajv** [comment]
Thanks, @karlalhdz for the designs, loved 'em and @pransh15 for re-creating it. Can you please share source files of the design.

**Comment by pransh15** [comment]
Sure.

**Comment by pransh15** [comment]
I tried to upload it and even made a PR, but it didn't work.
Anyway, I've uploaded the files here: https://drive.google.com/drive/folders/1IZQK2Ohfr8Pmkvvomat-tXHzStBHvsLZ?usp=sharing

I think we can close this issue now. :)
