### ISSUE TITLE
Create Graphics for Christmas 2017

### ISSUE THREAD

**Issue by cbaba20** [mozilla/OpenDesign#178]
## Goal: 
Graphics for Christmas 2017 for both social media channels. (Facebook and Twitter)

## Info: 
We will use it from our official Mozilla India Social Media channels to greet our users/fans/supporters.
## Style Information: 
It should also reflects our Firefox

## Deadline: 
23rd December

## Tag: 
#DesignNeeded #DeveloperNeeded #StaffSupportNeeded

**Comment by cbaba20** [comment]
Thanks @tanzeelkhan for making the graphics 👍 . 
![photo6194775608018446373](https://user-images.githubusercontent.com/8758288/34388725-56e46764-eb5b-11e7-90d5-5ae5f45c547d.jpg)

**Comment by tanzeelkhan** [comment]
:)
