### ISSUE TITLE
Poster for Rust for Undergrads 

### ISSUE THREAD

**Issue by biswajeet619** [mozilla/OpenDesign#179]
## Goal: 
 Poster of the event known as "Rust for undergrads" giving a short description about how it is to be a Mozillian and giving a short description about Rust programming language.  Venue is Swecha office, Gachibowli, hyderabad.
## Info: 
Event for Rust 

## Style Information: 
Heading as "Rust For Undergrads", 
Information about how it's like being an Mozillian and Explanation about Rust programming language as immediate headings, 
Providing the event  location as : Swecha office, Gachibowli, Hyderabad.
## Tag: 
[Design Needed]

**Comment by pransh15** [comment]
![rustforundergrads](https://user-images.githubusercontent.com/18158596/34410576-44731b38-ebf7-11e7-93fd-4180a8d0e050.jpg)

Basic Poster. I'm sure you have improvements to suggest. Let me know what's missing.

**Comment by barrosgeraldo** [comment]
@pransh15 awesome poster, I just would like suggest change the colors, you can see the [Mozilla palette here](https://mozilla.ninja/visualelements/). Don't do not forget to send the source file of this poster via pull request on this repository.

Hey @biswajeet619, at Mozilla Brazil community we've [created and used some banners already hosted on this repository](https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/Dive_Into_Rust_banner), it's banners for social media efforts, marketing, etc. 

Based on the information you provided here, and taking this as a printable poster, I made some adaptations of what we have already used here in Brazil. [Download it here](https://github.com/mozilla/OpenDesign/tree/master/2018/Graphics/rust_for_undergrads), see a preview:

![poster](https://user-images.githubusercontent.com/14970832/34450895-3bf16750-ecfe-11e7-88ec-dec619a0b866.png)

Let us know if you've all resources you need, so we can close this one.

**Comment by biswajeet619** [comment]
Thank you all for your efforts ! The posters are looking good and will be used in the event coming by.  @pransh15  @barrosgeraldo thanks.
