### ISSUE TITLE
New identity for Mozilla Venezuela

### ISSUE THREAD

**Issue by ThePhoenixBird** [mozilla/OpenDesign#180]
## Goal: 
Update the identity of Mozilla Venezuela with a new logo and wordmark according to the new visual styles of Mozilla launched during this year 2017.

## Info: 
The identity will be used on our website, social networks (facebook, twitter, instagram, etc), cards, posters, slides, etc ...

## Style Information: 
Mozilla Venezuela has a logo that is deeply rooted in our hearts and is the "Guacamaya de Fuego" [[1](http://mozillavenezuela.org/wp-content/themes/mozve-yoko/images/mascota-mozve.png)] as we call it, it is an emblematic animal in Venezuela [[2](https://es.wikipedia.org/wiki/Ara_(animal))] given that the tropic is its habitat and it is seen flying over naturally by almost all the cities in the country in flocks.

We want to keep the Guacamaya as our emblematic animal, and keep the tricolor (yellow, blue, red) in its plumage which is always quite saturated and bright, we are open to any proposal adapted to the guide of visual styles of Mozilla 2017 and preferably a flat design that is easy to use in multiple purposes whether it's printed material on paper, t-shirts, etc ... as well as for the web.

Reference images [[3](http://1.bp.blogspot.com/-1gqMFFYH1B8/UpNlS5pA9pI/AAAAAAAAAEc/OboOE4YTzyQ/s1600/Ara_macao_-flying_away.jpg)], [[4](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Ara_macao_qtl1.jpg/800px-Ara_macao_qtl1.jpg)], [[5](https://previews.123rf.com/images/prinprince/prinprince1510/prinprince151000304/46980950-hermosa-ave-guacamaya-roja-con-una-bonita-cola-larga-isoalted-en-el-fondo-blanco-Foto-de-archivo.jpg)], [[6](http://2.bp.blogspot.com/-a6QasqcLs4E/TywRC5yZHbI/AAAAAAAAAB4/0T3s4pTboSE/s1600/guaca.jpg)] 

## Deadline: 
When possible :)

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by karlalhdz** [comment]
Just in case, we have a proposal here if someone want's to make a comment, observation or constructive criticism 
  https://github.com/mozillahispano/equipoCreativo/issues/8

**Comment by barrosgeraldo** [comment]
Hello @karlalhdz, your design is awesome! I would like suggest to write "venezuela" using only Zilla Highlight. This bird is beautiful, congrats for this work, you're the best!
Proposal on https://github.com/mozillahispano/equipoCreativo/issues/8.

**Comment by ThePhoenixBird** [comment]
We have finally decided to go with the blue background one designed by @karlalhdz 

Beautiful logo, we all at Venezuelan community are pleased with it

Congratulations!
