### ISSUE TITLE
New Year Graphics from Mozilla India social media channels

### ISSUE THREAD

**Issue by cbaba20** [mozilla/OpenDesign#181]
## Goal: 
Graphics for community wishing New Year to users fans and supporters

## Info: 
Mozilla India Social Media Channels 

## Style Information: 
Anything which is under guidlines

## Deadline: 
1-1-18
## Tag: 
feedback required

**Comment by cbaba20** [comment]
Here are some designs : 
Thanks to tanzeel 👍 

- ![photo6212981304371292137](https://user-images.githubusercontent.com/8758288/34461505-1570d976-ee52-11e7-8f9f-5c64f7d4114b.jpg)

**Comment by cbaba20** [comment]
From Mahtab 👍 
![mozin new year wc](https://user-images.githubusercontent.com/8758288/34461514-54455e2e-ee52-11e7-97e5-fca527371bf9.png)

**Comment by Mahtab05** [comment]
MozIN New year 2018 Ai File.
Uploading MozIN New Year 2018.zip…]()

**Comment by tanzeelkhan** [comment]
Vector File of Mozilla India New Year Greeting Design
https://drive.google.com/open?id=18ey6m0OCfNjP8qj5aSSzLTMLR8_ELOrJ

**Comment by Mahtab05** [comment]
Ai File For MozIN New Year 218
https://drive.google.com/file/d/1-X757kRmwI49Cf7M72R-4v58qy6OCiz6/view?usp=sharing

**Comment by barrosgeraldo** [comment]
Thanks. Pushed. Closing.
