### ISSUE TITLE
Branding for '365 Add-ons in 365 Days'

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/OpenDesign#182]
## Goal: 
Branding and generalized design templates for '365 Add-ons in 365 Days' campaign by Mozilla India.

## Info: 
These generalized design templates will be used for posters, prints, social media posts etc

## Needed:
- [ ] Social Media poster for twitter.
- [ ] Stickers

## Style Information: 
Should incline with the new design language of Mozilla.

## Deadline: 
Jan 30, 2018.

## Tag: 
[Design Needed, Branding]

**Comment by barrosgeraldo** [comment]
Hi @ranjithrajv, thank you for your request! 

I've made a draft based on this Mozilla poster created by branding team since you request a design based on Mozilla branding. Let me know what do you think of this poster draft.

![prancheta 1 3x](https://user-images.githubusercontent.com/14970832/34470841-94016240-ef21-11e7-91ef-2316e66841f4.png)

**Comment by bhavabhuthi** [comment]
Logo Idea: Can you make the 365 pretty big and write "add-ons in days" beside it arranging vertically in three lines.

**Comment by barrosgeraldo** [comment]
This logo idea isn't under Mozilla branding guidelines: https://mozilla.ninja/expression/

@ranjithrajv, do you need a logo?

**Comment by ranjithrajv** [comment]
@barrosgeraldo
the poster is good.
A logo would be good to print on swag

**Comment by barrosgeraldo** [comment]
Here they are:
![logo_background 3x](https://user-images.githubusercontent.com/14970832/34575764-09fa06ee-f163-11e7-9031-82a5e5032e09.png)

**Comment by bhavabhuthi** [comment]
Hii @barrosgeraldo, Tried the following style for the logo. 

![365 addons logo](https://user-images.githubusercontent.com/26624774/34579418-f04d598e-f1ae-11e7-8629-7129bda96eb7.png)

Here is the poster with that logo

![365 addons poster](https://user-images.githubusercontent.com/26624774/34579444-048e0bf0-f1af-11e7-88fe-779105399fa7.png)

**Comment by bhavabhuthi** [comment]
Files for the above ideas are :--

[365 addons poster.pdf](https://github.com/mozilla/OpenDesign/files/1604408/365.addons.poster.pdf)
[365 addons logo.pdf](https://github.com/mozilla/OpenDesign/files/1604409/365.addons.logo.pdf)

**Comment by barrosgeraldo** [comment]
I got it, it's cool, but your logo idea need be created under Mozilla branding guidelines, check it here please: https://mozilla.ninja/expression

**Comment by bhavabhuthi** [comment]
@barrosgeraldo Sure will look into the guidelines. Thanks for the link.

**Comment by caitmuenster** [comment]
Hey all! These are looking good. I would also want to add 'addons.mozilla.org' somewhere on the page. :)

**Comment by barrosgeraldo** [comment]
done, @ranjithrajv, let me know if you need anything else, if not then we can close this.
![prancheta 1 3x](https://user-images.githubusercontent.com/14970832/34902456-cc4f625c-f802-11e7-9540-6131a72767cb.png)

**Comment by barrosgeraldo** [comment]
@bhavabhuthi I love your artwork, can you move the Mozilla logo to the footer? To use "365 Add-ons in 365 Days" as a logo is necessary align with Mozilla branding guidelines, but just using "365 Add-ons in 365 Days" in the banner looks great.

**Comment by ranjithrajv** [comment]
Updated the need for Stickers and Social Media poster for twitter

**Comment by bhavabhuthi** [comment]
@barrosgeraldo I have seen the guidelines and moved the logo to the bottom. 

[365.addons.logo.pdf](https://github.com/mozilla/OpenDesign/files/1649630/365.addons.logo.pdf)

and here is the image

![365 addons logo svg](https://user-images.githubusercontent.com/26624774/35192461-e1ceabda-feb8-11e7-8319-f85600ccc971.png)

**Comment by kindavishal** [comment]
They look great @barrosgeraldo! Certainly going to be useful in the future! :sparkles: 
Thank you for the issue @ranjithrajv :slightly_smiling_face: 
Closing this!
