### ISSUE TITLE
Update Firefox hexbin with the new logo

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/OpenDesign#185]
The Firefox hexbin sticker in https://github.com/mozilla/OpenDesign/tree/master/2017/Swag&Printouts/hexbin_stickers contains the old logo. We should update it with the new Firefox57+ logo for future production.

**Comment by elioqoshi** [comment]
Please don't open issues like this. While it might be straightforward, it is rather inappreciative towards volunteers who spend time on designs when a request is not even properly formed.

On another note, Hexbin seems rather inactive and I'm not sure if they still run properly.

**Comment by MikkCZ** [comment]
Sorry Elio. I have added some text to the initial report.

We are producing hexbins on our own and now we are working to get a new order for DevConf.cz at the end of January. @MekliCZ will make a haxbin with the new realease logo and add it here.

**Comment by MekliCZ** [comment]
I would rather create new hexbin Firefox Quantum than modifying the existing one.
