### ISSUE TITLE
Designs for Aadhaar Campaign

### ISSUE THREAD

**Issue by shashikanth171** [mozilla/OpenDesign#187]
## Goal: 
Designs for Aadhaar campaign

## Info: 
[Aadhaar isn’t progress — it’s dystopian and dangerous](https://blog.mozilla.org/netpolicy/2017/05/26/aadhaar-isnt-progress/)
[ Why do you need Aadhaar to investigate a lost package? ](https://blog.mozilla.org/netpolicy/2017/11/16/need-aadhaar-to-investigate-lost-package/)

This campaign helps reach more people to address tech critic issues of Aadhaar and Mozilla's stance on it in terms of data protection and citizen privacy.

Find more info about Aadhaar Logo [ here ](https://uidai.gov.in/media-center/uidai-brand/aadhaar-logo.html).

## Needed Designs for
- [x] Posters for talks/events on Aadhaar
- [x] Banners
- [x] T-Shirt  Designs
- [x] Stickers & Badges
- [ ] Profile Picture Frame

## Style Information: 
Should emphasize mass surveillance theme.
Add Mozilla Advocacy Logo.
Should include slogan "Aadhaar isn’t progress — it’s dystopian and dangerous" on the design.

## Deadline: 
As soon as possible.
Supreme Court of India has scheduled the hearing of Aadhaar case on Jan 17th. It would be helpful if it is before 17th.

**Comment by pransh15** [comment]
![aadhar_basic](https://user-images.githubusercontent.com/18158596/34784866-836b3c04-f655-11e7-822f-b6cb5f99a35e.jpg)

Something like this?

**Comment by ranjithrajv** [comment]
@pransh15 This seems more like UIDAI doing an event on Mozilla than Mozilla is doing an event on Aadhaar.

**Comment by shashikanth171** [comment]
@pransh15, Please check updated Style information.

**Comment by aspee** [comment]
![untitled-2](https://user-images.githubusercontent.com/1244052/34789657-1f2b426a-f665-11e7-8b00-049c033aea9e.jpg)

![2](https://user-images.githubusercontent.com/1244052/34789773-922bd7de-f665-11e7-8840-b2c81f1db8bd.png)

**Comment by aspee** [comment]
if anyone can smooth those face edges then it is more than welcome

**Comment by ranjithrajv** [comment]
@aspee Please share design source files, so that anyone can edit and make improvements.

**Comment by ranjithrajv** [comment]
Please read and follow: https://mozilla.ninja/mlogo use of coloured background is not advisable IMO
- Ankit Gadgil

**Comment by tanzeelkhan** [comment]
Can't we write: Not only it is an invasion of privacy, but it's not even right.

Moreover, I think the mozilla logo isn't at the right place. It should be at the corner or at the bottom in centre. And it looks too large to me.
Tanzeel Khan:

Keeping the color of logo same as text and illustration, mozilla doesn't look like a different entity, an organisation. I suggest changing the background color and keep the logo color as default black.

**Comment by tanzeelkhan** [comment]
Can we use aadhaar logo in the creatives? Is it permissible?

**Comment by barrosgeraldo** [comment]
Hey folks, please align your artwork with Mozilla branding guidelines, specially if you're using Mozilla logos. Brand application guidelines: https://mozilla.ninja/expression.

**Comment by karlalhdz** [comment]
@pransh15 and @aspee  both great proposals but do not forget to follow the guidelines of the branding https://mozilla.ninja/mlogo/ I do not work for a while, although I would love it, greetings to all.

**Comment by aspee** [comment]
![6](https://user-images.githubusercontent.com/1244052/34814532-05041208-f6d4-11e7-9a38-382c73625950.jpg)

**Comment by ranjithrajv** [comment]
I request all the designers to share source files of these designs in .svg or .ai format

**Comment by aspee** [comment]
It's PSD

https://drive.google.com/open?id=1vhjdPKZuJecRYcxFiypHpwG2kb9WL_kn

**Comment by Hariompanchal** [comment]
This is AI of my image.
https://drive.google.com/open?id=1C8nd94pLhuiE5zDl3Vzy3idbOaNnLjMn
This is SVG Of my image.
https://drive.google.com/open?id=1mmST7zrRvt9yqRANY-0TYUYSxEMaB7j6
This is PSD Of my image.
https://drive.google.com/open?id=1NrISu7L3D_YKJTq9CV_aBSp0yAh5wmSQ

**Comment by barrosgeraldo** [comment]
@shashikanth171, thank you for your request! Here you've my inputs ([download](https://github.com/mozilla/OpenDesign/blob/master/2018/Graphics/aadhaar_campaign/aadhaar_campaign_design_printable.pdf)):
<img width="843" alt="banner 2x" src="https://user-images.githubusercontent.com/14970832/34902365-1f582076-f801-11e7-86a0-011fae8cdb72.png">
<img width="842" alt="poster1 2x" src="https://user-images.githubusercontent.com/14970832/34902366-1f7919f2-f801-11e7-9c71-702538f81893.png">
<img width="843" alt="poster2 2x" src="https://user-images.githubusercontent.com/14970832/34902367-1f9a7412-f801-11e7-83e4-ff25da6dd888.png">
<img width="603" alt="sticker 2x" src="https://user-images.githubusercontent.com/14970832/34902368-1fbb7464-f801-11e7-9229-5efd09125d67.png">
<img width="2151" alt="t-shirt 2x" src="https://user-images.githubusercontent.com/14970832/34902369-1fdcb9ee-f801-11e7-8548-86c3e1822194.png">

I hope you've all resources now. Let me know if you need anything else, if not then we can close this.

**Comment by ranjithrajv** [comment]
@barrosgeraldo Loved these designs. Thanks a lot.
When it is a one-liner to decide, "Aadhaar is dystopian and dangerous" is more appropriate compared to "Aadhaar isn't progress!" please replace these statements.

**Comment by tanzeelkhan** [comment]
Text size of mozilla.org in 2nd and 3rd design looks bigger than the logo. Minimizing the size would make it look better I think.

**Comment by barrosgeraldo** [comment]
Thank you everyone for feedback, adjustments has been made and available on repository. Good luck with the Aadhaar Campaign.


<img width="842" alt="poster1 2x" src="https://user-images.githubusercontent.com/14970832/34908113-d2dc3d38-f871-11e7-9e6a-396bcce3a0a5.png">
<img width="843" alt="poster2 2x" src="https://user-images.githubusercontent.com/14970832/34908114-d38c194c-f871-11e7-98dc-b550ddea93cf.png">
<img width="603" alt="sticker 2x" src="https://user-images.githubusercontent.com/14970832/34908109-c7191444-f871-11e7-84a2-9f9bd43ec373.png">
<img width="2151" alt="t-shirt 2x" src="https://user-images.githubusercontent.com/14970832/34908110-c8359e24-f871-11e7-8128-424829cd8b2b.png">

**Comment by shashikanth171** [comment]
Thanks everyone, for the support.

This is the link to tweet about the today's event. 
https://twitter.com/shashikanth171/status/95255097567117312

**Comment by shashikanth171** [comment]
@barrosgeraldo, Please reopen the issue. Have included "Profile Picture Frame" to the needed designs list.

**Comment by pransh15** [comment]
![aadhar_frame](https://user-images.githubusercontent.com/18158596/34984226-35936b2a-fad6-11e7-9e36-9832c593b2ce.png)
How about this?

**Comment by shashikanth171** [comment]
@pransh15 Thanks for the design. I think mozilla is not easily identifiable and the rotation of line "Aadhaar isn't progress" is decreasing readability of it.

**Comment by pransh15** [comment]
![aadhar_frame1](https://user-images.githubusercontent.com/18158596/34988027-430f6e36-fae3-11e7-8e45-ff58a07ef80d.png)
How about now?

**Comment by barrosgeraldo** [comment]
I love this one! Go ahead! Add the source file (svg, pdf, ai, etc). :)

**Comment by pransh15** [comment]
Sure, following are the links for the files:

* __PSD:__ https://drive.google.com/file/d/1E_NHupMzJihpPJK8VVCAvNly85-DMBeP/view?usp=sharing
* __AI:__ https://drive.google.com/file/d/1ELljPcaU23WR9n4oJqprpUCCx4caC_e-/view?usp=sharing
* __PDF:__ https://drive.google.com/file/d/1nXpIlCzPaOU2M3xuTHZD2Kr3nHhcMxZ5/view?usp=sharing
* __PNG:__ https://drive.google.com/file/d/1vJOaQdc32iN3GQFZRkNAGE3H6Q3--cNi/view?usp=sharing

**Comment by barrosgeraldo** [comment]
@shashikanth171, can you check if you need more one thing?

**Comment by ranjithrajv** [comment]
@pransh15 aspect ratio of Mozilla seems distorted, please check.
I think placing Mozilla logo horizontal looks better over vertical on top-right.

**Comment by pransh15** [comment]
![aadhar_frame1a](https://user-images.githubusercontent.com/18158596/35054578-e2c83b34-fbd2-11e7-8a0c-bb017b9c7268.png)

It was fine, I checked. :)
Horizontal Mozilla logo, how about this?

**Comment by pransh15** [comment]
![aadhar_frame1a_eg](https://user-images.githubusercontent.com/18158596/35054880-bb2d29a8-fbd3-11e7-8ee8-ebf174c2987a.jpg)
An example.

**Comment by ranjithrajv** [comment]
@pransh15 Looks good! we can go with this if @barrosgeraldo is okay with it.

**Comment by barrosgeraldo** [comment]
Great, closing.

**Comment by tanzeelkhan** [comment]
It's Aadhaar I guess and you could try resizing the logo to 50% of its current size. That'll look better. :)
