### ISSUE TITLE
Mozilla l10n updated T-Shirt design with new Firefox logos

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#188]
@guerrojeff asked me to refresh the Firefox l10n T-Shirt designs with the new Firefox logo after last year's issue: https://github.com/mozilla/OpenDesign/issues/98

So here we go:

![image](https://user-images.githubusercontent.com/5436686/34791305-e3defc12-f644-11e7-91c5-1dc4175aa036.png)
![image](https://user-images.githubusercontent.com/5436686/34791346-fcc480c6-f644-11e7-89a6-128b34ecdfc5.png)

**Comment by barrosgeraldo** [comment]
Hey, add it to repository so everyone can produce it locally. Thanks.

**Comment by elioqoshi** [comment]
@barrosgeraldo this is still going through l10n review ;)

**Comment by gueroJeff** [comment]
These look so cool! I imagine they're not the transparents, correct? 

On the first one there's a stray 'x' that's a different color and outside of a box. Otherwise, they look nice to me :-) Could you send this to l10n-drivers@mozilla.org to invite the rest of the team to comment here please?

**Comment by elioqoshi** [comment]
>On the first one there's a stray 'x' that's a different color and outside of a box.

Ah sorry, that's a screenshot and part of the Illustrator UI. Not part of the design. I noticed it and thought it would be interesting if anyone notices it. You did, so bonus points!

>I imagine they're not the transparents, correct?

It's fully transparent, as you can see here:

![image](https://user-images.githubusercontent.com/5436686/34962600-9f8b5a20-fa44-11e7-896d-1ad55decbe93.png)

However because there are a lot of colors going on, I'd suggest not using any color from the illustrations as a background color due to low contrast. Light and Dark grayscale shades should work best

Will send the email yep

**Comment by flodolo** [comment]
Would it be possible to smooth out this part of the logo?

![schermata 2018-01-16 alle 07 39 02](https://user-images.githubusercontent.com/3644868/34975077-6490a3b6-fa90-11e7-885c-c94bfabc19d3.png)

**Comment by elioqoshi** [comment]
@flodolo the 3 small squares? Sure, maybe that detail is not needed

**Comment by Delphine** [comment]
This looks great! (and I agree with the comment for those 3 small squares).
Nice job Elio :D

**Comment by flodolo** [comment]
> @flodolo the 3 small squares? Sure, maybe that detail is not needed

Yes. Either remove it, or add one more square

![34791346-fcc480c6-f644-11e7-89a6-128b34ecdfc5](https://user-images.githubusercontent.com/3644868/35030342-e6d4b2b2-fb5e-11e7-828c-d7fbff61ecc2.png)

**Comment by elioqoshi** [comment]
Solid! Apart that any other comments?

**Comment by AnXh3L0** [comment]
The source files are now uploaded at the repo, [here](https://github.com/mozilla/OpenDesign/tree/master/2018/Graphics/Firefox_-_Nightly_l10n_2018)

**Comment by elioqoshi** [comment]
Thanks! Looking forward to see them in t-shirt form! Closing this.
