### ISSUE TITLE
Cheat sheet for Rust language resources

### ISSUE THREAD

**Issue by vyaspranjal33** [mozilla/OpenDesign#191]
## Goal: 
[design Flyer ]

## Info: 
[Will be used by evengelists , Tech speakers who are in to rust /it can be distributed among students , resources can be found at  https://github.com/rust-community/resources/blob/gh-pages/resources-business-card.odt?raw=true]

## Style Information: 
[https://github.com/mozilla/OpenDesign/blob/master/2017/Graphics/WebExtensions_Cheatsheets/Sheet-01.jpg]

## Deadline: 
[end of march 2018]

## Tag: 
[Design Needed]

**Comment by itsJagrati** [comment]
![resources to rust](https://user-images.githubusercontent.com/31163205/37878210-f2581a94-3082-11e8-8ba6-a58dd65c0906.jpg)

Will that work?

**Comment by vyaspranjal33** [comment]
no it won't work @itsJagrati  btw its nice for sharing on social platforms

**Comment by vyaspranjal33** [comment]
@itsJagrati in case you're looking for reference please check style information above

**Comment by DivuMarcus** [comment]
Here's The one I made
![flayer](https://user-images.githubusercontent.com/36792228/37878501-f455294a-3087-11e8-93d6-0480dc84a4ee.png)

**Comment by DivuMarcus** [comment]
Here's the one I made
![flyer](https://user-images.githubusercontent.com/36792228/37878551-8582e006-3088-11e8-8fe0-7cb98b37887c.png)

**Comment by DivuMarcus** [comment]
Version2 with some text adjustments
![flyer1](https://user-images.githubusercontent.com/36792228/37878611-80b8e790-3089-11e8-96c3-54b135e80803.png)

**Comment by vyaspranjal33** [comment]
looks good @divumarcus

**Comment by DivuMarcus** [comment]
Version 3 With font Sans 
![flyer2](https://user-images.githubusercontent.com/36792228/37878906-90277544-308d-11e8-9b7b-df06e0db6032.png)

**Comment by DivuMarcus** [comment]
improvements for better readability
![flyer3](https://user-images.githubusercontent.com/36792228/37878981-719010b8-308e-11e8-9121-a089496bc440.png)

**Comment by kindavishal** [comment]
Hi @vyaspranjal33! Thanks for the issue, we can re-use there flyers in future! Good job @DivuMarcus and @itsJagrati 
Closing this.
