### ISSUE TITLE
Logo for Rust India

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/OpenDesign#192]
## Goal: 
Logo Rust India community

## Info: 
It will be used for all documentation and community activities by Rust India.
http://github.com/rustindia

## Style Information: 
Similar to the colour combination of National Flag of India.

## Deadline: 
By end of March 2018.

## Tag: 
[Design Needed]

**Comment by cg-cnu** [comment]
Hey @ranjithrajv I have few ideas I am exploring. Will do an update soon! Thanks!

**Comment by cg-cnu** [comment]
Any guidelines for logo in the lines of https://mozilla.ninja/expression ? Let me know if there are any resources!

**Comment by ranjithrajv** [comment]
@cg-cnu https://mozilla.ninja/expression is just for Mozilla logo, nothing to do with Rust logo.

**Comment by ranjithrajv** [comment]
![brazil-flag](https://user-images.githubusercontent.com/3455008/36462141-9dee44ec-16e7-11e8-9bf7-2867b1786b89.jpg)

Rust Brazil logo adopted its colour style inspired by Brazil's national flag. Looking something on similar lines for Rust India with a colour style closer to Indian national flag.

![photo_2018-02-05_22-03-23](https://user-images.githubusercontent.com/3455008/36462142-9e292882-16e7-11e8-8866-4f6f9c01b099.jpg)

**Comment by JoelVinayKumar** [comment]
![rust india logo](https://user-images.githubusercontent.com/16177724/36616563-35298b2c-190a-11e8-8c9e-9645af5f4219.png)

**Comment by pransh15** [comment]
![rust_in_1](https://user-images.githubusercontent.com/18158596/36847573-c4397eb6-1d84-11e8-947f-13e76cf9b4ea.jpg)

A little something I made. \o/

**Comment by praphulpa** [comment]
![rust_logo](https://user-images.githubusercontent.com/36994495/36906092-0c0a14a4-1e5b-11e8-81c8-15253077b2b6.jpg)

**Comment by kumarsatish23** [comment]
![bg_header](https://user-images.githubusercontent.com/34617630/36948660-3be489c0-2004-11e8-843b-5dd28970fef0.png)

**Comment by kumarsatish23** [comment]
![28537028_1175812112553458_547971237_n](https://user-images.githubusercontent.com/34617630/36948663-4bd03cf8-2004-11e8-84cd-2ddaf34d525f.jpg)

**Comment by kumarsatish23** [comment]
![28754986_1035559849930104_1896356376_o](https://user-images.githubusercontent.com/34617630/36948677-7122d100-2004-11e8-8d4a-e76f3ac31380.jpg)

**Comment by kumarsatish23** [comment]
![28695063_1035297749956314_1601275431_o](https://user-images.githubusercontent.com/34617630/36948692-a664f0a0-2004-11e8-94cd-239f1db0196e.jpg)

**Comment by kumarsatish23** [comment]
![28694301_1035592016593554_989399832_o](https://user-images.githubusercontent.com/34617630/36949194-07fac186-200b-11e8-98ed-dad0ea0c6658.jpg)

**Comment by haxzie** [comment]
![rustlogo](https://user-images.githubusercontent.com/18684321/37050991-5a837c2c-219b-11e8-944c-8a0ac9612201.png)

**Comment by creativcoder** [comment]
![display_rust](https://user-images.githubusercontent.com/5155745/37336730-44810bd2-26d8-11e8-8f41-833dbf3d76ff.jpg)

Hi, here's my take on RustIndia logo ! Let me know your thoughts :)

**Comment by pransh15** [comment]
@creativcoder, @haxzie, @kumarsatish23, @JoelVinayKumar, @praphulpa Your submissions are lovely. :+1:

**Comment by barrosgeraldo** [comment]
@ranjithrajv let us know which one you chose and if everything here is enough, so we can close this.

**Comment by harshzalavadiya** [comment]
![mozilla](https://user-images.githubusercontent.com/5774849/38320144-63e0733e-3851-11e8-9d98-f4be00a5ca0b.png)

just an simple version 😄

**Comment by JoelVinayKumar** [comment]
Nice @harshzalavadiya

**Comment by kindavishal** [comment]
Drop a check here! @ranjithrajv, the submissions here look great! Which one do you choose?
And we can close this if no more inputs are required

**Comment by kindavishal** [comment]
Ping @ranjithrajv

**Comment by pransh15** [comment]
I think they've started using one of these on their social channels.
![image](https://user-images.githubusercontent.com/18158596/58896958-cc686480-8714-11e9-893f-2dbc6789fa1e.png)

**Comment by kindavishal** [comment]
Well then I think we can close this issue.
