### ISSUE TITLE
Logo for Rust Hacks

### ISSUE THREAD

**Issue by shahbaz17** [mozilla/OpenDesign#193]
## Goal: 
Logo for Rust Hacks Community

## Info: 
It will be used for all documentation, community activities, and Website of Rust Hacks Community. https://github.com/rusthacks

## Style Information: 
Rust Logo with wrench and tools in the background

## Deadline: 
March 2018

## Tag: 
[Design Needed]

**Comment by pransh15** [comment]
![rusthacks](https://user-images.githubusercontent.com/18158596/36900925-3352246c-1e4b-11e8-80d3-dcb9be934cc1.jpg)

This is how I've envisioned it. I think we need a change in the key, suggestions?

**Comment by rowdymehul** [comment]
Hi @pransh15, really like the quote, we can phrase it with only "Key to unlock Rust". This sounds sort and simple. Regarding design part, I think @barrosgeraldo & @shahbaz17 can give more suggestions here. Suggestions or ideas from others are also welcome. 

Thanks. :)

**Comment by barrosgeraldo** [comment]
@pransh15, it looks good, but too big for a logo.

**Comment by rowdymehul** [comment]
+1 @barrosgeraldo, the key theme I really liked. Still looking for more ideas and suggestions.

**Comment by pransh15** [comment]
@barrosgeraldo, thank you! Well, I kinda have the same feeling, that's why I want to change the key.

@rowdymehul, thank you! "Key to unlock rust" it is.
I'll check for a key which fits your needs and revert!

**Comment by barrosgeraldo** [comment]
@pransh15, but preserve this complete art too, it is very good to use in an art in banners for example.

**Comment by pransh15** [comment]
@barrosgeraldo, sure. I definitely will! :)

**Comment by shahbaz17** [comment]
@pransh15 How about few gears where Rust Logo itself can become one of the gear.

**Comment by pransh15** [comment]
@shahbaz17 can be done.

**Comment by pransh15** [comment]
![rust_in_2](https://user-images.githubusercontent.com/18158596/36935603-cb652658-1f1f-11e8-9274-da0504835d31.jpg)

a smaller key, with an updated phrase.

**Comment by pransh15** [comment]
![rust_in_2](https://user-images.githubusercontent.com/18158596/36935630-115d4064-1f20-11e8-8fe7-aa15e1df3fac.jpg)

a smaller key, with an updated phrase.

**Comment by pransh15** [comment]
![rusthacks_1](https://user-images.githubusercontent.com/18158596/37092892-799ff782-2233-11e8-9858-3f3dccf91971.jpg)
![rusthacks_gear](https://user-images.githubusercontent.com/18158596/37092895-7a0003f2-2233-11e8-97b1-a308152c4096.jpg)

New ones. How are these?

**Comment by rowdymehul** [comment]
The key design looks great with the quote. 👍  Can we other color options for key or background?

**Comment by pransh15** [comment]
![rusthacks_1_bw](https://user-images.githubusercontent.com/18158596/37114179-9fc5ef54-226d-11e8-9aaa-b8466dbf7094.jpg)
![rusthacks_1_gb](https://user-images.githubusercontent.com/18158596/37114180-9ffb41a4-226d-11e8-8c57-4f8c46fbf62c.jpg)
![rusthacks_1_gv](https://user-images.githubusercontent.com/18158596/37114181-a03003ee-226d-11e8-89f0-d455db10ed60.jpg)
![rusthacks_1_sb](https://user-images.githubusercontent.com/18158596/37114245-c9411156-226d-11e8-8924-c6c36924c988.jpg)


I personally liked black as the BG, and maybe turn the key grey or white, to keep it simple. Let me know what you like best! :dancer:

**Comment by rowdymehul** [comment]
@pransh15 even I liked the key grey or white, now need to decide which looks better. @barrosgeraldo what're your suggestions here?

**Comment by barrosgeraldo** [comment]
@rowdymehul I love the first and third because it's alive, it has colors, but use black and white for printable.

**Comment by barrosgeraldo** [comment]
Let us know which one you chose and if everything here is enough.

**Comment by pransh15** [comment]
We are through here, please close this issue.
![image](https://user-images.githubusercontent.com/18158596/44984639-2926cb00-af9b-11e8-9236-1ac8f20a43ab.png)

This has been chosen to use on the various channels.

**Comment by kindavishal** [comment]
Thank you everyone for the help :sparkling_heart: 
Closing this!
