### ISSUE TITLE
Designs for 'Digital Security trainings'

### ISSUE THREAD

**Issue by shashikanth171** [mozilla/OpenDesign#194]
## Goal: 
Designs for "Digital Security Training" Workshops Promotion/Campaign 

## Info: 
Designs will be used on Facebook, Twitter, LinkedIn  posts. 
Event Poster will be used in Meetup, Eventbrite.

Workshop Participants are trained in the following areas
1. Online security tools like Tor;
2. Encrypted communications platforms like Signal;
3. Email encryption;
4. Secure password management;
5. Using and implementing HTTPS;
6. Secure Data Storage; and
7. Measures to secure mobile phones from common security threats.

### Event Details:
Name: Digital Security Training
Venue: Lamakaan, Hyderabad
Data and Time: 8th March 3pm to 5:30pm
Organisers: SFLC.IN, Mozilla Hyderabad

## Style Information: 
1. Should emphasize encryption
2.  Location should be emphasized. Decent space for Location and timings of the workshop as these workshops are going to be organised at multiple locations.

This event is organised by SFLC.IN(https://sflc.in/) and Mozilla Hyderabad Community. Find the logo of SFLC.IN [here](https://user-images.githubusercontent.com/25389431/36787494-5b5c155e-1cb0-11e8-9dda-67e69c6528ec.png).

## Deadline: 
March 24th

## Tag: 
Design Needed

**Comment by barrosgeraldo** [comment]
@shashikanth171, please, can you review and feedback this template?
![artboard 1](https://user-images.githubusercontent.com/14970832/37633174-13576630-2bd0-11e8-8e84-be5f74b3f102.png)

**Comment by shashikanth171** [comment]
The design is good! Thanks. This will work.

**Comment by shashikanth171** [comment]
Thanks! @barrosgeraldo
