### ISSUE TITLE
Logo for Mozilla Delhi Open Community

### ISSUE THREAD

**Issue by realslimshanky** [mozilla/OpenDesign#196]
## Goal: 
Looking volunteers to help out in creating [Mozilla Delhi Open Community](https://wiki.mozilla.org/Mozilla_Delhi_Open_Community) logo.

## Info: 
It'll be used for the events and social profiles of Mozilla Delhi Open Community.

## Style Information: 
Any design would work similar to lastest Mozilla Logo/Icon.

## Deadline: 
March 2018

## Tag: 
Design Needed

**Comment by hellozee** [comment]
Here is my try on it, https://imgur.com/a/UHRNJ

**Comment by pransh15** [comment]
Hey, @hellozee!
That is a great logo, but I don't think that Mozilla logo can be of that color. Please refer to https://mozilla.ninja for design guidelines.

**Comment by realslimshanky** [comment]
@hellozee please refer to the link @pransh15 shared. The logo looks awesome, all it needs is to follow the color guidelines.

**Comment by pransh15** [comment]
![mozdelhiopencommunity](https://user-images.githubusercontent.com/18158596/37113392-43463d6c-226b-11e8-97c3-49f75248accd.jpg)

Hey, so I had some ideas I wanted to check and implement from the design @hellozee had created. Let me know how you like it? :)

**Comment by pransh15** [comment]
@hellozee, looks good. :D
@realslimshanky, ask the community if you're happy with these logos?

**Comment by realslimshanky** [comment]
@pransh15 sure. We'll put the logos on vote for the maain logo to be used. But we can use either of them in posters I guess wrt size. Let's see what community decide. ❤

**Comment by pransh15** [comment]
![mozdelhiopencommunity3](https://user-images.githubusercontent.com/18158596/37149488-2f984d62-22f4-11e8-8458-164814a4f4ac.jpg)
![mozdelhiopencommunity4](https://user-images.githubusercontent.com/18158596/37149490-2fea833e-22f4-11e8-896c-c5159018e65e.jpg)
![mozdelhiopencommunity5](https://user-images.githubusercontent.com/18158596/37149491-30177b78-22f4-11e8-8e96-2b81a7297323.jpg)
![mozdelhiopencommunity6](https://user-images.githubusercontent.com/18158596/37149492-304f8f40-22f4-11e8-9765-23cd8b0fa194.jpg)

So, I liked the color Elio used. That's why the color change.
Also, I used India Gate to make the logo more simple.

**Comment by realslimshanky** [comment]
Adding one more suggestion by Elio.
![image](https://user-images.githubusercontent.com/10004530/37151030-f6738b86-22f9-11e8-8df8-1c860db2c9f1.png)

**Comment by realslimshanky** [comment]
Sending this image out to the group for the vote. Thanks a lot, @elioqoshi, @pransh15, and @hellozee. :relaxed:  
![1](https://user-images.githubusercontent.com/10004530/37151184-7117599e-22fa-11e8-9c0d-fee2a6414efe.png)

**Comment by realslimshanky** [comment]
Updating poll!
![img_20180309_154053](https://user-images.githubusercontent.com/10004530/37202604-e39b9290-2382-11e8-88ea-de87425d1a38.jpg)

**Comment by imshubhamsingh** [comment]
@realslimshanky I've just tweeked the logo which are currently in the poll.
![mozilla delhi](https://user-images.githubusercontent.com/17807743/37235511-2b259f6e-2425-11e8-8ac0-f7a5065c91ed.png)

**Comment by realslimshanky** [comment]
Thanks @ishubhamsingh for your contribution. We'll add this to the wiki and reopen this issue in case of redesign :)
