### ISSUE TITLE
Design a Open Source Birthday Party Invitation for Mozilla

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/OpenDesign#197]
## Goal: 
Mozilla's 20th Birthday is coming up on March 31st. We're looking for someone to design a "20th birthday party invitation" that Mozillians can use to invite their friends and families to celebrate with them. 

## Info: 
The invitations will be emailed and shared on discourse with Mozillians all over the world and promoted on all of our channels! 

## Style Information: 
I'm imagining bright colors, balloons, and candles but totally trust in your creative vision!

## Deadline: 
March 16th - email will go out on March 19th

**Comment by barrosgeraldo** [comment]
Hi @LucyeoH,

Thanks for request design resources, the deadline is too closer but with some resources from MozFest past year I've created this template, we can add more text you want to align better to the campaign strategy. Let me know what you think and then we can refine this one:

<img width="640" alt="artboard 1 2x" src="https://user-images.githubusercontent.com/14970832/37265047-a6e4be80-258f-11e8-8a20-01a120bc35fe.png">

**Comment by LucyeoH** [comment]
@barrosgeraldo this looks great!! I love the design. 

I have a few suggested changes to the copy: 

You're invited! 
Come celebrate Mozilla's 20th Birthday with us!

"Join us on March 31st, as we celebrate 20 years of the open web with Mozillians all around the world! #MozillaTurns20"

**Comment by barrosgeraldo** [comment]
@LucyeoH, thanks, here we go:
![mozilla 20th birthday party invitation 4x](https://user-images.githubusercontent.com/14970832/37312049-4549477e-2628-11e8-94af-dab03843852b.png)

**Comment by LucyeoH** [comment]
@barrosgeraldo It's BEAUTIFUL!!! Thank you thank you!!

**Comment by barrosgeraldo** [comment]
You're welcome, you can [download .png and .pdf source files here](https://github.com/mozilla/OpenDesign/tree/master/2018/Graphics/20th_Birthday_Party_Invitation_Mozilla). Closing.
