### ISSUE TITLE
INTERN Sticker Design

### ISSUE THREAD

**Issue by lauracrick** [mozilla/OpenDesign#198]
## Goal: 
Create a collection of diversity focused stickers for the incoming intern class

## Info: 
These stickers will be distributed to the incoming 2018 interns to set the tone for the summer.  

## Style Information: 
The University Team would love some whimsical/creative/quirky/vintage looking stickers that are diversity focused. We are open to any design of foxes or Mozilla related ideas. We do not need the logo on the sticker, just the artwork :) Ideally we are looking a series of stickers that we can distribute in a sticker sheet. 

## Deadline: 
April 20th, 2018

## Tag: 
Design Needed , Stickers Needed

**Comment by weivicky** [comment]
Hey Laura! I have a couple of questions regarding the requirements. 
1. What format should I save the stickers in? 
2. If I create multiple, how should I submit them (one big file or individual files)?
Thanks for answering my questions!

**Comment by lauracrick** [comment]
Hi Vicky! 

Please submit in jpeg form and please submit individual files. Thanks so much for participating!! 

Best,
Laura

**Comment by weivicky** [comment]
Thanks for answering! Sounds good! 

# Here the diversity ones! 
Unfortunately, I don't know what the previous years' fox stickers look like (not living at home right now and never got to see them), so I created my own foxes!
![rainbow tail](https://user-images.githubusercontent.com/10877399/37257566-bcdb97de-2541-11e8-8ee2-f1feb41a649f.jpg)
![heart shaped earth](https://user-images.githubusercontent.com/10877399/37258244-45812190-254b-11e8-9f13-44c19e3b8b49.jpg)
![friends](https://user-images.githubusercontent.com/10877399/37258084-a1e83ef8-2548-11e8-9fe8-ea254952121f.jpg)
![rainbow balloons](https://user-images.githubusercontent.com/10877399/37258078-97c10c8e-2548-11e8-8035-75c98cba240f.jpg)
![rainbow flag](https://user-images.githubusercontent.com/10877399/37258079-97d2a84a-2548-11e8-859f-521615555ae7.jpg)
![diversity](https://user-images.githubusercontent.com/10877399/37258369-48d951b2-254d-11e8-9a43-760edaeee6e1.jpg)
![kissy face](https://user-images.githubusercontent.com/10877399/37258306-1eddef54-254c-11e8-83e7-4fb2fe40071a.jpg)
![female fox](https://user-images.githubusercontent.com/10877399/37258307-1eee45c0-254c-11e8-943f-ebfdc74757db.jpg)
![github inspired](https://user-images.githubusercontent.com/10877399/37257611-4ef7994c-2542-11e8-878c-47d58503f95d.jpg)
![in love](https://user-images.githubusercontent.com/10877399/37257612-4f07e874-2542-11e8-9fb5-df03c969e77c.jpg)
![rainbow glasses](https://user-images.githubusercontent.com/10877399/37257613-4f185e16-2542-11e8-90af-9f5c2823ac9e.jpg)
![paws](https://user-images.githubusercontent.com/10877399/37257615-4f4d7376-2542-11e8-998f-e21d6cbb9c56.jpg)
![rainbow m](https://user-images.githubusercontent.com/10877399/37257616-4f9a2ebe-2542-11e8-9608-dcc4f9a62df2.jpg)
![rainbow mozilla logo](https://user-images.githubusercontent.com/10877399/37257631-8b191914-2542-11e8-861d-f4bf44950e80.jpg)

# Here are some random ones!
They are not diversity related though!

![normal glasses](https://user-images.githubusercontent.com/10877399/37257989-444215d6-2547-11e8-95d5-cd0fb000810a.jpg)
![mozilla intern 2018](https://user-images.githubusercontent.com/10877399/37257990-4454abe2-2547-11e8-883a-d47daef2bad1.jpg)
![nightly](https://user-images.githubusercontent.com/10877399/37257991-4464c928-2547-11e8-80ae-02a3ba5e4f45.jpg)

**Comment by lauracrick** [comment]
These are amazing!!!

**Comment by barrosgeraldo** [comment]
@weivicky, I love these foxy design, do you've the source files? (.ai, .svg, .pdf)

**Comment by weivicky** [comment]
Hey @barrosgeraldo ! Thank you so much for the compliment! I couldn't upload my ai file directly so I uploaded it to my google drive. You can access it here: https://drive.google.com/file/d/1nVQN6dd4RT_hFKnjRuvjLXhlCluWr6Fi/view?usp=sharing

**Comment by barrosgeraldo** [comment]
@weivicky thank you so much! :tada:

**Comment by AlexisDeschamps** [comment]
Hi, I don't have much experience with this, but I tried doing something:
![sticker](https://user-images.githubusercontent.com/12681350/37767604-144cac94-2da1-11e8-9566-512f08eac96c.jpg)

**Comment by Ryuno-Ki** [comment]
https://github.com/mozilla/OpenDesign/issues/198#issuecomment-372148688 awwww!

Can somebody create a Telegram Sticker pack/upload them to Slack?

**Comment by mrachamallu** [comment]
i've never done this before, but tried my best!
![untitled_artwork](https://user-images.githubusercontent.com/19869159/38000221-6b08aefa-31db-11e8-90b9-92172f12a330.jpeg)
![fox1](https://user-images.githubusercontent.com/19869159/38000237-793ba5cc-31db-11e8-8d99-ee225f2b0617.jpeg)
![fox2](https://user-images.githubusercontent.com/19869159/38000243-7fc26156-31db-11e8-8392-c6b2bedf8ed5.jpeg)
![fox3](https://user-images.githubusercontent.com/19869159/38000253-8879f048-31db-11e8-85d9-a0ba33947ad5.jpeg)
![fox4](https://user-images.githubusercontent.com/19869159/38000257-8d8eb7c6-31db-11e8-9623-9f634e35057f.jpeg)
![fox6](https://user-images.githubusercontent.com/19869159/38000258-9019d764-31db-11e8-9350-7de00884538b.jpeg)
![fox5](https://user-images.githubusercontent.com/19869159/38000262-92283ea6-31db-11e8-8c8d-1486298ad0c1.jpeg)

**Comment by jubitaneja** [comment]
![m1](https://user-images.githubusercontent.com/6600596/38151310-e9754d3e-341f-11e8-84d4-6d31dd25af5c.png)
![m2](https://user-images.githubusercontent.com/6600596/38151311-e98b6e5c-341f-11e8-8821-1f617e4f2655.png)
![m3](https://user-images.githubusercontent.com/6600596/38151312-e9a5ed7c-341f-11e8-8a86-afbc6b2c4ccb.png)
![m4](https://user-images.githubusercontent.com/6600596/38151313-e9bc1afc-341f-11e8-81bc-e515e27f40d2.png)
![m5](https://user-images.githubusercontent.com/6600596/38151314-e9cfd650-341f-11e8-9173-fd8b806a6114.png)
![m6](https://user-images.githubusercontent.com/6600596/38151315-e9e8638c-341f-11e8-815f-aa5a6659ce50.png)
![m7](https://user-images.githubusercontent.com/6600596/38151316-ea021d40-341f-11e8-8b27-616a13ca739b.png)
![m8](https://user-images.githubusercontent.com/6600596/38151317-ea276e7e-341f-11e8-9f16-019c82d2c00c.png)
![m9](https://user-images.githubusercontent.com/6600596/38151318-ea3b16ea-341f-11e8-993b-a45a0c911475.png)
![m10](https://user-images.githubusercontent.com/6600596/38151319-ea5f2170-341f-11e8-91f6-7240487effff.png)
![m11](https://user-images.githubusercontent.com/6600596/38151320-ea7fdf14-341f-11e8-9c18-a138045bf56b.png)
![m12](https://user-images.githubusercontent.com/6600596/38151321-eaa73988-341f-11e8-8869-eb4cbec0f540.png)
![m13](https://user-images.githubusercontent.com/6600596/38151322-eabbdc26-341f-11e8-94e8-8990256eb9fb.png)
![m14](https://user-images.githubusercontent.com/6600596/38151323-eae06910-341f-11e8-8c03-36e72bc940e6.png)

**Comment by jubitaneja** [comment]
Thanks for introducing this fun event. :) I did this for the first time and enjoyed so much.

**Comment by sblatz** [comment]
This is my first time ever creating digital art, so go easy on me, and hope you guys enjoy!

![firefox_lgbt_icon](https://user-images.githubusercontent.com/4400286/38473402-88aa2d4a-3b5d-11e8-94d6-235529f70534.jpg)
![normal_firefox_alone](https://user-images.githubusercontent.com/4400286/38473391-7914b15c-3b5d-11e8-89ce-216ce3f47a75.png)
![normal_firefox_child_mom](https://user-images.githubusercontent.com/4400286/38473392-7b14997c-3b5d-11e8-9f94-88471f861d5f.png)
![normal_firefox_with_night_baby](https://user-images.githubusercontent.com/4400286/38473393-7c614f78-3b5d-11e8-8dfc-343cfffd3594.png)
![nightly_firefox_child_mom](https://user-images.githubusercontent.com/4400286/38473394-7fe4f8f2-3b5d-11e8-9d2a-ac9ab08ffd44.png)
![nightly_firefox_alone](https://user-images.githubusercontent.com/4400286/38473395-815f7694-3b5d-11e8-86e6-8b677c5fcb71.png)

**Comment by carolinecullen** [comment]
Similar to everyone else who has posted previously, I have never done any graphic design before but had a lot of fun! 

![faceversion2](https://user-images.githubusercontent.com/22187606/39022140-ffbfa34a-43e8-11e8-987f-c5c8b30735fd.png)
![rainbow](https://user-images.githubusercontent.com/22187606/39022152-09438238-43e9-11e8-96d9-67e7c7d9c630.png)
![gender](https://user-images.githubusercontent.com/22187606/39022159-0ff34b54-43e9-11e8-9ff9-571fa0aa27a5.png)

**Comment by barrosgeraldo** [comment]
Hi @kaustubhadhav, I like your designs, and we can use for community-stuffs, can you share with us the vector files?

**Comment by SofieC295** [comment]
Hello all! Here's a couple of designs I wanted to contribute. Shout out to my friend John for helping me with these! 
<img width="401" alt="mozilla-foxes" src="https://user-images.githubusercontent.com/25485414/39080580-5ff5842a-44ff-11e8-8a6d-1ddd0251b733.png">
<img width="221" alt="fox-heart" src="https://user-images.githubusercontent.com/25485414/39080581-617157c0-44ff-11e8-89d4-9a6fc2bcf6fc.png">

**Comment by kindavishal** [comment]
Thanks @kaustubhadhav nice designs, they look great!

**Comment by kindavishal** [comment]
Are we done here guys?
@lauracrick I think we have enough submissions here! Anymore needed?

**Comment by likeanushkaa** [comment]
Is this issue still open?

**Comment by kindavishal** [comment]
Hey @anushja :wave: 
Since we didn't hear back from the author, we shall be closing the issue. However, if you have ideas in mind that you want to share, you can still do so :D

**Comment by likeanushkaa** [comment]
Thank you for your response! Actually I was looking for some UI/UX issues
to work on. But I saw some Graphic Design problems only. Plus, I felt some
issues should be closed, hence pointed them out😊

Anushka Jain
19411009
GPT, 2nd Year
