### ISSUE TITLE
Poster for Community Meetup on Data Protection and Privacy

### ISSUE THREAD

**Issue by bhavabhuthi** [mozilla/OpenDesign#199]
### Goal: 
A Poster for Community Meetup on Data Protection and Privacy happening in Hyderabad on March 10, 2018.

### Info: 
TItle: Community Meetup on Data Protection and Privacy 
Venue: Room 205, Himalaya block, IIIT Hyderabad.
Time: 03:00 PM to 06:00 PM IST
https://reps.mozilla.org/e/community-meeting-on-data-protection-and-privacy/

### Style Information: 
Should follow the Mozilla design guidelines

### Deadline: 
March 10th, 09:00AM IST

### Tag: 
[Design Needed, Poster Needed]

**Comment by barrosgeraldo** [comment]
@bhavabhuthi, please add a suitable deadline, at least 20 days, or close this if the event is over and you no longer need this one.
