### ISSUE TITLE
Design template for Mozilla Delhi Webinars

### ISSUE THREAD

**Issue by imshubhamsingh** [mozilla/OpenDesign#201]
## Goal: 
A poster for [Mozilla Delhi Open Community](https://wiki.mozilla.org/India/Delhi) for their second webinar.
## Info: 
I've created this poster for webinar
![mozilla delhi open community 2nd webinar](https://user-images.githubusercontent.com/17807743/37540507-3cfb3c28-297d-11e8-87b2-b07ebcf4a010.png)

Please give feedback here or on [telegram](https://t.me/opendesign) as it can help improve the design.

## Deadline: 
give asap

## Tag: 
[Feedback needed, Communities]

**Comment by imshubhamsingh** [comment]
Source of the poster 
[Mozilla Webinar #2 psd and ai.zip](https://github.com/mozilla/OpenDesign/files/1820754/Mozilla.Webinar.2.psd.and.ai.zip)

**Comment by imshubhamsingh** [comment]
Updated design for the poster 
![photo_2018-03-17_08-44-04](https://user-images.githubusercontent.com/17807743/37551101-61e264ca-29bf-11e8-9230-86cbb246488a.jpg)

**Comment by shashikanth171** [comment]
![mozilla webinar 2 svg-9](https://user-images.githubusercontent.com/25389431/37552038-02ed49d0-29d3-11e8-9c80-d705fa20b9c7.png)

Source file below,
[Mozilla Webinar2_shashikanth171.svg.zip](https://github.com/mozilla/OpenDesign/files/1821313/Mozilla.Webinar2_shashikanth171.svg.zip)

**Comment by DivuMarcus** [comment]
![webinar 2](https://user-images.githubusercontent.com/36792228/37552066-8aeb881a-29d3-11e8-882b-8282b378910c.png)

**Comment by realslimshanky** [comment]
Final image by @imshubhamsingh 
![1](https://user-images.githubusercontent.com/10004530/37552190-2c135aea-29d6-11e8-86b3-42edb3389697.png)

**Comment by DivuMarcus** [comment]
![webinar 2 0](https://user-images.githubusercontent.com/36792228/37552288-079fa91e-29d8-11e8-8629-12cc198e4fd0.png)

**Comment by DivuMarcus** [comment]
updated poster by me
![webinar 2 0](https://user-images.githubusercontent.com/36792228/37552291-1de0e166-29d8-11e8-8c06-7042da0cfda7.png)

**Comment by DivuMarcus** [comment]
With the date and time as well :)
![web2 0](https://user-images.githubusercontent.com/36792228/37552366-84f99e50-29d9-11e8-8440-2ad087776e63.png)
