### ISSUE TITLE
 Design tempalate for Mozconnect with Django girls event

### ISSUE THREAD

**Issue by vyaspranjal33** [mozilla/OpenDesign#202]
## Goal: 
[a poster for mozconnect event]

## Info: 
it will be used to promote event on social media platforms

## Style Information: 
poster size is 1920 X 1080 px

## Deadline: 
[17 march 2018]

## Tag: 
[Design Needed]

**Comment by DivuMarcus** [comment]
Here is the one :)
![djangogirlsbvn 3](https://user-images.githubusercontent.com/36792228/37557511-98b7d428-2a2b-11e8-94c0-e3bd220c579f.png)

**Comment by DivuMarcus** [comment]
Have A look on this ;)
![djangogirlsbvn 3](https://user-images.githubusercontent.com/36792228/37557517-b9626c74-2a2b-11e8-8ffb-6e6cff1e624d.png)

**Comment by DivuMarcus** [comment]
Two More of them to give a more professional Look along with your pre-requisites.
![1](https://user-images.githubusercontent.com/36792228/37557921-d61fdbca-2a31-11e8-935c-ef59d5dc8136.png)
![2](https://user-images.githubusercontent.com/36792228/37557922-d690db40-2a31-11e8-91e2-39fff0f9d586.png)

**Comment by DivuMarcus** [comment]
Updated poster with the new django girls logo
![1](https://user-images.githubusercontent.com/36792228/37558005-484cef20-2a33-11e8-99ab-bf7a0485ec10.png)
![2](https://user-images.githubusercontent.com/36792228/37558006-489d975e-2a33-11e8-920e-86db9fa44500.png)

**Comment by DivuMarcus** [comment]
with Mozilla Gujrat Logo
![1](https://user-images.githubusercontent.com/36792228/37558567-cd830ff0-2a3b-11e8-8c1f-4025fe682303.png)
![2](https://user-images.githubusercontent.com/36792228/37558568-cdc563e6-2a3b-11e8-9530-a04ebd83bdb5.png)

**Comment by DivuMarcus** [comment]
Final One with the date and address
![1](https://user-images.githubusercontent.com/36792228/37558576-e6217308-2a3b-11e8-8d4d-cc52a99b02b8.png)
![2](https://user-images.githubusercontent.com/36792228/37558577-e67d5d80-2a3b-11e8-9247-397031d56846.png)

**Comment by barrosgeraldo** [comment]
@vyaspranjal33 Could you describe a paragraph about the event? What do people do at this event? What is the purpose of the event? Why is Mozilla in the event? Please, fill "Style information", what is the size of the poster and where will it be published? What is the real deadline? Please take time to fill in all the information.

**Comment by vyaspranjal33** [comment]
the event is about workshop on website development using django framework the event is organized by @djangogirls local chapter mozilla joined event because of diversity & inclusion AS they ve maximum seats reserved for womens/girls or first priorities are given to girls/women @barrosgeraldo you can see more details about event here : [-]https://djangogirls.org/bhavnagar/ & Mozilla's presence : https://reps.mozilla.org/e/mozconnect-with-django-girls-bhavnagar/

**Comment by vyaspranjal33** [comment]
thanks for design @divumarcus
