### ISSUE TITLE
Question: roll-up with quantum design

### ISSUE THREAD

**Issue by Thegennok** [mozilla/OpenDesign#206]
Hi all,

## Goal: 
I am from the french community and we don't have any up to date roll-up banner for ours booths.
So, my goal here is to make one or two new banners. And if possible, thoses designs should be able to be used by every other moz community. I am not asking you to do it, I think I can do the job, but I would like advice and input from you.

## Info: 
We put theses banners behind our booth, so people can reconize us from far away.

## Style Information: 
I already done a fews differents tests and I would like feedback from the OpenDesign community, which is waaaay more stylish than me.

First banner is Mozilla oriented: 
=>1-1 a blue one. The gradiant goes from #0060df to #0095ff, with 75% opacity.
![moz_blue](https://user-images.githubusercontent.com/7412626/38776833-ce5cfd00-409d-11e8-994a-c02776bf9148.png)

=>1-2 a white one
![moz_white](https://user-images.githubusercontent.com/7412626/38776835-ce925306-409d-11e8-9a86-e8ac90111283.png)

=>1-3 same as =>1-1, with a tail (this one, I am not sure^^). The tail is the one used on the front page of mozilla.org.
![moz_tail_ver](https://user-images.githubusercontent.com/7412626/38776834-ce77be24-409d-11e8-8963-bb3b9ce29b30.png)

And a Firefox banner:
=>2-1 Police is "Open Sans", wasn't able to find if a special one should be used and it's the one used on https://www.mozilla.org/firefox/.
![moz_ff](https://user-images.githubusercontent.com/7412626/38776849-fbaf501e-409d-11e8-9e07-1860d0d4ccf4.png)

## Deadline: 
No deadline here, only question/discussion :slightly_smiling_face: 

## Tag: 
[Question]

**Comment by nclm** [comment]
Hi!

For the “Firefox” wordmark under the logo, you can’t just re-write it with another typeface. You can download the proper one here: https://design.firefox.com/photon/visuals/product-identity-assets.html You can also pick one of these colours for the background: https://design.firefox.com/photon/visuals/color.html

The colours for the Mozilla one could come from here as well: https://mozilla.design/visualelements/

And I’d say if there’s a Mozilla and a Firefox one side by side sometimes, they should not be both blue but two colours that compliments each other :)

**Comment by pransh15** [comment]
@kindavishal you can add the roll-ups you created for your community. they might find it helpful.

**Comment by kindavishal** [comment]
![Quantum_RollUpBanner_2880x6912](https://user-images.githubusercontent.com/35860774/55847624-a769d200-5b67-11e9-91a1-5f8a217d67f9.png)

**Comment by kindavishal** [comment]
Hope this will help

**Comment by kindavishal** [comment]
Is there anymore requirement here? @Thegennok

**Comment by kindavishal** [comment]
Giving a gentle bump on the back, can we close this issue @Thegennok ?

**Comment by Thegennok** [comment]
Hi @kindavishal ! Thanks for the roll-up, they are very cool!

Closing, thanks
