### ISSUE TITLE
Design for Test Engineering Stickers

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/OpenDesign#208]
## Goal: 
Logo Design for Firefox Test Engineering

## Info: 
Stickers for All Hands!

## Style Information: 
A couple of sketches...
![image](https://user-images.githubusercontent.com/18633586/39538047-a5e94104-4df8-11e8-95c9-233354ff1433.png)

The top is based on the Firefox logo, with a magnifying glass finding a bug

The bottom is based on the Firefox Developer logo, modified into a teardrop shape, labelled "Dev tears"

## Deadline: 
Hopefully by the end of May, so that we can have them ordered in time for All Hands SF, June 11-June 16

## Tag: 
[Design Needed]

**Comment by kindavishal** [comment]
Hi, thanks for the issue @kimberlythegeek!
Is this still needed? Looks like we missed the deadline!

**Comment by kimberlythegeek** [comment]
I got in touch with a designer at Mozilla who came up with an awesome design for us :) Thanks @kindavishal

**Comment by kindavishal** [comment]
Great! Can you share it here as well? I'd love to see the output :sparkles:
