### ISSUE TITLE
Product Integrity All Hands Shirt

### ISSUE THREAD

**Issue by pauljt** [mozilla/OpenDesign#209]
## Goal: 
The Product Integrity (PI) team would like a t-shirt design for all hands

## Info: 
We'd like a T-shirt design for the PI team for all hands. So we need a design or logo or both for said t-shirt.  (we could also just use the standard Mozilla slab logo for team, with a custom design)

## Style Information: 
The core theme that unites the Pi team is "Quality" so something that conveys that theme, but also something great the PI team it is proud to wear. FYI that PI is made up of 4 teams:  
   - Release Management 
   - Quality Assurance (QA)
   - Test Engineering
   - Security 

Some Ideas discussed so far: 
 - Something detective related (play on PI == Private Investigator), and most of our work is related to bug hunting
 - PI could also be π symbol

## Deadline: 
We need this in the next could weeks so we can get shirts printed in time for all hands.

## Tag: 
[Design Needed]

**Comment by scottr97** [comment]
I'd like to help with this. I'll drop an initial design idea in very soon.

**Comment by scottr97** [comment]
![pimagnify](https://user-images.githubusercontent.com/28555167/40360550-e80d536a-5e09-11e8-95d0-765b34787482.png)
![mozillapi](https://user-images.githubusercontent.com/28555167/40360551-e83f464a-5e09-11e8-88d5-bb2035c4981e.jpg)

@pauljt 
Here's two ideas I came up with. Let me know what you think.

**Comment by pauljt** [comment]
Hey I love that second one!! Ill take it back to the team for feedback! Thanks!

**Comment by scottr97** [comment]
Fantastic, let me know what they say :)

**Comment by elioqoshi** [comment]
@pauljt Unfortunately those designs are out of brand guidelines.

**Comment by Dlimk** [comment]
![pi design 01](https://user-images.githubusercontent.com/11227639/40452890-af178ee2-5ee3-11e8-8065-617a714df260.jpg)

**Comment by pauljt** [comment]
@elioqoshi thanks for the helpful constructive feedback!

**Comment by pauljt** [comment]
@scottr97 I think what @elioqoshi  was trying to say was that if we want a shirt that has the moz:lla logo on it, then we need to adhere our branding guidelines, which are here https://mozilla.design/

From a quick skim, I think that means no corruption of the Mozilla workmark (specifically see https://mozilla.design/mlogo/) , so it might be that "moz:πa" isn't allowed (as awesome, as I think it is :) I'd suggest we either try to find design that uses the π is a different way that doesn't overlay the logo.  But I dunno, that kinda seems a bit boring and maybe defeats the purpose of the design. Maybe we look for a design that doesn't use the Mozilla logo at all, given the brand restrictions.

**Comment by pauljt** [comment]
That said, we are probably cutting it a bit fine to get this in time for all hands, so might have to aim for something in the future. Still keen for a design though. Suggestion from our director "how about the Firefox with a Sherlock Holmes hat? " Just an idea.

**Comment by kindavishal** [comment]
Thanks for the issue @pauljt! Is this resolved or needs any other additional inputs?
