### ISSUE TITLE
Logo Needed for Kinto

### ISSUE THREAD

**Issue by leplatrem** [mozilla/OpenDesign#21]
- **Goal:** design a vectorial logo
- **Info:** Mozilla product / branding
- **Style Information:** _See below_
- **Deadline:** Ideally before our Kinto workweek on 15th february
- **Tag:** Design Needed

[Kinto is an open source project](http://kinto.readthedocs.org/en/latest/) developed by Mozilla Services, to store data in a «personal cloud». It is also used by Firefox to synchronize internal data like security rules.

The project [is taking](https://news.ycombinator.com/item?id=10733164) [off](https://news.ycombinator.com/item?id=10994736), and we believe it now deserve a neat logo!
Our current one is an image taken from the Internetz, with no proper credits and very little identity (we're so bad at this).

![capture d ecran de 2016-01-27 11-49-19](https://cloud.githubusercontent.com/assets/546692/12611253/0a913258-c4ec-11e5-9968-252b15f3c55d.png)

«Kinto-Un» is the japanese name of the flying nimbus of Sangoku in Dragon ball.

![th](https://cloud.githubusercontent.com/assets/546692/12611225/e9450dc2-c4eb-11e5-84b2-17f772157df1.jpeg)

We like the idea of a small yellow cloud. The Sangoku flying nimbus matches well with Kinto: it is personal, small, sets up quickly and is very fast. Plus the image of a cloud is explicit on first sight (like Owncloud or Cozy.io logos).

If you could help us, we wouldn't be more happy! :heart:

A thousand thanks for your initiative! :clap:

**Comment by jenpez** [comment]
First proposal, let me know what you think
![kinto](https://cloud.githubusercontent.com/assets/16767717/12625899/d73a10ba-c503-11e5-83df-b2d38ba4468f.jpg)

**Comment by leplatrem** [comment]
Wao thanks @jenpez for proposing something at the speed of light!

Globally we like it! The lightning on the cloud is great.
It should probably be oriented to the right though (as @my-le suggested right=forward=future). What do you think?

We're not convinced by the text though. Not sure the cloud should be used as the dot on «i». Could you please try to put it on a side or below, maybe with another font?

What about an idea like that for example? (you tell us, the font is still bad and going through the hole might be debatable...):
![capture d ecran de 2016-01-28 10-20-51](https://cloud.githubusercontent.com/assets/546692/12640200/0c0e94a0-c5a9-11e5-9fd9-7c3e311a8f38.png)



Thank you again for your collaboration! :+1: :+1:

**Comment by elioqoshi** [comment]
@leplatrem thanks for opening this issue! @jenpez we use Fira Sans / Meta for logos at Mozilla, so it would be good to stick with that for consistency reasons :)

I will fire up some proposals of mine next week too!

**Comment by n1k0** [comment]
my humble take (don't laugh, first hour spent using Inkscape ever)

![](http://i.imgur.com/TQ94tSf.png)

**Comment by flukeout** [comment]
Here are a couple of ideas!

![image](https://cloud.githubusercontent.com/assets/25212/12659622/a275722c-c5c4-11e5-85a3-82ad78f7d17c.png)

**Comment by nlhkabu** [comment]
@flukeout I love the top design!  What about if you tried it in blue?

**Comment by yra99ary** [comment]
I am a big fan of Dragon ball.
It's a first proposal, hope you like it : )
 
![kinto_logo](https://cloud.githubusercontent.com/assets/8791195/12681138/0da2ca8a-c6e8-11e5-9b24-5e2db5b4abad.png)

**Comment by leplatrem** [comment]
Thanks all for your propositions! This is amazing (and a bit embarassing too.) to be able to pick and opinionate :)

*Disclaimer: I have absolutely no experience in giving my opinion about logos :)*

@flukeout I like the top one too. Maybe use more orange-ish color for the shadows to avoid confusion with a flatulence :) flashy colors like @jenpez's were great!  
I think the cloud should also be slightly bigger, but that may be a matter of taste. It's mainly to keep the proportions of the tail in the original flying nimbus. 

@yra99ary the colors are great and shape are great! It would be better to have left to right orientation. And maybe avoid the effect of «stack».

**Comment by yra99ary** [comment]
I change orientation and update some detail.

![kinto_logo2](https://cloud.githubusercontent.com/assets/8791195/12684319/425c0096-c6f9-11e5-8241-f270d81b7250.png)

**Comment by jenpez** [comment]
Revisions to my original design. Liked the idea of putting it to the right to represent the future. Also tried the cloud on the bottom.
![kinto](https://cloud.githubusercontent.com/assets/16767717/12693692/94268410-c6df-11e5-968c-6156b28ea3d9.jpg)

**Comment by n1k0** [comment]
Heavily inspired by @jenpez proposition

![](http://i.imgur.com/jpblcBv.png)

I'm too bad at inkscape so I couldn't intertwine the trails properly but you get the idea

**Comment by AntoineCezar** [comment]
Draft Idea. If any real designer want to iterate on it…
![kinto-draft](http://antoine.cezar.fr/kinto-draft.png)

**Comment by leplatrem** [comment]
When I saw [this page of «logo dust»](http://www.logodust.com/?ope) I felt inspired... but the output looks more or less like a car :)

![g4831](https://cloud.githubusercontent.com/assets/546692/12714048/b63b59e6-c8d2-11e5-8a68-f3b0d87a678a.png)

**Comment by AntoineCezar** [comment]
Wrong anime ^_^
![slump](http://vignette2.wikia.nocookie.net/drslump/images/3/34/1983YellowCar.jpg/revision/latest?cb=20120712120608)

**Comment by AymericFaivre** [comment]
A quick one, hope it could help.
![kinto_01](https://cloud.githubusercontent.com/assets/2395629/12901434/ff8da862-cebb-11e5-82c7-9f9b2626b77d.jpg)

**Comment by Natim** [comment]
I received new ideas by email if this can help:

![clx-3180_20160209_11405101](https://cloud.githubusercontent.com/assets/229453/12914032/6e12f1dc-cf22-11e5-8007-95cd40c4be5d.jpg)

![image](https://cloud.githubusercontent.com/assets/229453/12914042/7a12ffe0-cf22-11e5-81b9-55e88c914ad3.png)

**Comment by Natim** [comment]
Ideas that came with the email:

 - Italic might be use to give the speed and time saving in application development
 - Letter can be linked together to give the idea of connection through the cloud
 - The Kinto text could stay on top of the cloud (pure heart) it doesn't go through

**Comment by leplatrem** [comment]
Thanks @AymericFaivre for your proposition! I really like the colors! I'm not convinced by the shape though (the low trail and the two «half-spheres»), I think it could look a bit more lively/vivacious! 

@Natim I like this one (although it's very far from what was proposed here)
![capture d ecran de 2016-02-09 12-38-53](https://cloud.githubusercontent.com/assets/546692/12915231/190173d2-cf2a-11e5-9396-52cb833accf5.png)

Thanks all again!
(*please help us choose :)*)

**Comment by elioqoshi** [comment]
@AymericFaivre please share source files so we can remix ;)

**Comment by almet** [comment]
Hi, and thanks to everyone involved so far in this foray to find the best logo for Kinto!

I've asked @AymericFaivre to do some changes on his proposition, but he seems very busy (and I don't blame him for that!), but I think we should try to move this forward.

@jenpez proposal seems a good step in the right direction, so maybe we can iterate on this, and mix it with the proposal @AymericFaivre did?

@elioqoshi do you have any hints on how to go forward here? Thanks!

**Comment by elioqoshi** [comment]
I've lost quite track of the issue, let me know what you need and I will help out :)

**Comment by Natim** [comment]
So basically the aim is to find a logo for Kinto.

Kinto is a storage solution for web and mobile application that need to sync and share user data.
Kinto is a service that you can deploy but you can also pay a company to host it for you.

We are trying to find a nice logo that tells that it is a database for the web for anyone to use.

**Comment by Ryuno-Ki** [comment]
What I'm missing on the clouds above: The tail looks disharmonious. As it weren't be part of the cloud. Kinto-un hit that better. It took the momentum, whereas the proposed ones were straight most the time (except the [one](https://github.com/mozilla/Community-Design/issues/21#issuecomment-176433140) by @flukeout and the [one](https://github.com/mozilla/Community-Design/issues/21#issuecomment-176851930) by @yra99ary).

The lower most of these looks like an UFO:
![kinto proposal](https://cloud.githubusercontent.com/assets/25212/12659741/335c3302-c5c5-11e5-99cf-9b229a5d4743.png)

**Comment by Natim** [comment]
It make me think of a washing powder brand or electronic cigarette brand logo for the two first and of a steam cleaner brand for the latter.

The more I think about it the more I like @AymericFaivre proposal, there is the idea of a wave, the idea of a cloud.

@AymericFaivre could you please send us the vectorial file?

**Comment by Natim** [comment]
In @AymericFaivre proposition there is also the idea of steam after a fast Tex Avery character when through so we also have the idea of speed.

**Comment by AymericFaivre** [comment]
Hello,
Sorry, i had a lot of things to do -_-"

@Natim Yes, the "steam" after the cloud give a sensation of speed. I could accentuate this sensation if it's needed. I use transparent shape for the open side of the project, and the classic Mozilla font to stay in the whole branding.

I'm not toaly satsfied, so i can make modifications, just tell me and i will take the time.

Idealy, it could be fun to do the others things around this project. Like finish the design of website.

Thanks (And sorry my english is a bit rusty but i’m working on it)

**Comment by almet** [comment]
> I'm not totaly satisfied, so i can make modifications, just tell me and i will take the time.

Please, go ahead and do the proposal, we completely trust you on this!

**Comment by almet** [comment]
Any chance you can provide us with the sources so we can play with it?

**Comment by AymericFaivre** [comment]
Ok, i will do this !

> Any chance you can provide us with the sources so we can play with it? 

No sorry, my experience proved that is a really bad idea ;) (but of course I will give you the files when it's finish)

**Comment by Natim** [comment]
> I will give you the files when it's finish

Are things ever finished? What we usually do is to iterate on versions.

I already used the current logo once in a presentation and I wish we could have a vectorial version so that we can adapt it on different support (tee-shirt, presentation, website design and stuff)

> I'm not totaly satisfied, so i can make modifications, just tell me and i will take the time.

Please take the time to give us a first version you are satisfied about so that we can start using it.

> Idealy, it could be fun to do the others things around this project. Like finish the design of the website.

That would be great. Do not hesitate to join [#kinto](https://kiwiirc.com/client/irc.freenode.net/?#kinto) we speak french and english there.

**Comment by edangor** [comment]
Hi, I love @AymericFaivre 's one because it has the Mozilla feel, but in general I feel like we need more flat design.

**Comment by elioqoshi** [comment]
@AymericFaivre please provide us with the files so we can proceed with this. It has been already quite some time since this was opened. Thank you!

**Comment by AymericFaivre** [comment]
Hi, sorry, i've lot of client work.
I make few changes, mostly to make more harmonious shapes and give more movement.
3 versions : with grey dash, with orange dash, and without.
Don't hesitate to provide feedback :)
![kinto_04_01](https://cloud.githubusercontent.com/assets/2395629/15491297/92381fe0-215e-11e6-866a-9f4aea73b9de.jpg)
![kinto_04_02](https://cloud.githubusercontent.com/assets/2395629/15491298/93289ca4-215e-11e6-939f-51a409b43754.jpg)
![kinto_04_03](https://cloud.githubusercontent.com/assets/2395629/15491301/969fccd6-215e-11e6-9c0c-b97ee9f7d46a.jpg)

**Comment by leplatrem** [comment]
Awesome! \o/ I really like the second one!

**Comment by n1k0** [comment]
Yeah, the second version is winner to me as well. Thanks a bunch, @AymericFaivre!

**Comment by Natim** [comment]
Yes it is really good. However I don't understand the meaning of the brackets in the second and third ones. Is it for the share or self-host? Does it represent people or linked-computers? Or annotations like in the previous [Cliquet logo](http://kinto.readthedocs.io/en/stable/_images/logo.svg)?

**Comment by tarekziade** [comment]
nit: We should see how a low-res version would look like - e.g. when printing shirts we won't have all those color nuances and details

**Comment by tarekziade** [comment]
sinon, s/jaune/orange ?  je trouve que la forme et la couleur combinées ne changent rien au logo initial.

J'ai demandé à ma gamine de 5 ans ce que c'était, elle a dit "C'est du pipi ou du caca?"  😨

**Comment by yofiesetiawan** [comment]
I really like @AymericFaivre version, it just the colors remind me of CloudFlare...

**Comment by almet** [comment]
Thank you @AymericFaivre ! I really like the idea of having the wave inside the cloud, it's like a small tsunami :-)

I personally like the colors :) Maybe you can of propose other colors ? Howver, the main idea of this iteration was to work on the shape of the cloud, and I think we're in good shape ;)

I like the grey dashes, but like @Natim I miss some meaning for it. Maybe we could add some arrows there (but it might go against the newly added movement).

**Comment by AymericFaivre** [comment]
Thanks for your feedbacks :)

> I don't think the last logo is very different from the original logo, with a similar color/shape. My 5 yo daughter reaction when I showed it to her "It's poo or pee?

Yes, it's just improvement of the last i did, cause it's seems to be a good track, according to the comments. I don't see the  poo/pee shape. Maybe if you can be more explicit i can adjust this but it seems others people don't see this.

> I really like the idea of having the wave inside the cloud, it's like a small tsunami :-)
Yes, it's the idea :)

> We should see how a low-res version would look like - e.g. when printing shirts we won't have all those color nuances and details

I will make size declinations, and if necessary, make adjustements for the lowest size. For printing shirt and other stuffs, i will make a print-safe version when the colors will be fine. It shouldn't be a problem, Firefox logo had a lot of nuances and details to and work fine on print material :)

> However I don't understand the meaning of the brackets in the second and third ones. Is it for the share or self-host? Does it represent people or linked-computers?

It's a bit all of this. Link, share, sync... It bring a technic side and movement. I can try with arrows instead of circles.

> I personally like the colors :) Maybe you can of propose other colors ?

> I really like @AymericFaivre version, it just the colors remind me of CloudFlare...

I like theses colors too, but i can try with others if you want. Just give me some clues. Do you want to keep the yellow/orange (wich are the colors of Mozilla and Kinto-un and i thougt it's a good point), or others? I just want to keep vivid colors and the feeling of transparency.
I don't really see the similitudes with cloud flare (the orange and is really dark and not vivid) Is it [this one](http://www.thewebprograms.com/wp-content/uploads/2012/11/ClientHandler.ashx_.gif)?

Thanks again :)

**Comment by elioqoshi** [comment]
Looks good @AymericFaivre ! I'm a fan of the first one, the dashes are quite unneccessary I believe

**Comment by almet** [comment]
Hi,

I believe the next action here is to try a few variations. I believe we all agree that the logo is great in general ;)

Could you do some changes where:

- You use arrows instead of circles.
- You try to use different colors. Some other variations of yellow ? (after all it's a kinto-un!)

Thanks

**Comment by AymericFaivre** [comment]
Hey,
Yes i will do the change in the middle of the week :)
Thanks !

**Comment by AymericFaivre** [comment]
Hi !
I make few changes  :
- The first has a double arrow, and the others circle and arrow. Tell me what it make more meaning for you.
- The numbered pictures are déclinsons of colors. Yellow isn't an easy color. My preference goes to the first because of the vivids colors, but the others make sense to, so you have the
![kinto_05-13](https://cloud.githubusercontent.com/assets/2395629/15793420/59844174-29d3-11e6-92ae-30516a91100b.png)
![kinto_05-14](https://cloud.githubusercontent.com/assets/2395629/15793424/59864ce4-29d3-11e6-9da0-6038cb7e34f3.png)
![kinto_05-15](https://cloud.githubusercontent.com/assets/2395629/15793423/59862e76-29d3-11e6-8e41-6a781459e11a.png)
![kinto_05-16](https://cloud.githubusercontent.com/assets/2395629/15793419/5984027c-29d3-11e6-8fbc-c38433ba3750.png)
![kinto_05-17](https://cloud.githubusercontent.com/assets/2395629/15793422/5985c936-29d3-11e6-9da8-f662250b8ca7.png)
![kinto_05-18](https://cloud.githubusercontent.com/assets/2395629/15793421/59845d58-29d3-11e6-9bbe-20510789357f.png)
![kinto_05-19](https://cloud.githubusercontent.com/assets/2395629/15793425/5a06b262-29d3-11e6-861f-aaa51dedeafc.png)






 choice :D

Let me know if you have feedback !
Thanks and good weekend !

**Comment by almet** [comment]
Thanks! We have a community meeting tomorrow where we will discuss the logo, and we'll get back to you just after it :-)

**Comment by AymericFaivre** [comment]
Perfect, thanks :)

**Comment by almet** [comment]
Hi!

After today's discussion, we decided to go for the solution listed here as n°3 for the colors, but without the arrows and small additions you did.

So, I believe we're almost there: could you do these last changes and send us the sources / export ? Thanks again :+1:

**Comment by AymericFaivre** [comment]
Hello,

Perfect :)
So if i understand, it's this one : 
![kinto_05-final](https://cloud.githubusercontent.com/assets/2395629/15879593/27adc63a-2d15-11e6-88c9-52d4879bfca4.jpg)

I'm on vacation (and away from my workstation) until 20th june, but if you need it, i can send you a png with alpha.
I will send you the final vector sources as soon as i'm back to work.

Thanks !

**Comment by Natim** [comment]
Yes that's it :) Thanks a lot @AymericFaivre The PNG with alpha would be great :+1:

**Comment by AymericFaivre** [comment]
Hop !
See you soon :)
![kinto_05_final](https://cloud.githubusercontent.com/assets/2395629/15888102/22226dac-2d55-11e6-8c95-e8145b3c3e8d.png)

**Comment by almet** [comment]
We can start with this for now! Thanks

**Comment by Natim** [comment]
![capture](https://cloud.githubusercontent.com/assets/229453/15888534/8c61b094-2d67-11e6-957f-8cb187f16995.png)

I guess @leplatrem can now close this issue :)

**Comment by leplatrem** [comment]
Awesome! Huge thanks to all participants!

**Comment by elioqoshi** [comment]
Sorry for being a bit late to the party, I thought I'd chime in with some small details before this is set in stone.

I think the cloud is a bit misaligned with the wordmark.I'd suggest aligning it with the base of Kinto and scale it a little bit down afterwards. If you check it out here, there are way too many lines isolating h the objects:

![kinto](https://cloud.githubusercontent.com/assets/5436686/15989954/37412a0e-3087-11e6-8942-772e095ec9d4.jpg)

I'd suggest something like this:

![kinto](https://cloud.githubusercontent.com/assets/5436686/15989977/eef0f3e6-3087-11e6-9cfe-39a8f7215a57.jpg)

Apart of that, I love the logo! Good job!

**Comment by AymericFaivre** [comment]
Hey !
I made some change to align the cloud with the top of the "m" of "mozilla" and the bottom of the "K" of "Kinto". This version is easier to use with and without the baseline.

![kinto_10](https://cloud.githubusercontent.com/assets/2395629/16248965/4441227c-3802-11e6-85cb-830edbf4d217.jpg)

I export the final version in in various format. Where can I upload them?

Thanks !

**Comment by mart3ll** [comment]
Sorry to chime in on this late stage, but we should not be making a logo for this and the wordmark should at this point be made through the Brand team until the new system is complete.

Please see our new guidelines for branding projects, technologies and products at Mozilla:
https://wiki.mozilla.org/Engagement/Brand/Brand_and_Identity_Guide

**Comment by AymericFaivre** [comment]
@mart3ll so, i spent time for nothing? If this is the case, it is very annoying...

**Comment by mart3ll** [comment]
I wouldn't say for nothing - the visual can be used for swag, shirts, and stickers, it just shouldn't be used as the official logo. Lots of opportunity to use it.

The system is put into place so we can strengthen our main brands. We have far too many logos at Mozilla currently (I know, I've designed over 100 of them) and going forward we want the focus to be on our main Mozilla brand and key products.

**Comment by tarekziade** [comment]
@mart3ll can we just remove the word "Mozilla" and use the logo as it is as our official logo ?

**Comment by mart3ll** [comment]
Where does this fit into the Mozilla brand architecture within that wiki link? Project, technology or product? If it is not getting full Mozilla product support like Firefox, then it does not get its own logo.

As I said, it can still have visuals associated with it, but more for clothing, stickers, etc.

We can set up a chat to go over the new brand architecture system if you'd like.

**Comment by almet** [comment]
I think there is a misunderstanding here: Kinto is a project that is used at Mozilla but not a Mozilla "owned" project (just like Rust is).

As such, I do not believe these rules apply, and that it actually make more sense to not have the "Mozilla" brand associated with it.

**Comment by mart3ll** [comment]
Aha!

Ok, if it is not an official Mozilla project, technology or product then
removing the Mozilla wordmark should be enough, yes.

It might benefit from using another font for the wordmark itself if it
isn't part of our brand system, but that's not a necessary change.




On Wednesday, 22 June 2016, Alexis Metaireau <notifications@github.com>
wrote:

> I think there is a misunderstanding here: Kinto is a project that is used
> at Mozilla but not a Mozilla "owned" project (just like Rust is).
>
> As such, I do not believe these rules apply, and that it actually make
> more sense to not have the "Mozilla" brand associated with it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/OpenDesign/issues/21#issuecomment-227772105>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGaShGcVHi26XDjHm9n9H_qNP1mnv3wWks5qOU4jgaJpZM4HNThG>
> .
>


-- 
*Sean Martell   *
 *Lead Creative, Brand*
*__________________________________________*
*+1-416-545-7724   |   blog.seanmartell.com <http://blog.seanmartell.com>
|   @mart3ll*

**Comment by AymericFaivre** [comment]
Hi !
So, this version, without the mozilla wordmark, should be the one :)
![kinto_11](https://cloud.githubusercontent.com/assets/2395629/16312559/cbcea648-3964-11e6-9b3e-f79afd98d832.jpg)

If it's ok, I send you the files, juste let me know.
Thanks !

**Comment by elioqoshi** [comment]
@AymericFaivre I did some suggestions in my prior comment:
https://github.com/mozilla/OpenDesign/issues/21#issuecomment-225416715

I'd suggest applying these, if you agree :)

**Comment by AymericFaivre** [comment]
@elioqoshi yep, like you suggested I've aligned the cloud with the bottom of kinto, but I let it free on the top, to keep it strong, free and dynamic.

**Comment by AymericFaivre** [comment]
Hello,
I sent the sources files to kinto(@)mozilla.org. Enjoy !
So, I think you can close the issue.

Thanks :)

**Comment by elioqoshi** [comment]
Please also the source files here, we want to work in the open, thanks :)

**Comment by Natim** [comment]
I guess you are talking about this emai: https://mail.mozilla.org/pipermail/kinto/2016-June/000171.html

**Comment by AymericFaivre** [comment]
Yep :)

**Comment by elioqoshi** [comment]
Can you push the files to our repo please?
www.miho-stories.com/labs/Kinto/Kinto_Logo_Livrables.zip

**Comment by Natim** [comment]
@elioqoshi Would you like a PR to OpenDesign?

**Comment by Natim** [comment]
Btw @AymericFaivre if you want to give a revamp shot at http://www.kinto-storage.org/ design you are more than welcome.

**Comment by elioqoshi** [comment]
@Natim yes please, I can merge it

**Comment by Natim** [comment]
@elioqoshi https://github.com/mozilla/OpenDesign/pull/76

**Comment by Natim** [comment]
By the way thanks a lot @AymericFaivre

**Comment by AymericFaivre** [comment]
Thanks to you @Natim 
I will have some free times at the end of july to take a look at kinto storage :)
