### ISSUE TITLE
Logo for "Funda" project 

### ISSUE THREAD

**Issue by omudongo** [mozilla/OpenDesign#210]
## Goal: 
Logo for **Funda** project (_Funda: referring to "learning"_)

## Info: 
Logo to be used for documentation, community activities, Website  and Social media networks -- https://github.com/omudongo/-Rethink-Web-Literacy

## Style Information: 
Something that resembles (openness and collaboration, education tech, open science) -- good example here: https://science.mozilla.org/

## Deadline: 
May 2018

## Tag: 
#Design Needed #Developer Needed #Question #Staff Support Needed

**Comment by npscience** [comment]
A logo was designed at the eLife Sprint. @omudongo - would you like to keep this request open or to close it?

**Comment by omudongo** [comment]
@npscience we can close this, thank you so much!

**Comment by npscience** [comment]
@omudongo I don't have the power to close this issue — please go ahead if you do :)
