### ISSUE TITLE
Mozilla Fox Herder/Wrangler (CM) Design

### ISSUE THREAD

**Issue by emmairwin** [mozilla/OpenDesign#211]
## Goal: 
For All Hands , we would like a design to print-off that represents Mozilla community managers.

## Info: 
This will be used as currency at All Hands (limited edition Community management stickers)

## Style Information: 
Early brainstorming because CM work is often considered 'cat herding' :
* The fox (of course)
 * herding / shepherding a LOT of smaller foxes  (successfully)

Making it cute of course!

## Deadline: 
ASAP 

## Tag: 
[Design Needed]

**Comment by LucyeoH** [comment]
Propose we change this to "fox" wrangler. I think it translates better and avoids any potential misunderstandings :)

**Comment by LucyeoH** [comment]
@elioqoshi would you recommend anyone for this?
