### ISSUE TITLE
Use GitHub labels for deadlines

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/OpenDesign#213]
Hi,

just a thought which came to me right now: What about using Custom GitHub labels for each month?
This way, browsing the open issues would allow to see at a glance, which issues have a near deadline. (Assuming all of them have to be done in less than a year).

What do you think?

**Comment by muhammadridho** [comment]
hhmm ... thats good idea. but how do you label it,  month / or urgent level?

**Comment by pransh15** [comment]
I think we can add labels for [Whenever, 3 months, 2 months, 1 month, 3 Weeks, 2 Weeks, 1 Week, ASAP].

**Comment by elioqoshi** [comment]
Labels are not designed for that honestly. Milestones are designed for deadlines, so if anyone can create a milestone, that would be ideal.

**Comment by pransh15** [comment]
I think we can add the "Create a Milestone" in the Readme, under **Deadline:**

Along with the [link](https://help.github.com/en/articles/creating-and-editing-milestones-for-issues-and-pull-requests).

**Comment by Ryuno-Ki** [comment]
I'd rather use Labels for [Mar 19, Apr 19, May 19] etc.
I couldn't find an indicator, how Milestone would behave if they're overdue.

**Comment by muhammadridho** [comment]
thats include "design review" too ?, if we use milestone @elioqoshi  ?

**Comment by elioqoshi** [comment]
> I'd rather use Labels for [Mar 19, Apr 19, May 19] etc.

Yes, but personal preference shouldn't be an argument here. Any specific reasons why that would be a better approach? You'd have to clutter the whole label space with specific dates which will never be used again and ideally needed to be removed (which also defeats the purpose of labels if deleting them is part of the process).

I just gave this issue a test milestone. You can see that it says "Past due by 1 day"

> thats include "design review" too ?, if we use milestone @elioqoshi ?

Sure

**Comment by Ryuno-Ki** [comment]
> > I'd rather use Labels for [Mar 19, Apr 19, May 19] etc.
> 
> Yes, but personal preference shouldn't be an argument here.

Agree. It was my motivation for this ticket (that is, why I suggested label instead of milestone).

> Any specific reasons why that would be a better approach?

They stand more out in the issue overview:

![milestone-vs-label](https://user-images.githubusercontent.com/3097194/54491923-7547b600-48c2-11e9-80e0-ffae61ed1f3b.png)

> You'd have to clutter the whole label space with specific dates which will never be used again and ideally needed to be removed (which also defeats the purpose of labels if deleting them is part of the process).

What about using a label for the year and another one for the month then?
You can actually [filter for both in an issue search](https://github.com/mozilla/OpenDesign/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ACommunities+label%3A%22Good+First+Task%22).

> > I couldn't find an indicator, how Milestone would behave if they're overdue.
> 
> I just gave this issue a test milestone. You can see that it says "Past due by 1 day"

True, but only [in the milestone detail view](https://github.com/mozilla/OpenDesign/milestone/1).

**Comment by elioqoshi** [comment]
> What about using a label for the year and another one for the month then?

How would that be helpful? There are 30 different possibilities inside a month and some projects need to have a specific one.

> True, but only in the milestone detail view.

No, also in the projects view (which is enabled here).

GitHub simply does not support any due dates and anything closest to it is milestones. Using Labels is very very far fetched and comes up with a bigger set of other problems which I mentioned before.

If you want to use labels for prioritizing things, that can be done. Have a look at how I set up project management at our company:

https://github.com/uracreative/works/labels

**Comment by kindavishal** [comment]
I agree with @elioqoshi here. Creating labels for deadlines isn't very convenient and Milestones can work better than a label for such purposes! Closing this issue.
