### ISSUE TITLE
Graphic design of backdrop

### ISSUE THREAD

**Issue by iamVP7** [mozilla/OpenDesign#215]
## Goal: 
Graphic design of backdrop , octonorm booth of size  9ft w x 8ft h

## Info: 
We  (Mozilla India Community Contributors) are planning to organize a booth at [devconf](https://devconf.info/in/2018) . It is 2 days conference where contributors will be sharing about WASM, Rust, WebVR, WebExtension.

## Style Information: 
[What you want it to look like, link to references, similar things etc.]

## Deadline: 
25th July 2018

## Tag: 
[Design Needed, Developer Needed]

**Comment by iamVP7** [comment]
Changed Deadline to 25th of July after check with devconf india team. Faster is better they mentioned.

**Comment by abhi12ravi** [comment]
Hi all, we need a poster like this - https://ibb.co/hdcTYo

**Comment by tanzeelkhan** [comment]
![devconf-banner](https://user-images.githubusercontent.com/4867861/43244174-697997ca-90c7-11e8-8279-75a8c9bf6aa2.png)
Here you go! :)

**Comment by tanzeelkhan** [comment]
[Printable - devconf banner without website.pdf](https://github.com/mozilla/OpenDesign/files/2230695/Printable.-.devconf.banner.without.website.pdf)
[printable-devconf banner.pdf](https://github.com/mozilla/OpenDesign/files/2230696/printable-devconf.banner.pdf)
![devconf-banner](https://user-images.githubusercontent.com/4867861/43245293-67055b4c-90cb-11e8-950f-f3c2acf51e8e.png)

You may the use pdf files attached for printing purpose.

**Comment by abhi12ravi** [comment]
Thanks a lot, @tanzeelkhan . We appreciate it! 👍

**Comment by iamVP7** [comment]
Thanks a lot @tanzeelkhan  .. closing this bug.
