### ISSUE TITLE
Webcam cover packaging

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/OpenDesign#216]
## Goal: 
Webcam cover packaging. 

## Info: 
Hey Open Design community, the Mozilla Reps program is going to produce webcam cover. However, we need your help to design the packaging otherwise the space will be wasted. 

## Style Information: 
[What you want it to look like, link to references, similar things etc.]
Here is the sample of the packaging from the vendor. The dimention is 4"x 6"
<img width="533" alt="screen shot 2018-07-17 at 18 29 13" src="https://user-images.githubusercontent.com/4922388/42812178-5b3a5264-89ef-11e8-8a5f-ee3ed9ab9191.png">

## Deadline: 
23 of July 2018

## Tag: 
[Design Needed]

**Comment by MichaelKohler** [comment]
@kelimuttu I suppose we want the new Reps logo to be on it?

You can find the new Reps assets here: https://drive.google.com/drive/folders/1M80zSrx640Ve7chhrmwn08RO0s6HnN5n

**Comment by kelimuttu** [comment]
I was about to send the artwork once somebody assign the issue. But that's wonderful! Thanks @MichaelKohler 🥇

**Comment by elioqoshi** [comment]
@kelimuttu can we have more time than 23rd July? Generally 6 days are way too little time for requests.

**Comment by kelimuttu** [comment]
That'll be great if we can have it by 23rd so we can start the production right away. But, I can stretch it for sure. When do you think is the most convenient deadline for you @elioqoshi ?

**Comment by elioqoshi** [comment]
I generally am a fan of getting things right and design requests should be around the same timeline as budget requests :D That is, 2-3 weeks before. I don't think people will be angry if it's a week later, or?

But if anyone can jump in within this week, please feel free to help.

**Comment by kristicunga** [comment]
Hello guys,

This is a draft me and @elioqoshi made for Mozilla Resp webcam. I hope you'll like it :smiley_cat: 

[Reps Mozilla - 730.pdf](https://github.com/mozilla/OpenDesign/files/2241332/Reps.Mozilla.-.730.pdf)

**Comment by kelimuttu** [comment]
Thanks @kristicunga @elioqoshi !! I like the concept. I might gonna add some more text on the back cover. Let me get back to you once I have the copy.

**Comment by kelimuttu** [comment]
Hey both, sorry it takes a while to get the sample packaging. Here is the content. 

Front content: 
![photo_2018-08-09_19-41-26](https://user-images.githubusercontent.com/4922388/44034440-4bd12bc4-9f37-11e8-82dd-e404c4471b95.jpg)

Take charge of your privacy
with this webcam cover

Back content:
![photo_2018-08-09_19-32-53](https://user-images.githubusercontent.com/4922388/44034428-468d6678-9f37-11e8-8694-8bc504ff57b6.jpg)
Mozilla
Champion for a healthy internet

Privacy doesn't mean you have something to hide. It means you have the ability to choose who knows where you go and what you do. At Mozilla, we provide tools and fight for policies that respect people's identity and data accross the internet. 

Keeping your webcam covered is one simple step you can take to improve your privacy and security. 

#InternetHealth

Thank you for all your helps! (:

**Comment by elioqoshi** [comment]
Thanks @kelimuttu 

@kristicunga can we update this?

**Comment by kristicunga** [comment]
Yes, of course @elioqoshi!

**Comment by kelimuttu** [comment]
Hey both @elioqoshi @kristicunga, 

is there any update on this?

**Comment by elioqoshi** [comment]
Finishing today!

**Comment by AnXh3L0** [comment]
Hi @kelimuttu, below you'll find the PDF files ready for print with the additional text.

[Back - CMYK.pdf](https://github.com/mozilla/OpenDesign/files/2311801/Back.-.CMYK.pdf)
[Front - CMYK.pdf](https://github.com/mozilla/OpenDesign/files/2311802/Front.-.CMYK.pdf)

**Comment by pransh15** [comment]
Looks good! 👍

**Comment by kelimuttu** [comment]
Hey @AnXh3L0 Thanks for that! However, I could see there is a subtle white line in between the "healthy internet" part which makes the bottom part to be shifted just very slightly. 
<img width="355" alt="screen shot 2018-08-23 at 12 35 49" src="https://user-images.githubusercontent.com/4922388/44506568-242b6700-a6d1-11e8-971d-638614715ae1.png">

Can you fix those? Thanks in advance!

**Comment by AnXh3L0** [comment]
Hi @kelimuttu, I fixed the white line. You'll find the print file below. 

[Back - CMYK.pdf](https://github.com/mozilla/OpenDesign/files/2314183/Back.-.CMYK.pdf)

**Comment by kelimuttu** [comment]
I think we're cleared to close this issue now. Thanks everyone!! <3

**Comment by elioqoshi** [comment]
@AnXh3L0 Thanks! Can you push this here to the repo?
