### ISSUE TITLE
Emblem for Mozilla's Research TTS (Text to Speech) project 

### ISSUE THREAD

**Issue by erogol** [mozilla/OpenDesign#228]
## Goal: 
An emblem for [TTS](https://github.com/mozilla/TTS) project, which aims to create an open-sourced Text to Speech solution based on Deep Learning. Please visit the link for more information. 

## Info: 
This emblem is going to be used as an unique identifier of the project on any medium and platform. These will include stickers, t-shirts and online banners. 

## Style Information: 
Basically, it is used to synthesize the voice reading the given text. This basic usage might also be used as an inspiration for the emblem. Like set of characters are being converted to a voice signal.

Also, it is better to keep it simple and compact to be space friendly.

## Deadline: 
No deadline

## Tag: 
[Design Needed]

**Comment by kindavishal** [comment]
Hi @erogol!
Thanks for the issue! Will get back with an idea in sometime. Adding the Good First Issue label for more contributions. Feel free to tag me here incase I get caught up!

**Comment by kindavishal** [comment]
Here are some ideas I built from scratch
1.a) ![TTS_1_Text](https://user-images.githubusercontent.com/35860774/56484317-7638bc80-64ec-11e9-9b94-e6e0844024cd.png)
1.b) ![TTS_1_Binary](https://user-images.githubusercontent.com/35860774/56484316-75078f80-64ec-11e9-96d2-640cb8fddcbf.png)
2.a) ![TTS_2_ASCII](https://user-images.githubusercontent.com/35860774/56484320-7933ad00-64ec-11e9-9392-c7e4ea1e0359.png)
2.b) ![TTS_2_Text](https://user-images.githubusercontent.com/35860774/56484322-7a64da00-64ec-11e9-94e3-75327f3ca0f6.png)
2.c) ![TTS_2_binary](https://user-images.githubusercontent.com/35860774/56484321-79cc4380-64ec-11e9-828d-6deeeb0db470.png)
2.d) ![TTS_ASCII](https://user-images.githubusercontent.com/35860774/56484323-7afd7080-64ec-11e9-8d2e-378fef23fc9a.png)
These can be modified as you wish, the text, the color, feel free to provide your feedback about it

**Comment by kartik9756** [comment]
1.a) seems to adequate emblem, as it is showing text to voice conversion. And To add to the feedback, it would be better that Mozilla logo and 'Text to speech' text would be of the same length.

**Comment by muhammadridho** [comment]
2.b) can you simplify, whether the words there can be abbreviated again. i'd think "a short but straightforward word".

**Comment by erogol** [comment]
@kindavishal Thanks for your wok. they all look quite good. We tend to like the option b, but maybe less but the bigger text on the left side. We might also use a slightly darker coloring to make it more clear.

**Comment by kindavishal** [comment]
Thanks for the review @erogol and @muhammadridho!
Can do the changes, I added the text just for reference from mozilla.org, that can be changed as you wish, what text would you like to suggest?
Also, it will be great if you put a reference to what shade you might like, any shade, may add screenshots or link to that, will help me to understand how you might be seeing it in your mind.

**Comment by pransh15** [comment]
@kindavishal shouldn't we be following Mozilla's current design format for all the projects? Like this, I think:

![MozTTS](https://user-images.githubusercontent.com/18158596/56582740-9acc8b80-65f5-11e9-997c-0820f7cbbeca.png)

**Comment by kindavishal** [comment]
> @kindavishal shouldn't we be following Mozilla's current design format for all the projects? Like this, I think:

Well as per mozilla.design,
>Our primary logo (white type in black containing shape) should be used over most backgrounds. For darker backgrounds where the black shape may not be legible please use the one color white logo.

Since we are using white typed in black shape, it should be fine. And the project specific logo is independent of any such background color or shape as far as the guidelines is concerned.

**Comment by kindavishal** [comment]
> 2.b) can you simplify, whether the words there can be abbreviated again. i'd think "a short but straightforward word".

Do you mean to use a shorter phrase or like some short form of the same phrase? Can you make it more clear to me?

**Comment by ruchikabgosain** [comment]
Hello @kindavishal @pransh15 @erogol is this issue still open?

**Comment by kindavishal** [comment]
It is @ruchikabgosain I am actually waiting for the reply to [this](https://github.com/mozilla/OpenDesign/issues/228#issuecomment-485853215) so that I can put in the recommendations.

**Comment by kindavishal** [comment]
Ping @erogol !

**Comment by erogol** [comment]
we can close this given the new circumstances. Thanks, everyone who helped us here.
