### ISSUE TITLE
Mozilla Odisha Logo

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/OpenDesign#229]
## Goal: 
Need logo for Mozilla Odisha

## Style Information: 
Aligns with new Mozilla Design Language http://mozilla.design/

## Deadline: 
December 31, 2018.

## Tag: 
[Design Needed, Question]

**Comment by ankushChatterjee** [comment]
![js-map](https://user-images.githubusercontent.com/7688389/49105677-4b349e80-f2a7-11e8-98c7-211ba151e7b3.png)

**Comment by Manzar8** [comment]
![mozilla odisha logo designed by manzar](https://user-images.githubusercontent.com/23013833/49131683-1b18ea00-f2ff-11e8-9086-10d72faf6d7b.jpg)

**Comment by Manzar8** [comment]
![m](https://user-images.githubusercontent.com/23013833/49341802-9c160f80-f678-11e8-819c-8bf304a5e32f.png)

**Comment by Manzar8** [comment]
![m](https://user-images.githubusercontent.com/23013833/49341829-f1522100-f678-11e8-831d-02eef6219452.png)

**Comment by debasish2256** [comment]
![19b65261-7b8d-4a1a-88b0-d04923ffdbb1](https://user-images.githubusercontent.com/26497826/49426130-9712a680-f7c5-11e8-929d-1a4f8b405138.png)

**Comment by pransh15** [comment]
@Manzar8, @debasish2256 that's some great work you've contributed. I really like it! I think the logo use isn't quite right.

Can you guys please check if your designs comply with the Mozilla Design Language?
You can check it out at [mozilla.design](https://mozilla.design)! 😄

**Comment by debasish2256** [comment]
![color_logo_transparent](https://user-images.githubusercontent.com/26497826/49427065-5f592e00-f7c8-11e8-9580-c8185c5b0289.png)

**Comment by ranjansachin** [comment]
![mozilalogo](https://user-images.githubusercontent.com/45596563/49443482-96443980-f7f2-11e8-8928-17f5d8d473dc.png)

**Comment by ranjansachin** [comment]
![mozlogo](https://user-images.githubusercontent.com/45596563/49445585-410b2680-f7f8-11e8-869f-b3ed1625e8ae.png)

**Comment by manzarhasnain787** [comment]
> @Manzar8, @debasish2256 that's some great work you've contributed. I really like it! I think the logo use isn't quite right.
> 
> Can you guys please check if your designs comply with the Mozilla Design Language?
> You can check it out at [mozilla.design](https://mozilla.design)! 😄
![logo](https://user-images.githubusercontent.com/45493758/50527957-94c81180-0b11-11e9-868c-3c8cb26cd7b5.jpg)


I think it's ok now

**Comment by manzarhasnain787** [comment]
@pransh15 Is it ok now?
 
![logo](https://user-images.githubusercontent.com/45493758/50528006-cf31ae80-0b11-11e9-8961-1639a6607ddb.jpg)

**Comment by ranjithrajv** [comment]
Color palette is already used by Delhi, try another color.

**Comment by manzarhasnain787** [comment]
![logofinal](https://user-images.githubusercontent.com/45493758/50540596-79fda780-0bba-11e9-8a42-6f59b2932106.jpg)

**Comment by manzarhasnain787** [comment]
@ranjithrajv I hope now abobe yellow one will work. As we have to also follow Mozilla Design.
![screenshot 1474](https://user-images.githubusercontent.com/45493758/50540605-cba63200-0bba-11e9-8f6d-5f64032e25db.png)

**Comment by MichaelKohler** [comment]
@ranjithrajv 

> Color palette is already used by Delhi, try another color.

where is that requirement coming from? https://mozilla.design/visualelements/ doesn't list that many colors, and I think Community Logos should comply to those colors. This makes it de facto impossible to have such a requirement.

**Comment by Di-sha** [comment]
![mozilla-01](https://user-images.githubusercontent.com/45895968/50541422-ac63d080-0bcb-11e9-8f1b-2d0bbc98955c.jpg)

**Comment by Di-sha** [comment]
![mozilla1-01](https://user-images.githubusercontent.com/45895968/50541463-6a875a00-0bcc-11e9-96c1-09456ed2a78b.jpg)

**Comment by ramshorst** [comment]
Hello :)
What do you think of this?
Greetings,
Toon

![mozilla odisha](https://user-images.githubusercontent.com/5200239/50787759-9b941880-12b7-11e9-8ef7-4a0c5a2f9737.jpg)

**Comment by kindavishal** [comment]
Is it decided or do we still need help on this?

**Comment by pransh15** [comment]
@ranjithrajv is it done?

**Comment by ranjithrajv** [comment]
Done. The community started using https://github.com/mozilla/OpenDesign/issues/229#issuecomment-450506555

**Comment by pransh15** [comment]
Alright! Closing this issue.
