### ISSUE TITLE
Design needed on Spot Illustrations of Contributor Foxes for Science Lab

### ISSUE THREAD

**Issue by zee-moz** [mozilla/OpenDesign#23]
At MSL we're creating a series of presentations for an upcoming workshop and need some spot illustrations of groups of contributors working openly. I remixed/riffed on the MSL science fox/dapper fox to make some working contributor foxes. The design is quite rough-- needs paws, better outfits, shading, and different/better body positions so the group looks more varied. Here's an example.

![quickfoxblueworkng-01](https://cloud.githubusercontent.com/assets/13855390/12651782/0a8f1de0-c5b6-11e5-9158-5ec9162b5483.png)

If anyone wants to help out and fix some foxes, the [ai files are here.](https://drive.google.com/a/mozilla.com/file/d/0BytjEIvMn7SRd2ljdGk0SE1ZQTA/view?usp=sharing) 

Our workshop is coming up next week, but we will likely use these designs in materials going forward.

Thanks! Zannah

**Comment by elioqoshi** [comment]
Sorry for the lack of communication here @zee-moz !
I will try to delegate this as I currently have no buffer to take this on. By when would you need it?

**Comment by ioana-chiorean** [comment]
@zee-moz was this the workshop from Berlin the last weekend?  How can we use this going further? Any already requested?

**Comment by zee-moz** [comment]
Hey there @ioana-chiorean and @elioqoshi, we used our rough draft foxes in the materials for the Berlin Workshop that happened last weekend. But we'll continue to use foxes in lots of our materials going forward. While there's not an immediate need for them, it would be great to have some new foxes to use when we update our materials in early March. 

We'd also love to have additional illustrations to go along with the foxes-- we started with this laptop because we were doing a presentation about github, but we also have materials about open data, about community building, about creating "pathways" and "roadmaps"-- seems like we could add some graphics there!

**Comment by elioqoshi** [comment]
@yofiesetiawan do you have an illustrator friend who can help on this?

@Raphseck or maybe you?

**Comment by elioqoshi** [comment]
ping @Raphseck

**Comment by Raphseck** [comment]
lets do this! : )))

**Comment by Raphseck** [comment]
Hey guys
Sorry about the late.
What do you think about these sketches?
What type of fox do you prefer?
![sketches_fox_alch](https://cloud.githubusercontent.com/assets/14264676/14165256/671a374a-f6dd-11e5-9b63-1e4e5fd9de62.png)

**Comment by zee-moz** [comment]
Hey there, let me run these by the team and get back to you!
Thanks!
Zannah

**Comment by zee-moz** [comment]
Hey @elioqoshi and @Raphseck-- Sorry for the delayed response-- we had a week-long team meeting last week in Toronto, so I was running around like crazy. Now that I'm back home, I had some time to review this. Thanks for the work on these foxes. I ran them by our team and everyone agrees, they are very very cute-- so much personality! We will use them for stickers and for some swag for upcoming events. I really appreciate your help on this.

However, I think some of the info about this task got lost in the thread of comments on this issue-- we'd started off with an illustrator file and a basic fox design (see the original issue) that we needed modified and polished, rather than generating new fox designs. We'll totally use the foxes that @Raphseck made in our swag packs and we love them, but we still need work on the basic fox design MSL generated in house. 

Here are the tasks that are still outstanding for work on existing, draft foxes we created:

- needs paws (none currently)
- better outfits, more polished look
- shading
- different/better body positions so the group looks more varied

We could also use some graphics that show
- a fox following a roadmap, or making a roadmap (ok if this looks like a regular map, and not a project map)
- a fox walking down a pathway of some sort (could be forest? could be...?)
- a community of foxes
- foxes hanging out, coding or working together, drinking coffee (fox community)

Hope this clears things up! Thanks again for all your work, hope someone is willing to take on the revision of the draft foxes!

Sample:
![quickfoxblueworkng-01](https://cloud.githubusercontent.com/assets/13855390/12651782/0a8f1de0-c5b6-11e5-9158-5ec9162b5483.png)

[AI files with several fox versions](https://drive.google.com/a/mozilla.com/file/d/0BytjEIvMn7SRd2ljdGk0SE1ZQTA/view?usp=sharing)

**Comment by MarieSchweiz** [comment]
hei @zee-moz maybe i can help you a little from a brefing perspective. Your Illustration is a very geometrical shaped example. Which means paws is a very difficult request and shadows should be sharp not soft. Otherwise the style gets a little lost. example attached. "polished look" is difficult to understand. Can be everything. better outfits? I admit its a very rough fox. Maybe a brefing could look like

"We need a geometrical styled fox, vector based and resizable, different clothing (a bit more details as the example has), business casual and dress, scene based illustration with a forest or a similar solution to visualize a roadmap. adaptable"

My recommendation is to post your fox on dribbble and ask for rebounds which can be submitted as open source design. Attach a form or something like that. This way you reach more designers and in addition you have a huge variety of styles. Keep in mind your fox indicates hard and simple shapes. Your request just doesn't fit to the example you gave.

![fox_marie_schweiz](https://cloud.githubusercontent.com/assets/1557392/16599615/7d4d1bc8-4303-11e6-8e04-a8474b82a0ac.jpg)

**Comment by Raphseck** [comment]
Hey guys.
Sorry about my big delay.
I had some problems in the last months.

@MarieSchweiz  ! 
LOVE your foxes : )

**Comment by MarieSchweiz** [comment]
thanks @Raphseck maybe you can develop him in the direction requested? Take this one, might look better vectorized? She is already a cutie but i just sketched her.

![sciencefox](https://cloud.githubusercontent.com/assets/1557392/16603543/17081bbe-431d-11e6-92dc-f6f5196f6cc4.jpg)

**Comment by elioqoshi** [comment]
ping @Raphseck

**Comment by Raphseck** [comment]
Hey guys, how are you?
Sorry about the late.
But now I ll try to help more.
Sorry : (
what do you thing about this vector?
<img width="884" alt="screenshot 2016-09-18 11 12 51" src="https://cloud.githubusercontent.com/assets/14264676/18616373/e27efa80-7d90-11e6-99cf-bb4b179663a4.png">
