### ISSUE TITLE
SiliconShire Global Sprint logo

### ISSUE THREAD

**Issue by nohorse** [mozilla/OpenDesign#233]
## Goal: 
we are having a global spring and would like a logo!

## Info: 
we will use this for social media posts and maybe teeshirts for the event.

## Style Information: 
check out the branding at https://siliconshire.org/promote/ and riff on that.  It's under a CC license and fine fro use in our region.  

## Deadline: 
I think the next global sprint is in may, so mid-april would be great

## Tag: 
[Design Needed]

**Comment by pransh15** [comment]
Hello, @nohorse!

I have some trouble understanding what you need. I can see that you have a logo on your website, so do you need a new logo or just t-shirt templates, or both?

**Comment by muhammadridho** [comment]
i'm a agreed with @pransh15 , do you need logo for promote siliconshire global sprint event ?

**Comment by nohorse** [comment]
Something special for global sprint would be amazing!

**Comment by nohorse** [comment]
Please feel free to remix our logo with some Mozilla elements!

**Comment by pransh15** [comment]
@muhammadridho i think we can try something like [this](https://mozilla.design/gallery).

we have the logo, we can simply add a background or make it more interactive like this.

**Comment by muhammadridho** [comment]
ahh i see,

**Comment by nohorse** [comment]
our kickoff event is tomorrow!  https://www.meetup.com/EugeneTech/events/260713803/

**Comment by nohorse** [comment]
how can I get this labeled with #mozsprint

**Comment by kindavishal** [comment]
Hi @nohorse I am guessing this issue is solved, if so, please close the issue.
Thanks :sparkles:
