### ISSUE TITLE
Sokafrica Request: Logo Design - Open Leadership Program Cohort 7

### ISSUE THREAD

**Issue by omudongo** [mozilla/OpenDesign#237]
## Goal: 
Create a logo for Sokafrica project

## Info: 
Logo is used for a project undertaken under the Open Leadership program (cohort 7) here: [https://github.com/msoka86/Sokafrica](https://github.com/msoka86/Sokafrica)

## Style Information: 
Referenced here: [https://github.com/msoka86/Sokafrica/issues/3](https://github.com/msoka86/Sokafrica/issues/3)

## Deadline: 
30 April, 2019

## Tag: 
#33 #101

**Comment by agnelnieves** [comment]
Hello, I've come up with a quick concept. Let me know what you think!

![image](https://user-images.githubusercontent.com/5799157/55509109-60d91c80-5629-11e9-8b51-902c52a4c6d6.png)

**Comment by omudongo** [comment]
Hi @agnelnieves, I like it except the below which I'd suggest you remove. Also, kindly incorporate the 3 colors: (Black, Dark Red, and Mustard Yellow).

We would like to use this logo for (Facebook/Twitter profile and header) with the following specifications:

Twitter: Dimensions for profile images - 400x400 pixels / Dimensions for header images are 1500x500 pixels

Facebook: Profile photo size is 360 x 360 pixels / Facebook cover photo is 828 x 465 pixels

**Comment by msoka86** [comment]
First, thank you for your contribution @agnelnieves, it is much appreciated! Like what @omudongo posted above, we are looking for a combination of warm colors touches (mustard yellow and scarlet, a shade close to deep cadmium red) on a mostly black logo. I liked what you did with the red (we just need the change the shade) but I would also like to add the yellow mustard somewhere if possible.

**Comment by Chandan-Baba** [comment]
Hello @omudongo, @msoka86, Here is one that I made. Let me know if it fits on your requirement.        ![SOKAFRIKA](https://user-images.githubusercontent.com/47283424/55675228-1a134d00-58dd-11e9-81a6-26e0f7840f6d.png)

**Comment by msoka86** [comment]
@Chandan-Baba thank you for your contribution, it is a nice logo but sadly I don't feel Africa in it (plus we decided to keep it simple without the words below). I am attaching a crude version of my previously drawn logo so you can get a feel of it:
![image](https://user-images.githubusercontent.com/46974328/55676063-eb897800-58c4-11e9-9ebb-29364f998ac8.png)
If nobody has a clear idea of what I wrote above, making this neater and in the format asked by @omudongo  is perfectly fine by me.

**Comment by Chandan-Baba** [comment]
Hi @msoka, please clear few points : 
1) You don't want Afrika logo in the image (Yes/Let it as it is)
2) Do you want the same color coding as you did in attached image?

**Comment by Chandan-Baba** [comment]
Preview 1)
![Sokafrika_1](https://user-images.githubusercontent.com/47283424/55679312-dcd3ad00-5926-11e9-9b93-769138fede61.png)

**Comment by msoka86** [comment]
> Hi @msoka, please clear few points :
> 
> 1. You don't want Afrika logo in the image (Yes/Let it as it is)
> 2. Do you want the same color coding as you did in attached image?

Hello @Chandan-Baba and thank you for all your efforts! To answer your questions, I thought that the logo I draw was a bit heavy so I wanted to know if someone could come up with a simpler design with the same feel, but I think it is not possible. Although I like the last logo you designed, it is still not what I am looking for. Would you be able to come up with a professional rendition of my logo? Is it possible with all the details in it?

**Comment by omudongo** [comment]
> @Chandan-Baba thank you for your contribution, it is a nice logo but sadly I don't feel Africa in it (plus we decided to keep it simple without the words below). I am attaching a crude version of my previously drawn logo so you can get a feel of it:
> ![image](https://user-images.githubusercontent.com/46974328/55676063-eb897800-58c4-11e9-9ebb-29364f998ac8.png)
> If nobody has a clear idea of what I wrote above, making this neater and in the format asked by @omudongo is perfectly fine by me.

@Chandan-Baba & @agnelnieves we really appreciate you for your time and help so far. I was wondering if it's possible that you could get an exact copy of the redesigned logo maybe? We should be winding up the Mozilla Open Leadership program soon and mentees should be pitching their project ideas in a few weeks. 

I would really appreciate if you could kindly help us get this done perhaps this week :) ?

**Comment by agnelnieves** [comment]
![image](https://user-images.githubusercontent.com/5799157/55749007-ff8cc100-5a0d-11e9-88ac-81d715d640ca.png)

**Comment by Chandan-Baba** [comment]
Hi @msoka86 / @omudongo ,
Though I am not a professional ui designer, I always love to learn and share about design elements. So I will try to incorporate the suggestions simply by sharing multiple versions before finalizing one. Let me know if below is somewhat on the marks. 
![Sokafrika_1](https://user-images.githubusercontent.com/47283424/55750397-cfbad900-5a60-11e9-8bd9-19fe74fb67c8.png)

**Comment by msoka86** [comment]
> Hi @msoka86 / @omudongo ,
> Though I am not a professional ui designer, I always love to learn and share about design elements. 

 This is a very nice mindset to have. Coming from a family of artists, finding the combination of colors that will best portray what I want to convey is a process I really enjoy. If in the future you need help choosing a color palette for a design you can ask me anytime, I am told that I have quite the eye :)

**Comment by msoka86** [comment]
@agnelnieves  Although I like some elements a lot as well as the font and the whole looks much neater (really thank you for that), it still lacks the african feel I am going for. I added those elements to my original design and now it seems right. This will be the final design for Sokafrica logo.

![image](https://user-images.githubusercontent.com/46974328/55758747-8c0ba380-5a4f-11e9-97d8-9a020ec09a89.png)

@agnelnieves and @Chandan-Baba, now that I found what I am looking for (no need to add any written words or more elements, a simple white background is ok) whoever decides to work on this will have my utmost gratitude, and thank you both for all you did until now!

**Comment by omudongo** [comment]
> @agnelnieves Although I like some elements a lot as well as the font and the whole looks much neater (really thank you for that), it still lacks the african feel I am going for. I added those elements to my original design and now it seems right. This will be the final design for Sokafrica logo.
> 
> ![image](https://user-images.githubusercontent.com/46974328/55758747-8c0ba380-5a4f-11e9-97d8-9a020ec09a89.png)
> 
> @agnelnieves and @Chandan-Baba, now that I found what I am looking for (no need to add any written words or more elements, a simple white background is ok) whoever decides to work on this will have my utmost gratitude, and thank you both for all you did until now!

@agnelnieves  I would also go with this one. Please note the following dimensions while you prepare a final output: 

Website: Dimensions: 1200 × 630 (approximately)
Twitter: Dimensions for profile images - 400x400 pixels / Dimensions for header images are 1500x500 pixels
Facebook: Profile photo size is 360 x 360 pixels / Facebook cover photo is 828 x 465 pixels

**Comment by agnelnieves** [comment]
Hello @omudongo no worries, I actually enjoy contributing to opensource community. Sorry for the delay, I've been pretty busy lately. Here are the requested dimensions with the refined logo. I also added a png version of it so you can use it later on. 

I'd love to see what you guys end up doing with this project. I'll be around looking for the project updates. 

**Twitter**
Profile:
![image](https://user-images.githubusercontent.com/5799157/55928012-2e10c480-5be5-11e9-8c57-7298b3919e01.png)

Cover:
![image](https://user-images.githubusercontent.com/5799157/55928018-31a44b80-5be5-11e9-91a1-14bb93725dc8.png)


**Facebook**
Profile:
![image](https://user-images.githubusercontent.com/5799157/55928028-379a2c80-5be5-11e9-907f-1edb07555b72.png)

Cover:
![image](https://user-images.githubusercontent.com/5799157/55928049-3ec13a80-5be5-11e9-9803-355859f3d104.png)

**Web**
![image](https://user-images.githubusercontent.com/5799157/55928062-4aacfc80-5be5-11e9-9341-2fc04e76a4be.png)

**PNG**
![image](https://user-images.githubusercontent.com/5799157/55928112-847e0300-5be5-11e9-85b4-8986c8c4ed77.png)

**Comment by omudongo** [comment]
@agnelnieves wow! this is really amazing...thank you all so much for your time sharing your ideas and helping out. We really appreciate this and your timely response.

**Comment by pransh15** [comment]
Great work, @agnelnieves and @Chandan-Baba ! 👍 
We love your constant input here, keep up the great work, community! :heart:

@omudongo thank you for posting this here, let us know if there are any other requirements on this issue.

**Comment by omudongo** [comment]
@pransh15 I really appreciate this for my mentee. I don't have any other requirements and I will close this task.
