### ISSUE TITLE
Global Accessibility Awareness Day poster

### ISSUE THREAD

**Issue by asadotzler** [mozilla/OpenDesign#238]
## Goal: 
For Global Accessibility Awareness Day on May 16th, I'd like to share a "digital poster" on all of the Mozilla office "ambient displays" (big flatscreens) that features the text "Global Accessibility Awareness Day" "May 16th, 2019" an illustration if possible, probably the GAAD logo, and a link to a wiki page that will have some relevant content. 

## Info: 
This is primarily in support of a Mozilla office campaign, so mostly for employees, but Mozilla will also be doing a public blog post about the day and some or all of the poster may be useful for that as well. 

https://globalaccessibilityawarenessday.org/
https://globalaccessibilityawarenessday.org/participate.php

"The purpose of GAAD is to get everyone talking, thinking and learning about digital (web, software, mobile, etc.) access/inclusion and people with different disabilities."

## Style Information: 
The style is wide open. It will need to include the text Global Accessibility Awareness Day" and "May 16th" or "May 16, 2019" or similar date. It will also need to contain the text (maybe in link style) to https://wiki.mozilla.org/GAAD19 or similar URL.

## Deadline: 
May 12th

**Comment by reinhart1010** [comment]
Did someone say "Accessibility"?

![image](https://user-images.githubusercontent.com/17312341/57056647-fe2d7c00-6ccd-11e9-9e53-fd0a877f4d32.png)

**Comment by reinhart1010** [comment]
Here's another one, but in Braille.
![image](https://user-images.githubusercontent.com/17312341/57081633-593b8f00-6d1f-11e9-8d1d-734182020795.png)

**Comment by elioqoshi** [comment]
@asadotzler What do you think about this?

I thought using the color picker metaphor would resonate with enough Mozillians (based on the color picker in Firefox) :)

![Draft-01](https://user-images.githubusercontent.com/5436686/57100964-80469080-6d20-11e9-9853-0525c2cb76f8.jpg)

**Comment by elioqoshi** [comment]
Here is another version with the a11y color picker tool:
![a11y tool-01](https://user-images.githubusercontent.com/5436686/57102294-6c505e00-6d23-11e9-8161-a9ea49c017b6.jpg)

**Comment by pransh15** [comment]
Great work guys, I really like these! 👍

**Comment by asadotzler** [comment]
Elio, the one with the color picker is getting there. Do you think you could put together some variations that include the URL https://wiki.mozilla.org/GAAD2019

**Comment by elioqoshi** [comment]
This is the final design we went with: 
![Final GAAD19 (1920x1080)](https://user-images.githubusercontent.com/5436686/57763644-1788ec00-7702-11e9-9811-35739bc6a109.jpg)

Sources are here:
https://github.com/mozilla/OpenDesign/tree/master/2019/Global%20Accessibility%20Awareness%20Day

**Comment by ioana-chiorean** [comment]
The mzl.la/GAAD19 links to https://wiki.mozilla.org/GAAD2019 (vs the https://wiki.mozilla.org/GAAD19 in description - maybe worth correcting there as people will land to a non existing page)

**Comment by elioqoshi** [comment]
@ioana-chiorean where do you see the https://wiki.mozilla.org/GAAD19 link? That should be not in the final version.

**Comment by ioana-chiorean** [comment]
only here in the description - might be just me who clicked it 
"
Style Information:

The style is wide open. It will need to include the text Global Accessibility Awareness Day" and "May 16th" or "May 16, 2019" or similar date. It will also need to contain the text (maybe in link style) to https://wiki.mozilla.org/GAAD19 or similar URL.

"

**Comment by asadotzler** [comment]
Sorry for the confusion. The final link is https://wiki.mozilla.org/GAAD2019 and the mzl.la URL in the poster should point to that. I'll update the bug description.

**Comment by asadotzler** [comment]
Thank you Elio and reinhart1010.
