### ISSUE TITLE
Poster/Banner for Mozilla Event in University

### ISSUE THREAD

**Issue by manishkk** [mozilla/OpenDesign#239]
## Goal: 
Template Banner/Poster for Mozilla events and meetups

## Info: 
First I will use for a hackathon and later the same banner for general meetups. So I am looking for a general banner/poster which I can use always

## Style Information: 
I am looking for similar banners. **Poster detail will update soon.**

![Sample 1](https://user-images.githubusercontent.com/3470527/57076062-532eb980-6cf1-11e9-8bcf-2f749c7d8201.jpg)

![Sample 2](https://user-images.githubusercontent.com/3470527/57076090-6477c600-6cf1-11e9-8b29-4661fa2a35eb.jpg)

## Deadline: 
ASAP

## Tag: 
[Design Needed]

**Comment by manishkk** [comment]
@kindavishal Can you help in this?

**Comment by kindavishal** [comment]
Hi @manishkk!
Thanks for tagging me, you can find previous banners and roll ups from the repo itself, also you can check out the closed issues for similar requests. Check this https://github.com/mozilla/OpenDesign/issues/206

**Comment by pransh15** [comment]
I think apart from the generic roll-up, we can build a standard template for events.

**Comment by manishkk** [comment]
@pransh15 These kinds of banner anyone can use.

I am not good at designing. can someone design?

@kindavishal I checked closed issues also but couldn't find anything useful which I can give directly for print.

**Comment by kindavishal** [comment]
Sorry for the late reply, unfortunately I won't be able to take this as I am a bit caught up at the moment.
Also, can you please specify what you're looking for exactly? Any rough sketch or idea would do, I'll pitch this up in the group and look if anyone else can take this.

**Comment by kindavishal** [comment]
As I mentioned before, sadly I won't be able to take this, unless you are willing to wait till the next month, but this is not a tough job, I'll add the appropriate labels.
Feel free to mention about this in the TG group, so that someone else can take this up.
At the same time, tagging @pransh15, just in case :slightly_smiling_face:

**Comment by pransh15** [comment]
Do you need a banner, or a standee? You commented with a picture of a standee(3x6ft), but if it's a banner, the dimensions change accordingly.
I can look into it. Only after a couple of days though. I hope that's fine? @manishkk 

If someone else is available, please take a knack at it!
Adding a ``Good first Task`` label.

**Comment by kindavishal** [comment]
Thanks for adding the label @pransh15, I was about to!
I'll not be available till next month, due to some work! Good Luck :sparkles: 
@manishkk, you're in good hands!

**Comment by ruchikabgosain** [comment]
Hello I'll be happy to take this up!

**Comment by ruchikabgosain** [comment]
Sure I will do that @manishkk. Just wanted to know the dimensions?

**Comment by ruchikabgosain** [comment]
will be posting the banner by tomorrow latest.

**Comment by manishkk** [comment]
@ruchikabgosain I am not sure about the dimensions but I can confirm and will update here.

**Comment by ruchikabgosain** [comment]
@manishkk sure please!

**Comment by manishkk** [comment]
I confirmed with the person who will print. According to them they want roll up size 85*200 in centimeters.

@ruchikabgosain can you design and upload PDF here?

Thanks

> 3x6ft

**Comment by ruchikabgosain** [comment]
Surely I will do that by tomorrow, thanks! @manishkk

**Comment by ruchikabgosain** [comment]
Hello @manishkk, there you go with 85x200 cm. Let me know if there are any edits. Thanks :) 
[Poster Security 85 x 200 cm.pdf](https://github.com/mozilla/OpenDesign/files/3188942/Poster.Security.85.x.200.cm.pdf)
![Poster Security 85 x 200 cm@3x](https://user-images.githubusercontent.com/30324532/57885373-6d67ac00-7848-11e9-8073-6f27db459f45.png)

**Comment by ruchikabgosain** [comment]
Also, @pransh15 here is a standard 3x6ft banner. Thanks! 

![Poster Security 3 x 6 ft@3x](https://user-images.githubusercontent.com/30324532/57885621-faab0080-7848-11e9-8d8e-cbff936d013b.png)

**Comment by manishkk** [comment]
Thanks, @ruchikabgosain 

Now weekend here in Israel, I will let you know next week if any edit required by printing shop.

Thanks

**Comment by manishkk** [comment]
Printing shop is close for this week, I will inform you next week if any change required.

Thanks

**Comment by ruchikabgosain** [comment]
Sure thing.

**Comment by kindavishal** [comment]
Ping! Got what you needed @manishkk ?

**Comment by manishkk** [comment]
Printing shop is closed from last week, I can confirm on Monday. Thanks

**Comment by kindavishal** [comment]
Hi @manishkk the sizes @ruchikabgosain has provided are the standard sizes for banners. If your shop prints banners, I am pretty sure there won't be any problem. If you're happy with the design, please close this issue.
Thanks :slightly_smiling_face:

**Comment by manishkk** [comment]
Thanks for the help @ruchikabgosain @kindavishal

**Comment by pransh15** [comment]
Hey @ruchikabgosain,

Can you please replace the logo with the new Firefox Desktop logo and send the new one here?
You can find the logo at [mozilla.design](https://mozilla.design/)

**Comment by bobreyes** [comment]
> Hey @ruchikabgosain,
> 
> Can you please replace the logo with the new Firefox Desktop logo and send the new one here?
> You can find the logo at [mozilla.design](https://mozilla.design/)

This new Firefox logo, you mean?

![Fx-Browser-icon-fullColor-128](https://user-images.githubusercontent.com/2232/68530216-64f8b580-0341-11ea-8c96-46293ea7a71f.png)

**Comment by kindavishal** [comment]
> > Hey @ruchikabgosain,
> > Can you please replace the logo with the new Firefox Desktop logo and send the new one here?
> > You can find the logo at [mozilla.design](https://mozilla.design/)
> 
> This new Firefox logo, you mean?
> 
> ![Fx-Browser-icon-fullColor-128](https://user-images.githubusercontent.com/2232/68530216-64f8b580-0341-11ea-8c96-46293ea7a71f.png)

That's right

**Comment by likeanushkaa** [comment]
Is this issue still open?

**Comment by manishkk** [comment]
> Is this issue still open?

No @anushja 

Thanks!

**Comment by likeanushkaa** [comment]
Sure, no problem!😄
