### ISSUE TITLE
Mozilla.cz logo

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/OpenDesign#24]
## Goal: 
We would like to have our own logo for regional http://www.mozilla.cz/.

## Info: 
We want to use the loge on the website itself and as social media (FB, Twitter) avatar and/or in header image to be better recognized on Czech Internet.

## Style Information: 
No big requirements, but will be nice to have some Czech theme (flag pattern, ...), may also include text _Mozilla.cz_, but does not have to.

## Deadline: 
May '16

## Tag: 
Design Needed

**Comment by Ken-Saunders** [comment]
Hey,
It's been a long time since I've worked on graphics but I've been trying to get back into it and, contributing more to Mozilla.
See if there's anything <a href="http://www.accessfirefox.org//mozilla-cz/mozilla-cz-logos.html">here</a> that you like or find useful.
I take criticism/critiques very well especially when this will be your community's logo, not mine, so feel free to make suggestions and/or requests. 
Also, if there are inaccuracies with the map shape and/or the flag colors, let me know.
I initially started making my own map but it was overwhelming so I grabbed one from Wikimedia but it needed some heavy editing for things like a messed up node and the white flag color that bled under the blue and red when i removed the map's stroke (border).

With the exception of the very first one (that I'm not a fan of), the graphics were all made in Inkscape so I have the source files for them all and so they can all be edited, tweaked etc.

**Comment by MikkCZ** [comment]
Hi Ken.

I will discuss with others and let you know, if we would like to make any updates. Personally, I like the "blue coin". Maybe would it be possible to use the font from Mozilla wordmark, if it's available?

**Comment by Ken-Saunders** [comment]
<blockquote>"Maybe would it be possible to use the font from Mozilla wordmark"</blockquote>

That shouldn't be a problem.
The one that I used is Open Sans. It's based on Mozilla's <a href="https://www.mozilla.org/styleguide/websites/community/overview">Community sites</a> style guide.

<blockquote>"Personally, I like the "blue coin""</blockquote>
I do too, and the one below that (with the drop shadow).

**Comment by zelitomas** [comment]
Hi, 

I've also tried to make something up, and here some drafts I came up with:

![web](http://down.zelitomas.cf/firstWebCutted.png)

![logo_resized](http://down.zelitomas.cf/rsz_1first.png)

As the logo is intended to be used as a social media avatar, I've tried to make it as simple as possible, so it's basically just a Mozilla m with Czech tricolora added. 

![community](http://down.zelitomas.cf/rsz_1firstCommunity.png)

It's just a draft and I'm not a designer, but please let me know what you think about it anyway :)

Have a nice day
Tomáš

**Comment by zelitomas** [comment]
Ooops, I've accidentally changed the order of colors and made a Russian tricolora :)

Here's the correct version:

![Correct version](http://down.zelitomas.cf/rsz_firstCorrect.png)

**Comment by MikkCZ** [comment]
@Ken-Saunders According to the feedback I received, it's a draw between #5 and #6. Could you please make a variation of them - with the CZ below and inside the state, and with/without the shadow below, and possibly a set without any text?

@zelitomas Does not look bad at all. May I ask you to create a variant with all three tricolora paint stripes in the background and the "m" in one color for comparison? Having in background painted flag instead of stripes can be a second idea.

I did not expected so many proposals. I start thinking about creating a repository for you and then let the community and users vote.

**Comment by elioqoshi** [comment]
@zelitomas really like your proposal! maybe put the flag colors a bit upwards? there is a small part empty between the 'm' and the red.

No need for the wordmark also, you can put it seperately

**Comment by elioqoshi** [comment]
@zelitomas can you please share the source files?

Also, have a look at the Netherlands logo proposal to see how you can implement the wordmark 

https://github.com/mozilla/Community-Design/issues/17

**Comment by elioqoshi** [comment]
@Ken-Saunders thanks for the proposals! However the current style you used is quite disaligned with the Mozilla style direction. Maybe have a look at some other community logos to get an idea?
Try avoiding shadows and gradients if you can

**Comment by zelitomas** [comment]
@elioqoshi Ok, but please keep in mind that I'm really not a designer and I don't know how to work with graphics (that's why I used GIMP, which is unsuitable for this kind of work), so I've made a few things I'm not really proud of...

https://goo.gl/jpQ5Lw

**Comment by elioqoshi** [comment]
Thank you @zelitomas !

here are 2 variants of mine:

![preview](https://cloud.githubusercontent.com/assets/5436686/12993757/79d70516-d11c-11e5-9bf4-613f2c313915.jpg)

**Comment by MikkCZ** [comment]
I like those proposals. If you wouldn't mind, I have created a repository https://github.com/MozillaCZ/logo. @Ken-Saunders , @zelitomas , @elioqoshi - you should be able to commit there. Once all you final proposals are there, I will start my work on the vote and getting feedback from the community. Thank you all very much.

**Comment by elioqoshi** [comment]
@MikkCZ not really familiar with pushing in GitHub, feel free to do it :)

**Comment by MikkCZ** [comment]
@elioqoshi Added them there. Do you also have sources of them?

**Comment by elioqoshi** [comment]
@MikkCZ Sure! Will send them in if it gets approved

**Comment by MikkCZ** [comment]
I've created a form as part of https://github.com/MozillaCZ/logo/issues/1 and shared today via Twitter and Facebook. There are already few tenths of responses - I will let the form open till the next week and share the summarized feedback here.

**Comment by MikkCZ** [comment]
Soooo, sorry for such delay. The results from the form are these:
- we've got over 800 responses!
- 71% of them marked the "m" variant from @elioqoshi as liked, other options were under 41% as liked
- 56% of responds said they like the "m" variant the most, other variants were under 30%

Also I would say the "m" logo from @elioqoshi is the winner, but there were also some negative reactions on it:
- the tricolor is not in the right order (white in the middle), which I think cannot be done much about
- the tricolor does not differ Czech from any other country with the same colors
- looks like a supermarket logo
- looks like [mBank](http://www.mbank.cz/) logo

I don't wanna judge those reactions as valid or not, but do any of you have any comments on this, or ideas for improvements/second iteration, if you feel the logo can do even better?

**Comment by MikkCZ** [comment]
@elioqoshi ?

**Comment by elioqoshi** [comment]
@MikkCZ well, I sent in my proposals and feedback like "looks like a supermarket logo or
looks like mBank logo" is not really helpful. So if you like the current version, feel free to go ahead with it.

**Comment by MikkCZ** [comment]
Yes, I know. That's not my feedback nor my attitude, only what I have found in responses.

I like the proposals you have created and most of the responders too. If you have no update about the color positions in the logo or any next iteration, can you please push the sources or better resolution to https://github.com/MozillaCZ/logo or into this repo, if you have access?

**Comment by elioqoshi** [comment]
Yes sure, will export them

**Comment by zelitomas** [comment]
@elioqoshi So how does it look with the exported version?

**Comment by elioqoshi** [comment]
@zelitomas wow, I have totally lost this issue! Will catch up soon

**Comment by zelitomas** [comment]
@elioqoshi Are there any problems? If there are, would you please at least export the logo in higher resolution (preferably in png) that we could use on social networks until you'll be able to send the sources? It would be really helpful, because Mozilla contacted us asking if we could stop using Firefox logo as profile picture on Facebook and Twitter.

Thank you and sorry for my bad English.

**Comment by elioqoshi** [comment]
Sorry, I failed to get this notification here. Here we go:
http://elioqoshi.me/owncloud/index.php/s/ODP9WOy2ZI2Y5yf

**Comment by MikkCZ** [comment]
Great, downloaded and I will upload it to our repo in a minute, and on website and social media later this weak. Thank you very much, and thanks everyone for their designs too!
