### ISSUE TITLE
user  data  storage  independent from  service providers

### ISSUE THREAD

**Issue by holu123gg** [mozilla/OpenDesign#241]
## Goal: 
[more  privacy, more  freedom]

## Info: 
[for example:  a user  can  store  his  favorite  music   list  in  dropbox or  his own  server or  any  other  place  he  agrees , then  after  an agreement  the user  made,  any music  player  service provider can  play  the  list for  the user , there  will be  only one copy of the list, but  user can enjoy  different  service  from any  service provider  he  like . other examples: different  calendar  apps  using  one  calendar  events  list  from  each user; different   social  apps  using  one  friends list  from  each user  ]

## Style Information: 
[look great.]

## Deadline: 
[asap]

## Tag: 
[Developer Needed]

**Comment by kindavishal** [comment]
Hi @holu123gg!
I don't think you're asking it in the right place, we can only help you with design needs and not development needs.
Closing this issue, thank you.

**Comment by Ryuno-Ki** [comment]
@holu123gg Sounds pretty much what Sir Tim Berners-Lee tries to achieve with SoLiD at MIT …
