### ISSUE TITLE
Backdrop For DevConf'19, BLR.

### ISSUE THREAD

**Issue by pransh15** [mozilla/OpenDesign#242]
## Goal: 
Backdrop for the booth, of the size: 6ft x 4ft [WxH]

## Info: 
We (Mozilla India Community Contributors) are planning to organize a booth at Devconf'19. A 2-day Conference where contributors will be talking to the participants about Bug Hunting, CommonVoice, Internet Health & Mozilla India.

Creating this issue on behalf of the Organizer, @shinadhingra18.

## Style Information: 
@tanzeelkhan created a [beautiful backdrop](https://github.com/mozilla/OpenDesign/issues/215#issuecomment-407991568) last time, something along the same lines.

## Deadline: 
ASAP or 18th July, 2019. Whichever's quicker.

## Tag: 
[Design Needed]

**Comment by tanzeelkhan** [comment]
I'm on it! :)

**Comment by tanzeelkhan** [comment]
![devconf-19-banner](https://user-images.githubusercontent.com/4867861/61582108-2d70be00-ab44-11e9-9d3f-81525b648f10.png)
[printable-devconf 19 banner.pdf](https://github.com/mozilla/OpenDesign/files/3413867/printable-devconf.19.banner.pdf)

**Comment by tanzeelkhan** [comment]
![devconf-19-banner](https://user-images.githubusercontent.com/4867861/61582182-f2bb5580-ab44-11e9-865c-8d0899d83a43.png)

**Comment by tanzeelkhan** [comment]
![printable-devconf-19-banner-2](https://user-images.githubusercontent.com/4867861/61582280-8fcabe00-ab46-11e9-98b8-1b6ffbcc19e4.png)
[printable-devconf 19 banner 2.pdf](https://github.com/mozilla/OpenDesign/files/3413876/printable-devconf.19.banner.2.pdf)

**Comment by pransh15** [comment]
the colors look really good with the icons.
thank you for doing this at a very quick pace, appreciate it! 💘

**Comment by shinadhingra18** [comment]
This is great! @tanzeelkhan 
Thank you for your efforts on such short notice.

**Comment by tanzeelkhan** [comment]
I'm at a loss for words :D
Thank you for the encouragement. :)
