### ISSUE TITLE
New identity for Mozilla Peru

### ISSUE THREAD

**Issue by AngelFQC** [mozilla/OpenDesign#243]
## Goal: 
Update the identity of [Mozilla Perú](https://mozilla.pe/) with a new logo and wordmark according to current Mozilla style.

## Info: 
The new identity will be used in the social networks and banner for events.

## Style Information: 
Currently we use the old logotype from Mozilla [1]. We have thought about updating it. 
We have not had a official brand pet... but recently we are using a paper toy with the football soccer shirt [2] (the most liked sport in the country). Maybe we should use the national bird of the country "Andean cock-of-the-rock" [3] if the use of a brand pet is mandatory.

Alternatively we made this logo https://github.com/mozillaperu/participacion/blob/master/logo.svg

## Deadline: 
When you can

## Tag: 
[Design Needed, Staff Support Needed]

[1]: https://mozilla.pe/assets/images/nosotros/mozillaperu_wordmark_bglight_medium.png
[2]: https://mozilla.pe/assets/images/papertoy.jpg
[3]: https://en.wikipedia.org/wiki/Andean_cock-of-the-rock

**Comment by klhernandez42** [comment]
hi @AngelFQC, I could help you but ¿this is a "andean cock-of-the-rock? ¿right?
https://peru.info/Portals/0/Images/Productos/6/167-imagen-1325441372018.jpg

**Comment by AngelFQC** [comment]
Hi @klhernandez42 
Yes, it is a (male) cock-of-the-rock

**Comment by klhernandez42** [comment]
![Selección_999(231)](https://user-images.githubusercontent.com/2287630/64914112-aede6a00-d709-11e9-8948-763f8e7faa26.png)
This would be my proposal, You can write me by telegram anything is the same user github in spanish.

**Comment by AngelFQC** [comment]
Hola @klhernandez42 
Gracias por el logo
Puedes adjuntar los editables, porfavor. Para ir cerrando el issue.

**Comment by klhernandez42** [comment]
Genial, acá te comparto el enlace del [Logo Perú](https://github.com/mozillahispano/equipoCreativo/tree/master/MozillaPeru_logo) para que lo descargues desde el github.

**Comment by AngelFQC** [comment]
Muchas gracias @klhernandez42
