### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Lovo666** [mozilla/OpenDesign#244]
## Goal: 
[What you'd like created]

## Info: 
[What it will be used for/where it will go]

## Style Information: 
[What you want it to look like, link to references, similar things etc.]

## Deadline: 
[When would you like this done by]

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by kindavishal** [comment]
Hi @Lovo666 :wave: 
It seems you've created an empty issue. If you have any requirements from the Open Design Community, you've to specify why you're opening the issues and fill in necessary details! If this was created by mistake, don't worry I shall close this. If you had anything in mind, please open a fresh one with all the details mentioned. You may refer to other open issues for this.
Thanks :sparkles:

**Comment by Lovo666** [comment]
At the moment I have a lot to do on my job.  In addition, I would like to learn old from you.  For example, have no idea how to make the diary app or what to do with the info from the app.  That's why I need help and guidance.  For that I serve with what I am good at, translations about information of a work.  I translate from English into German and Romanian.  Best regards!  Lovo666

**Comment by Lovo666** [comment]
Thnx for yours anderstaending.
Lovo666

Vishal Das <notifications@github.com> schrieb am Mo., 21. Okt. 2019, 07:40:
