### ISSUE TITLE
Re-Structuring the Repo!

### ISSUE THREAD

**Issue by kindavishal** [mozilla/OpenDesign#245]
## Goal: 
Re-structuring the folders and files in the repo to make designs more accessible and easily discoverable!

## Info: 
There are too many awesome designs and graphics in this repo and sadly not everything is easily discoverable for new visitors/designers! Goal is to make things easy by having more relatable folders and graphics!

## Style Information: 
NA

## Deadline: 
NA

## Tag: 
NA

**Comment by kindavishal** [comment]
Adding the Hacktoberfest Label because, why not :slightly_smiling_face:

**Comment by Ryuno-Ki** [comment]
I think, it would help, if you could describe what the target structure should look like (if you already have made up your mind).

Another label could be „Good first issue” then :-)

**Comment by kindavishal** [comment]
> I think, it would help, if you could describe what the target structure should look like (if you already have made up your mind).
> 
> Another label could be „Good first issue” then :-)

Thanks for the suggestion @Ryuno-Ki :smile: but I was already supposed to do this myself sometime ago so didn't open it up for everyone! :grimacing: 
However I will make it more clear if more inputs are required! :100:

**Comment by Ryuno-Ki** [comment]
Ah, so that's done in #246 then?
I somehow would have needed another hint, that this topic is already in the works (e.g. by assigning it to someone - or removing the „feedback needed” label).
I had too many times „snitched” issues on this year's Hacktoberfest, so no worries. By now I have my four PRs together :-)

**Comment by kindavishal** [comment]
Ah! Sorry for the confusion Ryuno!
Congrats on your 4 PRs! :tada: :smile:

**Comment by kindavishal** [comment]
The new changes have been merged! Closing this!
