### ISSUE TITLE
Safer Internet Day Graphic

### ISSUE THREAD

**Issue by bobreyes** [mozilla/OpenDesign#254]
## Goal: 
Generic graphics material for Safer Internet Day (which is celebrated every 2nd Tuesday of February).

## Info: 
For use on social media channels of Mozilla communities.

## Style Information: 
Will leave it up to the designers. Samples are here:
https://www.google.com/search?q=Safer+Internet+Day&client=firefox-b-d&sxsrf=ACYBGNT0g51xdWVpwmsgt2Da9EyXgrsTzA:1580826270687&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiEmsPijLjnAhWCe30KHRaOB0sQ_AUoAXoECBgQAw&biw=1440&bih=738

## Deadline: 
On or before Mon 10 FEB 2020

## Tag: 
Design Needed

**Comment by Vinit-bisht** [comment]
Try soemthing on figma!
![Artboard 1](https://user-images.githubusercontent.com/54279468/95673209-5f949280-0bc4-11eb-840f-e87607b7d65d.png)
I know it's late, but I am just trying to work formally in Github!

**Comment by kindavishal** [comment]
Hey @bobreyes :wave: 
Still need any help here? Or can we close this?

**Comment by bobreyes** [comment]
> Hey @bobreyes 👋
> Still need any help here? Or can we close this?

Thank you!
