### ISSUE TITLE
Mozilla Indonesia Community – Jakarta Space Interior Design

### ISSUE THREAD

**Issue by fauzanalfi** [mozilla/OpenDesign#29]
**Goal:** interior design for upcoming Mozilla Space in Jakarta

**Floor Plan:**
The space is going to be on office-labeled room on the left side
https://dl.dropboxusercontent.com/u/4450713/mozilla/community-space/WorkRoom%20-%20Denah.jpg

**Comment by fauzanalfi** [comment]
Assigning to myself.

**Comment by elioqoshi** [comment]
Fantastic use cast @fauzanalfi ! Please share the process and source files with us within your possibilities :)

**Comment by fauzanalfi** [comment]
First update on the design. It's still on progress and needs more refinement. 

<img width="1252" alt="screen shot 2016-02-27 at 8 04 24 pm" src="https://cloud.githubusercontent.com/assets/1860909/13373027/774d461a-dd8e-11e5-97ce-91221a7d434a.png">

**Comment by yofiesetiawan** [comment]
Good job @fauzanalfi :)

**Comment by fauzanalfi** [comment]
Here's some design update on floor plan and elevations of the Space.

![jakarta space - layout](https://cloud.githubusercontent.com/assets/1860909/13433139/24cec63a-e003-11e5-8a59-06c9ea3370ad.jpg)

**Comment by ioana-chiorean** [comment]
I added another space to get the best of the room:
![screenshot 2016-03-03 22 15 13](https://cloud.githubusercontent.com/assets/1391451/13508788/2323b572-e191-11e5-9282-5d2125751f4d.png)
![screenshot 2016-03-03 22 16 08](https://cloud.githubusercontent.com/assets/1391451/13508786/232212c6-e191-11e5-9759-8752e577a1e3.png)
![screenshot 2016-03-03 22 17 01](https://cloud.githubusercontent.com/assets/1391451/13508789/2323f082-e191-11e5-8b9a-d45965314007.png)
![screenshot 2016-03-03 22 20 16](https://cloud.githubusercontent.com/assets/1391451/13508790/2325a666-e191-11e5-98ee-3fc9ca6521bf.png)
![screenshot 2016-03-03 22 20 45](https://cloud.githubusercontent.com/assets/1391451/13508785/23204676-e191-11e5-9d38-a9ef3a516743.png)
![screenshot 2016-03-03 22 21 12](https://cloud.githubusercontent.com/assets/1391451/13508787/2322daa8-e191-11e5-89e5-faf38129396e.png)
![screenshot 2016-03-03 22 31 09](https://cloud.githubusercontent.com/assets/1391451/13508791/2383c19c-e191-11e5-808d-709b716c084a.png)

![photo_2016-03-03_22-44-07](https://cloud.githubusercontent.com/assets/1391451/13508902/a153b514-e191-11e5-8ad2-8f852e823a46.jpg)
![photo_2016-03-03_22-44-13](https://cloud.githubusercontent.com/assets/1391451/13508903/a17ec696-e191-11e5-94f9-a3e9a56f7dff.jpg)

**Comment by fauzanalfi** [comment]
@ioana-chiorean love it! :heart_eyes: Overall, I really like your inputs. We will discuss it with Jakarta Comspace Crew and see if it's fit with our budget. /cc @yofiesetiawan

**Comment by flaki** [comment]
Not sure why was I summoned into the thread, but I sure do love the pigfoxes! :relaxed:

**Comment by ioana-chiorean** [comment]
> Not sure why was I summoned into the thread, but I sure do love the pigfoxes! :relaxed: (@flaki)

Just for the fox pillows. sorry for the fox-spam.

**Comment by elioqoshi** [comment]
Holy! Great job guys! A good example how Community Design goes far beyond than graphic design only :)

@LucyeoH this is a really amazing case study

**Comment by fauzanalfi** [comment]
Thanks everyone who've contributed on this issue. Sorry if I'm late on closing this one. Mozilla Community Space Jakarta is now open for public and you guys are invited to come to the Space. More info on the Space: [mozilla.or.id/space](http://mozilla.or.id/space)
