### ISSUE TITLE
WordPress/Bootstrap Theme with Mozilla Design Style

### ISSUE THREAD

**Issue by Mte90** [mozilla/OpenDesign#3]
I have started to work to a Bootstrap theme in SASS with the Mozilla style based on Mozilla.org and Mozilla Indonesia site.

The stuff to do:
- Complete design
- Improve the PHP code for bootstrap compatibility in wordpress
- Improve the Bootstrap code about the design
- Other stuff are for developer but there are tickets opened in every repo

Repo: https://github.com/Mte90/WP-Mozilla
Demo site: http://mozilla.mte90.net/

Repo of BootStrap style: https://github.com/Mte90/MozStrap/
Demo site: https://mte90.github.io/MozStrap/

**Comment by Mte90** [comment]
The developer need to know SASS/CSS for the frontend part or WordPress to help me on that part.
More developers less time to work on :-)

**Comment by elioqoshi** [comment]
I'm unable to commit on this, but I hope someone else is able to join

**Comment by Mte90** [comment]
Well actually I need to have a designer, the development part I can do it without problem.
I have added that info for the Developer needed labels

**Comment by parag9d** [comment]
I wish to work on the design part of the website. Please provide me with some details about what this site is going to be about. Thank you.

**Comment by parag9d** [comment]
Could you please share more about the purpose of this WordPress/Bootstrap theme?

**Comment by Mte90** [comment]
You have seen the demo site? 
The purpose is create a Bootstrap and WordPress theme with the Mozilla design style. In this way the local community can download and use it without problem and customize.

**Comment by parag9d** [comment]
Okay, so you want to create a template so that for every new page people don't have to rewrite the code and re-use the theme. Right? What help do you need in design for this?

**Comment by Mte90** [comment]
Check if the actual design that I've made is ok, evaluate the sidebar design and check bootstrap for the design of new components http://getbootstrap.com/css/
ASAP I hope to share a demo only of bootstrap that contain the actual design.

**Comment by joshua-s** [comment]
Nice work!

Just one note: Tabzilla should be updated. It recently changed to not include the expanding menu anymore.

**Comment by Mte90** [comment]
I a really work in progress so open a ticket in the repo for that!

**Comment by Mte90** [comment]
I have created a repo only for the bootstrap style with a demo page, that page show all the missing part of that design

Repo of BootStrap style: https://github.com/Mte90/MozStrap/
Demo site: https://mte90.github.io/MozStrap/

**Comment by elioqoshi** [comment]
@Mte90 that looks amazing! Can't wait to see this finished :)

**Comment by Ryuno-Ki** [comment]
@Mte90 Could you add some Lorem Ipsum in the main part of the demo? Maybe even explaining the purpose of the site.

Oh, and I noted that switching themes yield 404s (probably because they're links which didn't get intercepted by jQuery).

```css
button {
    background: inherit
}
```
is missing (on *indicators* section).
Gray text on disabled pager button is [hard to read](https://leaverou.github.io/contrast-ratio/#%23777-on-%23c4372d).

Language Links in the upper right ("EN" and "IT") open a link in a new tab - on purpose?

Looks good so far. Fix [several accessibility issues](https://tenon.io/testNow.php?url=https://mte90.github.io/MozStrap/) and you're good to go.

**Comment by Mte90** [comment]
Hi @Ryuno-Ki,
thanks for that feedback can you open a tickets in the specific repos to help me to track that, but when I have time I work on that.

**Comment by Ryuno-Ki** [comment]
Done. Sorry for the many references, but I prefer to keep the context where possible.

**Comment by elioqoshi** [comment]
@Mte90 how is this going?

**Comment by Mte90** [comment]
Actual there is this bootstrap css https://github.com/mozilla/mozmaker that is official and the demo on https://mozilla.github.io/mozmaker/demo/
but the wp project is stopped

**Comment by Mte90** [comment]
An idea is to switch to the official mozmaker and abandon my version but the design of a site will be not the same of the official Mozilla website.
