### ISSUE TITLE
Start a 'Design buddies' (Dbuds) program

### ISSUE THREAD

**Issue by cassiemc** [mozilla/OpenDesign#30]
At the Foundation we started a 'Dbuds' program last year so that when we hire someone new on staff, we pair them with someone already on staff so that have a bit of a buddy – someone to check in with regularly and to ask questions – as they're learning to integrate with Mozilla projects and processes. This could work really well between staff and community members.

The idea is super simple: once paired up, the two buddies can decide between them how / when / how often they'd like to meet. They would talk about any issues they're working on or thinking about and share progress. Gives people an opportunity to form a closer connection with each other across projects, time zones and other various hurdles, and in my experience it has surfaced awesome new collaborations and learning opportunities.

Wondering if anyone in this repo would be interested in such a thing? If so, maybe add your name to this list and introduce yourself below.

**Mozilla Staff**
- @lime124 
- @natalieworth 
- @designakt

**Non-mozilla staff**
- @elioqoshi 
- @seeam
- @parag9d
- @jkachhadia

**Comment by elioqoshi** [comment]
I'd be interested! I'm pretty familiar with our processes though, so always willing to mentor someone else (I'm kind of doing it already unofficially).

**Comment by seeam** [comment]
Hi, I'm interested too. Though I'm producing design for Mozilla Bangladesh community for almost two years accordingly style guide, still I have never worked with global community before.  I have produced lots of print design and event promotion material and worked with the Firefox OS social promo team. 
But as a designer, I mostly create visual design for various interfaces (and I love it). So I would love to mentor someone who is new member of visual design world and I would also love to be mentored by someone to know the Mozilla ways of doing work!
By the way, here is my ugly portfolio: https://dribbble.com/seeam

**Comment by elioqoshi** [comment]
@seeam so humble :D
Are you on Telegram?

**Comment by seeam** [comment]
Yes, the nick is @seeam too on telegram.

Sashoto Seeam
Visual Designer,
https://dribbble.com/seeam

**Comment by seeam** [comment]
Mistakenly my previous comment copied my long email signature. Anyway my nick on telegram is @seeam too.

**Comment by lime124** [comment]
sign me up! :)

**Comment by cassiemc** [comment]
Thanks @lime124!

**Comment by natalieworth** [comment]
Yes! I'd be up for this!

**Comment by designakt** [comment]
Yes, sound great. Sign me up.
_(preferably for everything to do with Firefox Desktop and/or Add-ons.)_

**Comment by parag9d** [comment]
Hi,

I would really love to be a part of this. I am new to the Mozilla community
and would like to have a mentor to help me with the
Mozilla way of doing things :)

Here is my portfolio: https://dribbble.com/ParagNandi

Thanks.

Regards,
Parag Nandi

**Comment by jkachhadia** [comment]
hey,
I am a designer/animator/Frontend web developer and would like to be a part of this program.I would love to work with the mozilla's global community.I would love to have awesome mentors like you guys.
Resume with portfolio links : https://drive.google.com/file/d/0B8QJe4owuNjMeXlOWEd5a0ZMZXM/view?usp=sharing
Regards
Jay Kachhadia

**Comment by LucyeoH** [comment]
@cassiemc let me know if you want me to also send an email to the contributor mailing list about this!

**Comment by cassiemc** [comment]
That would be awesome @LucyeoH! Only I'm just not sure what the next step is. Maybe you and I could put our heads together?

**Comment by cassiemc** [comment]
@xmatthewx @lovegushwa maybe you guys want to put heads together with @LucyeoH, given my imminent mat leave?

**Comment by edangor** [comment]
Hi, I'm new (and late to this issue but...), could I be part of this?
