### ISSUE TITLE
Electrolisys project logo design

### ISSUE THREAD

**Issue by bslassey** [mozilla/OpenDesign#32]
## Goal:

Assets for e10s swag
## Info:

zip up fleece 
## Style Information:

I'm looking for a logo design. The project name lends itself to a few graphical themes. Electrolysis is the separation of elements (atoms) using direct current electricity, which is analogous to what the project did in separating the chrome of the browser from the web content into two separate processes. That leads to several themes that could be incorporated, including the separation of atoms (usually represented as circles or spheres much like our firefox, nightly, beta and dev edition logos), electricity and lab beakers. 
## Deadline:

Before release of the product (currently slated for April 19, 2016)
## Tag:

Design Needed

**Comment by elioqoshi** [comment]
I would love to take it on, (especially if I have a chance for a zip up fleece :D )
WIll work on a proposal in the next days

**Comment by elioqoshi** [comment]
Sorry, was really caught up, will need some more time on this

**Comment by edangor** [comment]
Hi, is this still going?

**Comment by bslassey** [comment]
Yes, I'm still looking for a design

**Comment by edangor** [comment]
oh ok

**Comment by elioqoshi** [comment]
@mart3ll need your opinion here. Probably more of an artwork than a logo needed here?

**Comment by edangor** [comment]
Aww, I was working on my proposals 😢.

**Comment by ioana-chiorean** [comment]
@edangor there is not problem, Finish them and share them here! ( I think Elio wanted to get more context here/ inputs)
