### ISSUE TITLE
Logo needed for Mozilla Policy Events

### ISSUE THREAD

**Issue by MozStacy** [mozilla/OpenDesign#37]
## Goal:

Mozilla policy volunteers are in need of a logo with our name incorporated.
## Info:

The logo will be used for on our events wikis and events materials (similarly to how we use our Privacy Lab logo now). 
## Style Information:

We think we'd like the design to be a fox (like the plushie fox) with Raegan MacDonald's glasses on.  I have attached a photo.  The logo should also incorporate the name of the group, which we should have agreement on shortly (ideas welcome).  
## Deadline:

Please tell us what is reasonable.  Ideally, we'd like to have th new logo by the end of March.
## Tag:

[Design Needed, Developer Needed, Question, Staff Supp
<img width="1426" alt="policylogotemplate" src="https://cloud.githubusercontent.com/assets/14221139/13535435/fe70e188-e1ee-11e5-8973-3128a23d736e.png">
ort Needed]

**Comment by elioqoshi** [comment]
@MozStacy Thanks for submitting the issue!

I'm not sure how a glass wearing fox would be related to Policies, could you please clarify that?
Also, is "Mozilla Policy" the final name?

Thanks!

**Comment by elioqoshi** [comment]
@MozStacy  ping again :)

**Comment by Tess-welhazi** [comment]
Been a while since anyone commented is the logo still needed?

**Comment by elioqoshi** [comment]
Closing this, no updates at all here.
