### ISSUE TITLE
Mozilla Presentation Boilerplate

### ISSUE THREAD

**Issue by Mte90** [mozilla/OpenDesign#4]
Improve the design style following the Mozilla design rules of that boilerplate for presentation in HTML.

Repo: https://github.com/Mte90/Mozilla-Presentation-Boilerplate
Demo: https://mte90.github.io/Mozilla-Presentation-Boilerplate

**Comment by elioqoshi** [comment]
@Mte90 If we design this, can you convert it back into code?

**Comment by Mte90** [comment]
Sure!
The actual design is mine based on Mozilla stuff.
As you can see is easy to change the color of background with a simple css class that change the style of all the slide.

**Comment by elioqoshi** [comment]
Thanks! @yofiesetiawan want to take this over?

**Comment by yofiesetiawan** [comment]
@elioqoshi to be honest, i'm not clear with the brief.. So there are 12 slides, we need to design 12 different slides?

**Comment by Mte90** [comment]
The idea is a Mozilla design to use for presentation/talks. 
In that demo of boilerplate I show the various colour scheme versions.
That design can be used also for powerpoint presentation.

**Comment by yofiesetiawan** [comment]
I thought this issue is just sharing what @Mte90 has done with html slides design... And we can add new slide design, which also means this issue might never close...

**Comment by elioqoshi** [comment]
@yofiesetiawan no, it's pretty simple, just design the most common slide templates used in Mozilla presentations and then @Mte90 can convert them into HTML

**Comment by Mte90** [comment]
new design https://mte90.github.io/Mozilla-Presentation-Boilerplate/ based on mozilla.org
