### ISSUE TITLE
Fedora & Mozilla Activity Days Designs

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#40]
In joint efforts with Fedora, we have organized Fedora & Mozilla Activity Days where the community gets involved with both projects. I created the design here for the banners, including the cubes patterns. The dimensions are optimized for facebook cover images. I will add the source files soon.

![blue background-01](https://cloud.githubusercontent.com/assets/5436686/13679330/81550026-e6f3-11e5-9a9a-ad526e540ae6.jpg)
![light background-01](https://cloud.githubusercontent.com/assets/5436686/13679331/81e0f31a-e6f3-11e5-910e-5392919b9eb3.jpg)
![red background-01](https://cloud.githubusercontent.com/assets/5436686/13679332/81f09478-e6f3-11e5-86e5-96f57974bd64.jpg)

**Comment by barrostecnologia** [comment]
@elioqoshi you have the source files? I liked this background, it would be interesting this art banner for [Mozilla São Paulo Workday](https://github.com/mozilla/Community-Design/issues/54).
Thanks...

**Comment by elioqoshi** [comment]
I will try to get it done within the week @barrostecnologia  :)

**Comment by GABBAR1947** [comment]
something like this...just a rough draft
![15935299_1430189093666051_1755219182_o](https://cloud.githubusercontent.com/assets/9786291/21744231/a792a846-d537-11e6-99d9-981243977a38.jpg)

**Comment by Tess-welhazi** [comment]
I don't understand what's requested here especially since the issue is still open

**Comment by elioqoshi** [comment]
I just wanted to report back as I did the design for the events. No call for action here (not sure why it's not closed)

@GABBAR1947 no please, butchering logos like this is a no-go.
