### ISSUE TITLE
Mozilla Community Makassar

### ISSUE THREAD

**Issue by fahrulrazy** [mozilla/OpenDesign#45]
## Goal:

We would like to create every Firefox Club Logo and Mozilla Club Logo in East Indonesia as one of our promotion strategy campaign. We have created two logos (PNUP Firefox Club and Mozilla Club Makassar)
## Info:

The logo will be used for event's publication (poster, pamphlet, etc) and also we would like to create sticker. We also need FSA logo in vector
## Style Information:

Simple, there is FSA logo, flat design, and eye-catching
## PNUP Firefox Club:

![pnupfckecil](https://cloud.githubusercontent.com/assets/6801259/13762487/48548730-ea7a-11e5-86b1-a57b86126423.png)
## Mozilla Club Makassar:

![mozilla club mks](https://cloud.githubusercontent.com/assets/6801259/13762518/7f61006e-ea7a-11e5-8595-dad3b1a15014.png)

**Comment by elioqoshi** [comment]
Hi @fahrulrazy !
I'm not sure what your request is here. Also, I do not think it's wise to create a logo for every Club in such a big quantity, it would be rather smart to have a general Firefox Club logo template, and you add the name of the Club behind it

**Comment by fahrulrazy** [comment]
Hello @elioqoshi 
Thanks for your advise, I think that's good idea. Is there any general Firefox Club logo template? or we can create by ourselves?

**Comment by elioqoshi** [comment]
Yep, here we go
![firefoxclubmakassar-01](https://cloud.githubusercontent.com/assets/5436686/13809031/21f43d20-eb69-11e5-9e3b-ac080644d503.jpg)

**Comment by elioqoshi** [comment]
Then again, this could be a better solution:
https://github.com/mozilla/Community-Design/issues/46
