### ISSUE TITLE
Firefox Club Logo Template

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#46]
To help Firefox Student Ambassadors who need logos for their Clubs, I think to keep it simple and in line with the FSA Logo, which can be used as a template by other Clubs. What do you think?

![v2-01](https://cloud.githubusercontent.com/assets/5436686/13809832/f62592b2-eb6c-11e5-81d6-f40f8f846f04.jpg)
I have also created a template based on the logo by @medmack but it might be better to not add another subbrand identity or similar

![v1](https://cloud.githubusercontent.com/assets/5436686/13809888/3db95d02-eb6d-11e5-8d4d-0a7cc325db82.jpg)

Would you be okay to choose the first FSA based template?

**Comment by Mte90** [comment]
A FSA based template is not bad, create a brand identity.
I think that the second option is better because the logo is small and maybe can customized with the flag of the country like the milan logo.

**Comment by elioqoshi** [comment]
We do not need so much customization, think that hundreds of Club worldwide will have it

**Comment by seeam** [comment]
I personally liked the first version (fsa based) as it is aligned with current logos. Also the second version won't be fit as a template in my opinion. Because smaller or larger text may not look good on that.

**Comment by seeam** [comment]
So what is the decision @elioqoshi? I got same request from a local Firefox Club and followed the first example.
![diu](https://cloud.githubusercontent.com/assets/7550283/13856288/b22ac9c8-ec9e-11e5-98f6-7786db18462a.png)

**Comment by elioqoshi** [comment]
I think that is fine, let's wait a few more days before taking this further

**Comment by fayetandog** [comment]
Hi! Faye here from the FSA team. Commenting to participate on the discussion so we can communicate this to Firefox Club leads and implement in the future. We have a process for establishing Firefox Clubs so it would be crucial to communicate a logo guideline if it will be implemented. Thanks for initiating this!

**Comment by constantine599** [comment]
Hi shubham here from RAL, United States. I think the first logo looks really sharp and professional keeping the primary logo of the organisation stable by having the fox face followed by the name on the side. Moreover it shouts authentic and original when I see the first logo.  The second logo on the other hand is good job done but its too big and doesn't have the fox face(which has been the logo since long time) instead has a Firefox globe.
