### ISSUE TITLE
Need a logo for Mozilla QA to make sticker

### ISSUE THREAD

**Issue by umeshagarwal** [mozilla/OpenDesign#51]
## Goal:

Mozilla QA logo 
## Info:

For making stickers for local community in India
## Style Information:

According to Mozilla Style guide
## Deadline:

As soon as possible
## Tag:

Design Needed

**Comment by ioana-chiorean** [comment]
@umeshagarwal is this for a local QA community or the Mozilla QA big one? I am asking as there is already a sticker design for Mozilla QA. 

U can check it out here: https://wiki.mozilla.org/QA 

@mozillamarcia has probably the sources for it.

**Comment by umeshagarwal** [comment]
@ioana-chiorean  Thanks for the update! Actually i saw them and found that there are different logo for different QA projects. Also the logo on the wiki page is more like badge. 

I was looking for something like the participation logo : https://wiki.mozilla.org/images/thumb/0/04/Mozilla_Participation.svg/253px-Mozilla_Participation.svg.png

I will wait for @mozillamarcia to provide more information on this :)

**Comment by elioqoshi** [comment]
@umeshagarwal can you ping @mozillamarcia via PM for this?
