### ISSUE TITLE
Take Back the Web/Campus Campaign Logo Needed

### ISSUE THREAD

**Issue by charissalaisy** [mozilla/OpenDesign#52]
## Goal:

We need a logo for the campus campaign! Our website has already been designed but we need a small logo in our color scheme.
## Info:

The logo will be used in our resources--PowerPoints, documents, etc. It should be a relatively small image that's able to be used in lots of different contexts.
## Style Information:

Our color scheme is on the website: https://takebacktheweb.mozilla.community/
## Deadline:

Wednesday, 4/6
## Tag:

Design Needed

**Comment by LucyeoH** [comment]
@yofiesetiawan any interest/time to take this?

**Comment by yofiesetiawan** [comment]
@LucyeoH i'm no good with logo.. maybe @elioqoshi ?

**Comment by Subway19** [comment]
Hows this ?
![capture](https://cloud.githubusercontent.com/assets/14835320/14269525/21a39e5c-fb03-11e5-8928-970e10a7713c.jpg)

**Comment by yofiesetiawan** [comment]
@Subway19 can you upload the transparent png? so i can try to put it on the web layout?

**Comment by Subway19** [comment]
Here

![logo - copy](https://cloud.githubusercontent.com/assets/14835320/14284346/cbeb9e9e-fb64-11e5-836d-c77a752138d5.png)

**Comment by charissalaisy** [comment]
Hi @Subway19! Thank you for creating this logo. A few notes:

- I don't think we need any text
- We'd like the colors to be be the same as the ones on the website [https://takebacktheweb.mozilla.community/], especially the blue, yellow, and green of the hero image
- It's probably best if it's a bit more round in shape and a bit simpler

**Comment by charissalaisy** [comment]
@elioqoshi any thoughts on this option?

**Comment by birajkarmakar** [comment]
We need some graphics for social media post regarding Take Back the Web/Campus Campaign.
Here are some ideas for graphics:
1. Student is amplifying this campaign in his college Campus with other students.
2. Local coach is giving training to campus campaigners.
3. Why student thinks that secure internet is important?
4. Some graphics with some key points of Campus Campaign.
etc.

**Comment by anistuhin** [comment]
Hi, @birajkarmakar lets not populate this single issue with too many different graphics. I'm opening a new issue: #57 with those and you should edit the comment referring the new issue for those graphics :)

**Comment by birajkarmakar** [comment]
Hi @anistuhin 
I was not aware of that.  I did that because @LucyeoH pointed out this issue. 
BTW no problem. I am re-writing again in #57.

**Comment by anistuhin** [comment]
It's complete fine :)
