### ISSUE TITLE
Take Back the Web/Campus Campaign Graphics Needed

### ISSUE THREAD

**Issue by anistuhin** [mozilla/OpenDesign#57]
## Goal:

Having some important graphics created for Take Back The Web/Campus Campaign
## Info:

We need some graphics for social media post regarding Take Back the Web/Campus Campaign.
Here are some ideas for graphics:
1. Student is amplifying this campaign in his college Campus with other students.
2. Local coach is giving training to campus campaigners.
3. Why student thinks that secure internet is important?
4. Some graphics with some key points of Campus Campaign.
etc. 
## Style Information:

Our color scheme is on the website: https://takebacktheweb.mozilla.community/
## Deadline:

[When would you like this done by]
## Tag:

Design Needed

**Comment by birajkarmakar** [comment]
We need some graphics for social media post regarding Take Back the Web/Campus Campaign.
Here are some ideas for graphics:
1. Student is amplifying this campaign in his college Campus with other students.
2. Local coach is giving training to campus campaigners.
3. Why student thinks that secure internet is important?
4. Some graphics with some key points of Campus Campaign.
etc.

**Comment by josuaflores** [comment]
We'll do it :)

**Comment by analynarcilla** [comment]
Count me in! :)

**Comment by anistuhin** [comment]
Guys, those who are showing interest, you should start working on those graphics. And you can ask @LucyeoH or @birajkarmakar for any kind of inquiry about these :)

**Comment by LucyeoH** [comment]
@anistuhin yes!! I'd love to see your ideas @analynarcilla
