### ISSUE TITLE
Logo for Upcoming Mozilla Community Space Jakarta

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/OpenDesign#60]
## Goal:

Creating logo for upcoming Mozilla Community Space Jakarta
## Info:

I want to share updates about our upcoming Mozilla Community Space Jakarta logo. We are open for ideas, and suggestions.
## Style Information:

Use illustration and unique elements of Jakarta or Indonesia.
## Deadline:

End of April 2016

**Comment by yofiesetiawan** [comment]
I post 2 of my ideas.

1. Working together with Petshopbox Studio, who contribute to design our new local mascot. So we try to make our local mascot become part of the logo.
![img_2016-04-15 00 44 49](https://cloud.githubusercontent.com/assets/2810823/14538156/81b29e6c-02a4-11e6-99d8-32a532bdcebd.jpg)

2. Use the unique element of Jakarta, which is National Monument (Monas)
![mozilla-space-jakarta-sticker](https://cloud.githubusercontent.com/assets/2810823/14538179/97264d34-02a4-11e6-8665-90d908bd692f.png)

3. This one done by Mahendra, a mozillian from Jakarta. 
![img_2016-04-15 00 45 00](https://cloud.githubusercontent.com/assets/2810823/14538204/bc9c9712-02a4-11e6-9fe5-95bd2e0388f8.jpg)

**Comment by Aastha14** [comment]
@yofiesetiawan I really liked the 1st one, but I'd suggest you to include the Mozilla wordmark!

**Comment by elioqoshi** [comment]
@yofiesetiawan Do you want me to give this another look or did you already decide on this?
