### ISSUE TITLE
Badges logo/ Graphics needed for Mozilla QA Bangladesh Community

### ISSUE THREAD

**Issue by hossainalikram** [mozilla/OpenDesign#61]
## Goal:

I am looking for logo or graphics design for the role of contributors of Mozilla QA Bangladesh Community. The Logo or graphic design will be used as an Symbol for different contributors role. I am looking for designs for this specific role of contributor - "Casual Contributor", "Active Contributor", "Core Contributor", "Community Mentor". This roles are created for our local community, inspired by Web QA's contributor role, which will be implemented after getting this design. Our Contributor Roles description can be found here - https://docs.google.com/document/d/19OQf5WcLbrX36HzwJhKLMvji_da056-cHREy5zXP1Z8/edit?usp=sharing which will be updated in the community website after getting the design.
## Info:

It will be used in Wiki and also in badges.mozilla.org and our community website which will be used to recognize our contributors.
## Style Information:

The idea came from the actual contributor role at Web QA - https://wiki.mozilla.org/QA/Execution/Web_Testing/Contributor_levels and also FSA recognition system - https://wiki.mozilla.org/StudentAmbassadors/Recognition . It may give a idea.
## Deadline:

By the First week of May, 2016
## Tag:

[Design Needed]

**Comment by anistuhin** [comment]
@elioqoshi and @yofiesetiawan another great one to work on :)

**Comment by ioana-chiorean** [comment]
Adding @mozillamarcia as there were some badges made and she is also coordinating Community efforts for Firefox Desktop QA

**Comment by mozillamarcia** [comment]
The last time we did a Mozilla QA badge, it was designed by a Community Member. You can see it here: https://badges.mozilla.org/en-US/badges/badge/General-QA-Participation-Badge. There are also some other QA badges here: https://badges.mozilla.org/en-US/badges/?q=QA

**Comment by hossainalikram** [comment]
The Badges I am requesting/ planning to use for a local QA community not for the bigger QA Community ( Obviously, both can be used)

And the badges will be implemented for this roles, whom we will be working on in this quarter to better support our contributors and recognize them in a more proper way - https://wiki.mozilla.org/QA/Community/Bangladesh/Contributor_Level

This was implemented in Web QA Team a long ago and thus, we want to implement it around our community as we have larger number of volunteers and this roles will be helpful to recognize them.

**Comment by elioqoshi** [comment]
@Raphseck can you help here?

**Comment by hossainalikram** [comment]
Pinging again as the Design is still needed.

**Comment by elioqoshi** [comment]
Sorry, we missed this it seems. I am personally also unable to follow up on all design requests by my own. Is this still needed?

**Comment by hossainalikram** [comment]
Yes, It is still needed and the request is still on. 

Regards
Ikram

**Comment by elioqoshi** [comment]
@thomasjosephgreco would you like to take this on?

**Comment by Tess-welhazi** [comment]
I'm interested in taking this

**Comment by elioqoshi** [comment]
@hossainalikram still needing this?
@raphseck has done some nice badges in the past

**Comment by hossainalikram** [comment]
Yes @elioqoshi , I still need this :)

**Comment by kindavishal** [comment]
This issue is greatly outdated, @hossainalikram if you still need it, please open a new issue.
Thanks!
