### ISSUE TITLE
Logo for Unica Firefox Club (Cagliari - Italy)

### ISSUE THREAD

**Issue by edovio** [mozilla/OpenDesign#64]
## Goal:

I want to create a Logo for the UNICA Firefox Club located at Cagliari in Italy
## Info:

I want to use it on Social Pages, Web site and presentations
## Style Information:

I like the Style of Logo for the Milano Firefox Club and I want if possible to use the color of Cagliari (Red and Blue)
## Deadline:

asap
## Tag:

Design Need @Mte90 
![10688387_10202935185157447_5649550829679832495_o](https://cloud.githubusercontent.com/assets/16137636/15072561/e3acbd28-1393-11e6-89a1-765c0e607734.jpg)
![10454940_10202936302705385_5886652069012961756_o](https://cloud.githubusercontent.com/assets/16137636/15072562/e3ad439c-1393-11e6-8804-2e7bed12357e.jpg)
![10295407_10202935185677460_1286369829385892687_o](https://cloud.githubusercontent.com/assets/16137636/15072563/e3aed766-1393-11e6-8bf4-9da6b6e69084.jpg)

**Comment by Mte90** [comment]
Maybe we can use https://github.com/mozilla/Community-Design/issues/46 and change the text.
I think that like https://github.com/mozilla/Community-Design/issues/6 is better to reconize the logo also with the monuments

**Comment by elioqoshi** [comment]
@edovio  are you sure that you need a logo of your own here? We would like to try using general community logos before fragmenting

**Comment by Mte90** [comment]
They started with the promotion so a specific logos for their club will be useful for it
