### ISSUE TITLE
Logo for the Mozilla Cagliari Club

### ISSUE THREAD

**Issue by edovio** [mozilla/OpenDesign#65]
## Goal: 
a Logo for the Cagliari Mozilla Club

## Info: 
We want to use this logo in Web Pages, Social and Presentation

## Style Information: 
We don't have a specific style requirement, only if is possible to use the color of Cagliari (Red & Blu) for example we can insert a flamingo bird in the logo (example attached)

## Deadline: 
ASAP
![fenicotteri-001](https://cloud.githubusercontent.com/assets/16137636/15072692/d05bc63c-1394-11e6-881c-5e7e83ddeb48.jpg)
![fenicottero_318-62981 png](https://cloud.githubusercontent.com/assets/16137636/15072694/d05cb5b0-1394-11e6-89c3-83c42a34ff20.jpg)

## Tag: 
Design Need @Mte90

**Comment by Mte90** [comment]
I don't know if we have something for mozilla club but can be an interesting first case!

**Comment by elioqoshi** [comment]
This has too few informations. Please provide the use case and the reason for using the logo and not a general Mozilla one or Mozilla Italy one. We want to keep the different Logos to a minimum.

**Comment by Mte90** [comment]
Mozilla Italy actually it is not involved in that club, at the same time we don't have a logo template that can maintain the style of Mozilla Italia ones.
A specific logos will be helpful for the promotion.

**Comment by elioqoshi** [comment]
If it's a Mozilla Club, we shouldn't use additional images, just replace the name in the Club template
