### ISSUE TITLE
Mozilla Brand Identity Research Challenge 

### ISSUE THREAD

**Issue by Timotay** [mozilla/OpenDesign#72]
## Goal: 
Help us define Internet freedom through photography. 

## Info: 
Mozilla is fighting for an Internet with greater freedom from corporate control, and for a future where people are truly empowered, safe and independent in their online lives. These important concepts can be hard for the average person to understand. We have a hypothesis that relating messages about Internet freedom with photos of real-life "Freedom" will help people see our work as relevant to their modern life. 

We have a sense of iconic images for "Freedom" in North America, such as people enjoying nature. We know less about what images would represent the idea of freedom in other parts of the world, and this is where we could use the help of our community designers. 

## Style Information: 
We're looking for photographs from Internet searches (or your own camera) that represent the concept of "Freedom" to you. 

## Deadline: 
June 30, 2016

## Tag: 
Design Research Needed

**Comment by elioqoshi** [comment]
I'm trying really hard not to be cheesy here, but it's proving to be quite difficult. The best element to express freedom, is space I believe. The more, the better (?). This might be emphasized by a very small element (a person?) in a huge space. Like this:

![plane](https://cloud.githubusercontent.com/assets/5436686/15626667/356a1e42-24cb-11e6-93ed-81aad678f9a9.jpg)
![sea](https://cloud.githubusercontent.com/assets/5436686/15626668/356d5fda-24cb-11e6-95d7-b6ef7b83d950.jpg)


A light tower might be a good concept for this as well. Attached some concepts of mine I found (the photos are Public Domain).

![light tower](https://cloud.githubusercontent.com/assets/5436686/15626673/3e1161c2-24cb-11e6-9530-1535685932f3.jpg)

**Comment by Ryuno-Ki** [comment]
@MozJan asked me to share these images with you before the deadline is reached. He has some struggles with his GitHub account right now.

The following images are taken by him and published under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/):
[![King of the Universe](https://drscdn.500px.org/photo/157838141/q%3D80_m%3D1500/ecfa7699e2b39ad3903e3701497bd2bf)](https://500px.com/photo/157838141/king-of-the-universe-by-jan-bambach)

[![King of the World](https://drscdn.500px.org/photo/153741391/q%3D80_m%3D1500/044420ee0a8e900a8b4979c48b5c9289)](https://500px.com/photo/153741391/king-of-the-world-by-jan-bambach)

[![Watching The Night Sky](https://drscdn.500px.org/photo/133254577/q%3D80_m%3D1500/8704398610af246a142db93f265f6b54)](https://500px.com/photo/133254577/watching-the-night-sky-by-jan-bambach)

[![Colourful Clouds](https://drscdn.500px.org/photo/116373511/q%3D80_m%3D1500/f407dc205b4205adb950ce723d0826cc)](https://500px.com/photo/116373511/colorful-clouds-by-jan-bambach)

[![Lighthouse](https://drscdn.500px.org/photo/101898767/q%3D80_m%3D1500/80e742336eda2c62c9b61e08db77a573)](https://500px.com/photo/101898767/lighthouse-by-jan-bambach)

[![Bird is the word #2](https://drscdn.500px.org/photo/101897369/q%3D80_m%3D1500/231c0c246623b4507ddbaa1d6ea987d5)](https://500px.com/photo/101897369/bird-is-the-word-2-by-jan-bambach)
