### ISSUE TITLE
Fira font issues on Google Fonts

### ISSUE THREAD

**Issue by Mte90** [mozilla/OpenDesign#74]
## Goal:

Fira font update on Google Fonts CDn to improve the experience and use of that font in the many apps and websites that use it.
## Info:

Ref: https://github.com/google/fonts/issues/10
## The problem:

Google font use an old version of Fira font family that have rendering problems in many browser and situation meanwhile the Mozilla CDN version of the font don't have that problem.
The problem was reported on April 2015 and actually that font is not updated so it's impossible to use it with Google Font.
Ping on GitHub seems not enough to update only the files, now they update all the website and this situation create many problems during the development so we need a way to get this issue fixed.

**Comment by elioqoshi** [comment]
@mart3ll what do you suggest?

**Comment by svivian** [comment]
I've tried putting the files for Fira Sans through Font Squirrel's webfont generator, and they come out around 28kb which is better. Though there seems to be a problem with ligatures not displaying that I can't figure out. 

I think the main thing Google Fonts does is split the font into several character ranges and use the `unicode-range` property. This way most pages will only download a small subset of the font.

**Comment by Mte90** [comment]
Any update? Who can help us to speed that?

**Comment by Mte90** [comment]
There is also https://github.com/google/fonts/issues/155

**Comment by Mte90** [comment]
I written on IRC in #marketing to ask help, there is someone that we can contact to close this ticket?

**Comment by elioqoshi** [comment]
Any update on this? @Mte90

**Comment by Mte90** [comment]
I am following the google tickets, they done their fork of the font that fix the problem but not yet uploaded on google fonts.
There is the problem that the font is not maintained anymore and there no use in Mozilla like when there was for firefox.

**Comment by elioqoshi** [comment]
I see. closing this then.
