### ISSUE TITLE
Promote MDN plugin for WordPress

### ISSUE THREAD

**Issue by Mte90** [mozilla/OpenDesign#75]
## Goal:
- A new banner of size of 772x250px
- A new logo for that plugin (square)
- [Optional] https://developer.mozilla.org/en-US/promote multilanguage
## Info:

https://github.com/mdn/wp-promote-mdn
## Style Information:

MDN styles
## Deadline:

It is blocking for the next major version

**Comment by elioqoshi** [comment]
Taking this on.

**Comment by elioqoshi** [comment]
@Mte90 I'd need the source files. Can you track them down?

**Comment by Mte90** [comment]
Of https://developer.mozilla.org/en-US/promote? I have no idea where find it XD

**Comment by mart3ll** [comment]
They should be on the Mozilla asset repo.

On Monday, 20 June 2016, Elio Qoshi <notifications@github.com> wrote:

> @Mte90 <https://github.com/Mte90> I'd need the source files. Can you
> track them down?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/OpenDesign/issues/75#issuecomment-227237844>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGaShPxiste-zTUNdwaTGn37kwF3K3_dks5qNuRFgaJpZM4I59w_>
> .
>


-- 
*Sean Martell   *
 *Lead Creative, Brand*
*__________________________________________*
*+1-416-545-7724   |   blog.seanmartell.com <http://blog.seanmartell.com>
|   @mart3ll*

**Comment by mart3ll** [comment]
Oh, not those styles. Matt Ternoway has that artwork.

On Monday, 20 June 2016, Sean Martell <smartell@mozilla.com> wrote:

> They should be on the Mozilla asset repo.
>
> On Monday, 20 June 2016, Elio Qoshi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @Mte90 <https://github.com/Mte90> I'd need the source files. Can you
>> track them down?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mozilla/OpenDesign/issues/75#issuecomment-227237844>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AGaShPxiste-zTUNdwaTGn37kwF3K3_dks5qNuRFgaJpZM4I59w_>
>> .
>>
>
>
> --
> *Sean Martell   *
>  *Lead Creative, Brand*
> *__________________________________________*
> *+1-416-545-7724   |   blog.seanmartell.com <http://blog.seanmartell.com>
>   |   @mart3ll*
>
>

-- 
*Sean Martell   *
 *Lead Creative, Brand*
*__________________________________________*
*+1-416-545-7724   |   blog.seanmartell.com <http://blog.seanmartell.com>
|   @mart3ll*

**Comment by elioqoshi** [comment]
@mart3ll thanks, do you have a connection to him or should I drop him an email?

**Comment by Mte90** [comment]
any updates?

**Comment by Mte90** [comment]
Any updates?

**Comment by elioqoshi** [comment]
I have them, but I never had the time...

**Comment by Mte90** [comment]
Ok in any case the development actually it's blocked for missing of new features ideas.

**Comment by barrosgeraldo** [comment]
Ciao @Mte90, do you still need this banner and logo? I see that MDN is being redesigned, and maybe we can work together to create banners to promote the MDN and plugin. Let me know if the project is up, I would like to contribute since I use it on my blog too. 

Grazie,

**Comment by elioqoshi** [comment]
Let's close this and open a new issues when something specific is needed :)

**Comment by Mte90** [comment]
I have done a meeting the last week with the MDN people and there is a plan for the new version to release new banners with the new graphics but I will keep updated about it.
