### ISSUE TITLE
Logo and banner 

### ISSUE THREAD

**Issue by praveenbadami** [mozilla/OpenDesign#78]
We need a banner format and  logo for our workshop on   "mozilla web literacy" ...

The workshop is held on 15th July at Vijayapur - Karnataka  State( INDIA) 

Logo: Mozilla Vijayapur - Karnataka  State

Banner : A Workshop on 
 "web literacy "
15th july, 2016
Please see the attachments...the banner should be as per attachments...only title need to change
![banner of foss projects](https://cloud.githubusercontent.com/assets/16304257/16521234/2738f20a-3fb3-11e6-947f-c2bfbb0b281e.jpg)

**Comment by elioqoshi** [comment]
I see this has passed. Would be preferred if these requests would go a bit earlier in, now especially in summer as a lot of people are on vacations
