### ISSUE TITLE
Visual for RepsNext

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/OpenDesign#79]
## Goal: 
We would like to get a nice visual for the drawing in https://docs.google.com/document/d/1Xnf8daDl1OzuTvK14gxQKNxwv9ZFZ0PdG_1vaFVbgqA/edit?usp=sharing (attached below for clarity). Feel free to be creative, it doesn't need to look exactly like that as long as the meaning is still given.

![screen shot 2016-07-12 at 22 31 45](https://cloud.githubusercontent.com/assets/330324/16782560/70e863b0-4880-11e6-852e-cf7748d779eb.png)

## Info: 
We'll be using this in our blog post, you can find the draft here: https://docs.google.com/document/d/1Xnf8daDl1OzuTvK14gxQKNxwv9ZFZ0PdG_1vaFVbgqA/edit?usp=sharing

General outline for the picture: 

> With RepsNext there will be three different tracks to be specialized in: Leadership, Resources and functional areas. Every Rep will have a coach who has ideally run through the Leadership track to get specialized on leadership skills like personal development.  This enables the Reps program to have a synergy between the different tracks, and Reps from the Leadership track can help out other Reps even though they’re not their coaches but are knowledgeable in a certain area the Rep is interested in.

> For all inquiries for resources there is a specialized Review Team that will review the requests. To have a most efficient process there will be Reps that are part of this Resources track specialized in increasing the impact of activities that involve resources.

> Through this structure Reps from all specialization tracks can work together towards the overall Reps and Participation goals, each having their own piece of skill to bring Mozilla forward.

Further we have published a video introducing RepsNext if that is any help to come up with the visual: https://blog.mozilla.org/mozillareps/2016/06/16/repsnext-introduction-video/

This is part of https://github.com/mozilla/Reps/issues/9

## Style Information: 
Reps logo: https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/mozillareps/files/2014/04/cropped-Untitled.png

## Deadline: 
As soon as possible, best before July 17th

## Tag: 
[Design Needed]

**Comment by MichaelKohler** [comment]
Quick bump here, is there anyone interested in creating this visual? /cc @elioqoshi

**Comment by ioana-chiorean** [comment]
Also @yofiesetiawan has a nice input on this type of designs before. 
I can also help but with more like a sharp design ( not people, cute animals and flowers :| )

**Comment by yofiesetiawan** [comment]
![repsnext-diagram](https://cloud.githubusercontent.com/assets/2810823/17034566/6e30c84a-4fad-11e6-9414-2ff7d1e9d442.jpg)
I don't know if it's acceptable or not, just following the illustration...

**Comment by parag9d** [comment]
Made this based on the visual style of Reps logo: https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/mozillareps/files/2014/04/cropped-Untitled.png

Hope this is satisfactory...
![repsnext](https://cloud.githubusercontent.com/assets/6411097/17039529/92e0b118-4fb8-11e6-8c02-40ab2febfd26.png)

**Comment by parag9d** [comment]
@MichaelKohler Is the visual okay? Let me know...

High Resolution Image: https://www.dropbox.com/s/y8feksdnk9rr874/RepsNext.png?dl=0

**Comment by ioana-chiorean** [comment]
@parag9d - till @MichaelKohler  replies can u try sa version with another background color? i feel it is too much red. maybe gray?

**Comment by parag9d** [comment]
@ioana-chiorean @MichaelKohler Another version with grey background...

![repsnext-02](https://cloud.githubusercontent.com/assets/6411097/17082984/0b8f460a-51ae-11e6-80a1-746a143cfe5b.png)

**Comment by ioana-chiorean** [comment]
way more easy to read - 👍

**Comment by yofiesetiawan** [comment]
Now we have more new logos for each tracks :D

**Comment by elioqoshi** [comment]
They are not logos, but icons. Should be good to go. Thanks for chiming in!

I refer the one with the red background, but I'd suggest making the title boxes bigger and white (text should be red). Orange is pretty unrecognizable :)

**Comment by elioqoshi** [comment]
@MichaelKohler please try to keep at least 2 weeks buffer for requests, especially now in Summer time as people are on vacations. I hope we are not too late for this though.

**Comment by elioqoshi** [comment]
@parag9d also please share source files :)

**Comment by MichaelKohler** [comment]
I really like the one with the gray background, thanks!

Maybe @nukeador wants to give his feedback here as well?

**Comment by nukeador** [comment]
Hello,

Quick feedback: I like the overall design.

Some questions:

* Coach is more a guide than a trainer, is the whistle the best icon?
* The Council icon is not linked with anyone. Maybe linked to the Reps one?
* Who are we referring with the "Leadership team" icon?

Thanks for the good work!

**Comment by hmitsch** [comment]
What about one of there for the "**Coach**"?
- https://thenounproject.com/term/coaching/66723/
- https://thenounproject.com/term/leadership/544631/
- https://thenounproject.com/term/teamwork/215991/

What about changing the perspective of **Leadership** to something like this?
- https://thenounproject.com/term/helm/163872/

**Comment by elioqoshi** [comment]
I think a Torch icon would be best for Coach.

@MichaelKohler the gray background doesn't feel like Reps that much really :) Red works better here (with some adjustments of the elements of course).

**Comment by parag9d** [comment]
As I had mentioned earlier the red and yellow colour scheme is based on the visual style of Reps logo: https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/mozillareps/files/2014/04/cropped-Untitled.png & some visual cues from the introductory video

So, even I guess the red one is more in sync with the RepNext Branding. But we can tweak it a little, based on the requirements. I will upload the source file in the repo.

**Comment by elioqoshi** [comment]
@parag9d Thanks! The orange is only part of the gradient I think. I haven't seen it as a solid color at Reps, hence I mentioned that. Do you have write access to the repo?

**Comment by parag9d** [comment]
I used the yellow/orange shade from the focused text colours used in the introductory video here: https://blog.mozilla.org/mozillareps/2016/06/16/repsnext-introduction-video/.

I don't know if I have the write access, but I had uploaded the Mozilla Hyderabad Logo earlier. How do I check the access status?

**Comment by elioqoshi** [comment]
You have write access, should be good to go

**Comment by MichaelKohler** [comment]
@elioqoshi 

> I think a Torch icon would be best for Coach.

Could you elaborate on this? For me a torch would be "follow me, I lead you through the darkness". While the darkness part is nice, I don't think we want to have a followers perspective here, but more like teamwork.

> @MichaelKohler the gray background doesn't feel like Reps that much really :) Red works better here (with some adjustments of the elements of course).

If red works better and you'd recommend this from a design point as well, we could definitely go with red based on a design standpoint :)

**Comment by parag9d** [comment]
Source files uploaded here: https://github.com/mozilla/OpenDesign/tree/master/RepsNext%20Blog%20Visuals

**Comment by elioqoshi** [comment]
@MichaelKohler You are right. Anyway here is the version I suggest (I changed the leadership icon)
![repsnext-01](https://cloud.githubusercontent.com/assets/5436686/17271355/a5a7abea-5679-11e6-83fc-0368d7e62ebf.jpg)

**Comment by MichaelKohler** [comment]
Thanks! Could we somehow make the Council icon position (or make lines or whatever) to say that Council will focus on the strategy of all these? Currently it's on the top, but seems quite displaced. Any ideas?

**Comment by elioqoshi** [comment]
@MichaelKohler how about this?
![repsnext-01](https://cloud.githubusercontent.com/assets/5436686/17275028/04b5d8b6-56fa-11e6-9d33-296f82b352a2.jpg)

**Comment by MichaelKohler** [comment]
Thanks Elio, I like it. @nukeador do you have any other input?

**Comment by hmitsch** [comment]
@MichaelKohler I also really like it! In my opinions it captures the current state of affairs quite well. What I like best is the big dotted frame created by the Council. Well done @elioqoshi and team!

**Comment by nukeador** [comment]
For me having a red background with red icons make it extremely difficult to read, I feel it's hard for people with visual problems to read.

* "Leadership team" is not clear what's referring to, maybe "leadership training is more clear".
* "Coach/ing" maybe should be linked to goals too.

**Comment by MichaelKohler** [comment]
> For me having a red background with red icons make it extremely difficult to read, I feel it's hard for people with visual problems to read.

Henrik and I have written text to explain it, that should be fine (see https://docs.google.com/document/d/1Xnf8daDl1OzuTvK14gxQKNxwv9ZFZ0PdG_1vaFVbgqA/edit?usp=sharing)

> "Leadership team" is not clear what's referring to, maybe "leadership training is more clear".

Fair point, this might actually just be "Leadership" if we want to be consistent in naming (see "Resources" and not "Resources Team"). Or we add "track" to both of them which makes it more complex.

> "Coach/ing" maybe should be linked to goals too.

Every coach is a Rep by itself as well, and therefore connected to the goal individually. I don't think we need to specifically link this to the goals.

**Comment by hmitsch** [comment]
Nice discussion. All of @nukeador's points seem reasonable to me. Not sure if we should take action on all of them.
- Red color: for sake of accessibility, the picture is described in words in the text below the picture. The design experts advised to use red color. I am bad at these things, so I'd go with the designers' suggestions. 
- +1 to the consistent naming. Not sure which parts need changing. @michaelkohler, can you take care of that?
- Linking coaching to goals: I am not sure if this really needs linking? Most of the time it will be linked, but there might be instances where it is not. I'd suggest to take the approach which allows for the lowest amount of visual complexity.

**Comment by MichaelKohler** [comment]
Thanks Henrik, since I'd love to get this blog post out of the door as quick as possible, @elioqoshi could you please change "Leadership Team" to just "Leadership"?

Thanks everyone who was involved here, great to have design resources at disposal to make it the best out of it!

**Comment by MichaelKohler** [comment]
After discussing this with a few others, could you please also change the background to something that gives it more contrast so it is easier for people with disabilities to see? After that and the change to "Leadership" we're set! Thank you for your effort, greatly appreciated

**Comment by elioqoshi** [comment]
@MichaelKohler Sorry for the delay, I was outside country for a conference.

Here we go :)
![repsnext-01](https://cloud.githubusercontent.com/assets/5436686/17560005/9e6256a0-5f20-11e6-9ffa-16a57acc03a2.jpg)

**Comment by MichaelKohler** [comment]
Perfect, thanks a lot!
