### ISSUE TITLE
Mozilla India Meetup 2016

### ISSUE THREAD

**Issue by prathameshchavan** [mozilla/OpenDesign#80]
## Goal: 
The Mozilla India Community has organized a Mozilla India Meetup 2016. Over 100 participants would be joining this gathering. The goal is to create a logo for the meetup which would be a mix of text and graphics and could be used as a design for printing laptop stickers.

## Info: 
The design would be used in all the activities under the Mozilla India Meetup 2016. It would be used in online posts and printing laptop stickers.

## Style Information: 
The design must contain the following details:
- A text 'Mozilla India Meetup 2016 - Pune, India'. The font of 'Mozilla India Meetup 2016' could be large as compared to 'Pune, India'.
- It should include a graphic of 'Shaniwar Wada' which is a historic monument and a well known feature associated with the Pune City. 
Image link:http://images2.fanpop.com/image/photos/12400000/shaniwarwada-pune-city-puneites-12473759-1600-1200.jpg
- Circular in shape

## Deadline: 
15th August 2016

## Tag: 
[Design Needed]

**Comment by ioana-chiorean** [comment]
> The goal is to create a logo for the meetup which would be a mix of text and graphics and could be used as a design for printing laptop stickers.

a logo or a design for tshirt? Mozilla India already has a logo ( nice one even)

**Comment by prathameshchavan** [comment]
We are looking for a logo which would be specific to the Mozilla India Meetup 2016.
Tshirt design would be different.

**Comment by elioqoshi** [comment]
Thanks for requesting @prathameshchavan ! We will get back very soon with updates on this.

Can you send us the Mozilla India logo in vector format?

**Comment by thomasjosephgreco** [comment]
@prathameshchavan wanted to ping you as I just spent some time speaking with @elioqoshi on this task and am happy to work with him on completing it 😄 Will be chatting with Elio more about this shortly... Excited to begin putting this together !

**Comment by elioqoshi** [comment]
Perfect! Happy to see Tom onboard!

**Comment by geroter** [comment]
Wanted to chime in here.

A major theme of this meetup is refreshing, rebirth, recommitment,
rebooting...it's aiming to mark the beginning of the next phase of Mozilla
India.

If the graphic could reflect this theme, that would be amazing!

On Jul 25, 2016 08:11, "Tom Greco" <notifications@github.com> wrote:

@prathameshchavan <https://github.com/prathameshchavan> wanted to ping you
as I just spent some time speaking with @elioqoshi
<https://github.com/elioqoshi> on this task and am happy to work with him
on completing it 😄 Will be chatting with Elio more about this shortly...
Excited to begin putting this together !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/OpenDesign/issues/80#issuecomment-234848494>,
or mute the thread

**Comment by elioqoshi** [comment]
Thanks George, we will keep this in mind

**Comment by prathameshchavan** [comment]
I thank you so much @ioana-chiorean @elioqoshi @thomasjosephgreco for helping us with the graphics. 

As @geroter said, this meetup will mark a new beginning for Mozilla India. Also, since it is happening in Pune, we are very much keen on giving it a Pune touch by adding some graphics which are associated with Pune. 

Shaniwar Wada is a historic monument located in the heart of the city and so, if you guys could add a graphic featuring Shaniwar Wada then that would be great. Check this out: https://openclipart.org/image/2400px/svg_to_png/215160/shaniwarwada.png

@elioqoshi Here is the Mozilla India logo in vector format https://drive.google.com/open?id=0B9I8V40G7rztRG05RFYtN2UxaVE


Just for reference, the logo of the Mozilla India Community Meetup 2014 which had happened in Hyderabad https://wiki.mozilla.org/images/6/60/Mozilla-India-Meetup-Hyderabad.png 
It fetaures Char Minar, the historic monument in Hyderabad.

**Comment by umeshagarwal** [comment]
@elioqoshi did you got a chance to work on this? I am pushing this as the event is approaching and  we need to print them as well. 

Regards
Umesh Agarwal

**Comment by parag9d** [comment]
I am almost done with the Shaniwar Wada illustration. Will post the sticker design hopefully by tonight. Using a rising sun in the sky to depict the rebirth/recommitment theme...

**Comment by tripad** [comment]
@prathameshchavan Where exactly do you plan to use this logo ? 
Is this going to be used on any kind of swag - like stickers, tshirt etc ?

**Comment by thomasjosephgreco** [comment]
@tripad just to be sure, I am still working on this logo correct ? I was about to work on an Shaniwar Wada illustration but I want to make sure that I am all good to go

**Comment by parag9d** [comment]
@thomasjosephgreco Don't worry about it, I am done with the illustration, will be posting in some time.

**Comment by thomasjosephgreco** [comment]
@parag9d alright so what will we be using that illustration for? If you can check out the thread you'll see that this is something that @elioqoshi and I spoke about doing so which is why I believe @tripad asked where this logo plans to be used?

**Comment by prathameshchavan** [comment]
@tripad The logo would be used in printing stickers which could be pasted on the laptop cover. The design would be circular just like any other Mozilla stickers. We dont want any design for the tshirts.

**Comment by prathameshchavan** [comment]
I am very much clear with the logo plans as in where it would be used. Kindly refer the above threads for specifications.
@parag9d Waiting for your design :)

**Comment by thomasjosephgreco** [comment]
@prathameshchavan just to be sure, is this still something that I am working to create ? I would definitely like to help out but I think I am getting a bit confused. Will I be incorporating @parag9d's design into the logo ? my apologies for the confusion 😄

**Comment by parag9d** [comment]
@thomasjosephgreco I will post the entire logo & the sticker design. If there are any changes/improvements needed you can add to it :)

**Comment by prathameshchavan** [comment]
@thomasjosephgreco Hey! No problem :)
As per my understanding, you and @elioqoshi are working together. That logo idea would be yours and anything that you guys discuss and create together. 
Meanwhile, @parag9d is working on his idea. If he is done with his logo design, then you and @elioqoshi can suggest some changes or come with your own new design altogether. :)

**Comment by parag9d** [comment]
Shaniwar Wada Illustration:
![mozilla india meetup 16-01](https://cloud.githubusercontent.com/assets/6411097/17258544/14da0c28-55e5-11e6-9854-ef57e8b59564.png)

Mozilla India Pune Meetup Sticker:
![mozilla india meetup 16-02](https://cloud.githubusercontent.com/assets/6411097/17258565/2b17ac70-55e5-11e6-955f-9fd5d8efbad0.png)

I will upload the source file and the associated assets soon...

**Comment by prathameshchavan** [comment]
@parag9d 
Some addition:
- Kindly add the text 'Meetup'

**Comment by parag9d** [comment]
@prathameshchavan Check this, let me know if there is anything else. I will do them tomorrow, signing off for tonight. Good night everyone :)

![mozilla india meetup 16-02](https://cloud.githubusercontent.com/assets/6411097/17258979/08df89d2-55e7-11e6-8940-c34126d9cf33.png)

**Comment by prathameshchavan** [comment]
@elioqoshi @thomasjosephgreco Do you guys have any suggestions on @parag9d 's design? Or are you creating an altogether new logo?

**Comment by umeshagarwal** [comment]
Good work! 
Can we accommodate event name "Mozilla India Meetup 2016 - Pune" in this ?

**Comment by prathameshchavan** [comment]
@parag9d Can you create one more image with text 'Meetup 2016 Pune' instead of 'Meetup Pune'16'.
i.e.
2 images:
1) As above
2) With text 'Meetup 2016 Pune' replacing 'Meetup Pune'16'

**Comment by parag9d** [comment]
![mozilla india meetup 16-02](https://cloud.githubusercontent.com/assets/6411097/17267782/4d0d371e-5630-11e6-87a4-22036fa737c8.png)

**Comment by prathameshchavan** [comment]
@parag9d Thanks! :)

**Comment by elioqoshi** [comment]
Looking really solid! Can you please attach the source files here so we can try some tweaking? Thanks!

**Comment by parag9d** [comment]
@elioqoshi Done. Uploaded here: https://github.com/mozilla/OpenDesign/tree/master/Mozilla%20India%20Meetup%20'16%20-%20Pune

**Comment by elioqoshi** [comment]
![mozilla india meetup 16-02](https://cloud.githubusercontent.com/assets/5436686/17269510/c46994fa-564a-11e6-8668-4e4a2fb55dca.png)

Added some border, tweaked the colors and also fixed the meetup title as requested. What do you think?

**Comment by umeshagarwal** [comment]
Thanks everyone the final one looks good and perfect for making stickers.

Regards
Umesh Agarwal

**Comment by umeshagarwal** [comment]
@elioqoshi Can you share the high resolution file which can be send for printing ?

**Comment by parag9d** [comment]
@elioqoshi Now that there is a border, maybe you can utilise the same and increase the size of the texts. Also, the white outline of the border is visible just below the text, can you do something about it? Thanks.

Convert the RGB file to CMYK and remove the white background from the artboard. Then export the PNG file. Good job everyone 👍

**Comment by elioqoshi** [comment]
Sure, confirming here, good to go?
![sticker-02](https://cloud.githubusercontent.com/assets/5436686/17270220/53e21536-565e-11e6-9422-53d4ea79c0ab.png)

**Comment by umeshagarwal** [comment]
Yes this is good!

**Comment by prathameshchavan** [comment]
Perfect!
Thank you so much everyone! \o/

**Comment by elioqoshi** [comment]
There we go!
https://github.com/mozilla/OpenDesign/tree/master/Mozilla%20India%20Meetup%20'16%20-%20Pune

Good luck with the event!
