### ISSUE TITLE
MozItalians - Italian Participation Team

### ISSUE THREAD

**Issue by Mte90** [mozilla/OpenDesign#81]
## Goal: 
A logo, badge style like FSA, for the Italian Participation Team to use for swag and promotion.

## Info: 
In the logo it's important to have an Italian symbol to get easily reconize or references like the flag colors.

## Style Information: 
The Mozilla Italia logo is https://www.mozillaitalia.org/home/wp-content/themes/mozillaitalia/immagini/header_logo.png, for us it's not a problem to not use the same images but similar color (the blue) will be perfect.
In case think a version with the term MozItalians will be useful for other type of promotion.

## Deadline: 
For 20 August if possible

Ref: @Mte90, @edovio

**Comment by elioqoshi** [comment]
Daniele, what will you be using this for? As I said, no logos for smaller projects as that goes against the new branding guidelines. We can make graphics for specific swag or mediums however.

**Comment by Mte90** [comment]
We will use for our participation team that is growing very fastly.
We need a different logos, also similar to the community one, only for
promotion and swag.
For promotion I mean slides, meetup, social and internal things.

**Comment by elioqoshi** [comment]
Sorry but we cannot do that. As I said, feel free to use your community logo with a subtitle (Participation) but we are not creating new logos for projects of this scale.

**Comment by Mte90** [comment]
Ok thanks for the support :-)
