### ISSUE TITLE
B2G OS Logo 

### ISSUE THREAD

**Issue by kskarthik** [mozilla/OpenDesign#82]
## Goal: 
We need a logo for B2G OS 

## Info: 
I made a transparent bg image from the existing one i found using gimp. Please convert it to vector (.svg) & add detail to it. I tried using Inkscape but i'm not expert in it. 

## Deadline: 
One month (flexible)

## Tag: 
[Design Needed]

![b2gcut](https://cloud.githubusercontent.com/assets/11899221/17167146/1f96c6f8-53f9-11e6-8214-401476ec039f.png)

**Comment by elioqoshi** [comment]
Sorry, I don't think this is relevant and we should not be focusing our efforts on recreating a logo. @mart3ll also advised not to use it again as it's outdated. Who is leading B2G OS? We just cannot create a logo and afterwards see it rejected on official channels.

**Comment by parag9d** [comment]
@elioqoshi Exactly, this is what I was also concerned with. We can probably redesign the logo if the official channel decides so.

**Comment by geroter** [comment]
Quick Context:

B2G OS isn't an official Mozilla project anymore. So moving forward the
"official channel" is the community of people/contributors/volunteers who
are passionate about this project.

You may still decide that it isn't a good use of this group's time to help
out with a logo for the project. @elioqoshi and others can vote with your
feet :)

**Comment by elioqoshi** [comment]
@geroter Makes sense, but even for the community group, there needs to be some kind of consensus. If there will be some coordinated request, and we can be sure that the logo will be put to good use, we can do that, of course.
