### ISSUE TITLE
Generalize l10n hackathon design resources

### ISSUE THREAD

**Issue by gueroJeff** [mozilla/OpenDesign#83]
## Goal:

We'd like to use these design resources for future l10n hackathons without needing to request changes for each one. We'd like the resources to be generalized so that we can print them in bulk, once, without needing customization.
## Info:

It will be used for future l10n hackathons organized by the l10n-drivers.
## Style Information:

https://github.com/mozillaslovenija/Design/tree/master/L10n%20hackathon%20Ljubljana%202016
## Deadline:

By 19 August, in time for us to print these out and have them ready by our Asian hackathon on 27-28 August.
## Tag:

[Design Needed]

**Comment by elioqoshi** [comment]
@gueroJeff I'm really really sorry but I had to run for a conference I am speaking at in Germany. I can prepare the files for 23rd August as I don't have the right tools with me here. Really really sorry again, can you deal with a 4 day extension?

**Comment by gueroJeff** [comment]
@elioqoshi That's no problem. We won't be able to use these for the hackathon happening this weekend, but we would still be able to use them for the final 3 of the year. Thank you

**Comment by elioqoshi** [comment]
![name badge-01](https://cloud.githubusercontent.com/assets/5436686/18784192/d286e18e-8190-11e6-80c3-7466dd4d7ee7.jpg)
![name badge-02](https://cloud.githubusercontent.com/assets/5436686/18784193/d2b3d298-8190-11e6-9595-2597118318c9.jpg)

Terribly sorry, that's what happens when you don't do stuff right away. Here are the name badges:
https://github.com/mozilla/OpenDesign/tree/master/l10n-Event-Resources

Are there other templates needed?

**Comment by gueroJeff** [comment]
Thanks @elioqoshi ! The photo frame and medallion would be great too.

**Comment by elioqoshi** [comment]
@gueroJeff Hey, just saw this (traveling in the US currently)

I haven't created them but I can ask the Slovenian guys about them

**Comment by gueroJeff** [comment]
Thanks @elioqoshi !

**Comment by gueroJeff** [comment]
Hey @elioqoshi , now that there's new Mozilla branding, could we get updated name badges? Even if it was just with the "m" lettermark (can't bring myself to call a letter a wordmark). We have a workshop at the end of this month that we'd like to use them for. Thank you!

**Comment by elioqoshi** [comment]
@gueroJeff I think that's possible. When do you need to print? Can you wait until Zilla is out on 17th April?

**Comment by peiying2** [comment]
@elioqoshi, I need it for our Taipei event coming up later next week.  It will be very tight.  I am leaving on April 19th.

**Comment by elioqoshi** [comment]
I can finish this by this weekend. Just please ping me again in 2 days so I dont forget :)

**Comment by peiying2** [comment]
Thank you.  Will do!

**Comment by peiying2** [comment]
@elioqoshi, could you update me on the status?

**Comment by elioqoshi** [comment]
![draft](https://cloud.githubusercontent.com/assets/5436686/25024845/fa030f36-209f-11e7-88e0-8234e8558314.jpg)

So you only need name badges right now? We can do these with the new wordmark (without icon yet)

**Comment by peiying2** [comment]
What icons are you referring to? The l10n head?  It would fill up the space a bit or the badge looks almost empty for now.

**Comment by elioqoshi** [comment]
Yeah sorry I cannot do that as it's old branding.

**Comment by peiying2** [comment]
Do you know when the replacement is ready?  Next few days or in a few weeks?

**Comment by gueroJeff** [comment]
I think the wordmark is fine for our purposes.

**Comment by elioqoshi** [comment]
Pretty sure not within this month :)

I will export you the name badges

**Comment by peiying2** [comment]
thanks so much!

**Comment by gueroJeff** [comment]
Thanks Elio!

**Comment by elioqoshi** [comment]
![2](https://cloud.githubusercontent.com/assets/5436686/25026075/23764e32-20a5-11e7-9640-8d6f03d90ece.jpg)

Like this? :)

**Comment by elioqoshi** [comment]
![2](https://cloud.githubusercontent.com/assets/5436686/25026266/07dbba26-20a6-11e7-8668-d06bf1532220.jpg)

Or maybe an alternative version

**Comment by peiying2** [comment]
Elio, these look great!  I like the blue one just a tad more, 👍

**Comment by elioqoshi** [comment]
@peiying2 @gueroJeff there we go:
https://github.com/mozilla/OpenDesign/tree/master/2017/Swag&Printouts/l10n%20nametags

**Comment by gueroJeff** [comment]
Thank you so much!

**Comment by peiying2** [comment]
@elioqoshi everyone in Taipei loved the design of the badge, ^-^!  Thank you very much!

**Comment by elioqoshi** [comment]
Great to hear! My pleasure!
