### ISSUE TITLE
An A4 size design for front side of T-Shirt Activate Mozilla Community. 

### ISSUE THREAD

**Issue by umeshagarwal** [mozilla/OpenDesign#86]
## Goal:

An A4 size design for front side of T-Shirt Activate Mozilla Community. 
A work mark logo for backside neck of T-Shirt  "Activate Mozilla Community" 
https://activate.mozilla.community
## Info:

It will be used as a swag for events happening in India.
## Style Information:

It should follow the Mozilla Style guide and should reflect (Activate Mozilla Campaign + India). Basically a localised design for Indian audience to describe Activate Mozilla Community. 
https://activate.mozilla.community
## Deadline:

By 11 September as this is kind of urgent. 
## Tag:

@parag9d @brianking @elioqoshi

**Comment by parag9d** [comment]
@Raphseck Would you like to take this up? Your illustrations are awesome and will look superb on the t-shirt :)

**Comment by umeshagarwal** [comment]
Any update on this request ? @parag9d @Raphseck

**Comment by parag9d** [comment]
@umeshagarwal This design would be fine if you are going for digital print for the t-shirts, but if you are planning for screen printing, I'll need to reduce the colours or make a different design. Lemme know...
![activate mozilla tshirt-01](https://cloud.githubusercontent.com/assets/6411097/18336924/73f1273a-75a9-11e6-9164-7b10e1751377.png)
![activate mozilla tshirt-02](https://cloud.githubusercontent.com/assets/6411097/18336925/742a5d52-75a9-11e6-8d56-be2ebf2768a0.png)

**Comment by umeshagarwal** [comment]
@parag9d we will be doing digital print so this is fine. Overall design looks good to me.

@brianking can you do a review as we need to get this produced soon.

**Comment by parag9d** [comment]
@umeshagarwal The black version of the t-shirt...
![activate_black](https://cloud.githubusercontent.com/assets/6411097/18417990/ab7e5010-785b-11e6-9431-43bde98ea42d.jpg)

**Comment by parag9d** [comment]
@umeshagarwal The source files of the design are here: https://github.com/mozilla/OpenDesign/tree/master/Activate%20Mozilla%20Tshirt%20Design

**Comment by elioqoshi** [comment]
Good one! As I said, we shouldn't rush things out like this, especially on such important campaigns. Let's take our time and review together through it. @brianking let's talk about the incorporation of these assets globally.

**Comment by Raphseck** [comment]
Hey guys!
SORRY about that..
I'm having problems with git hub... but i created a filter now for it.
SORRY : (
I just saw the email now : /

**Comment by umeshagarwal** [comment]
I will have to go with the current design for events in India as we need time for production and we are already late. But if there is a need for global level design the you can use this design request for the same purpose..
