### ISSUE TITLE
Firefox Security (FoxSec) logo

### ISSUE THREAD

**Issue by jvehent** [mozilla/OpenDesign#87]
## Goal:

I'd like a logo for the Firefox Security teams (nicknamed FoxSec) that includes the Security Engineering (crypto, privacy, ...) and Cloud Security (Fxa, Sync, AMO, ...) teams.
## Info:

The logo will be used on the web (wiki, etc...), stickers, and maybe tshirts.
## Style Information:

I really like the [Firefox Robin Hood](https://ulfr.io/f/IMG_20160925_155054.jpg) logo. Something along these lines that carries the idea of security, privacy, cryptography and overall safety would be very nice. Maybe a Fox Gatekeeper, master of the keys, etc...

Matrix-like colors (green front with black background) are often associated with hacking and security. That might be an idea, but I'm not 100% sold on it (it's very cliche). I think keeping the usual Firefox orange and blue colors may be nicer.
## Deadline:

End of october, to print stickers for Hawaii.
## Tag:

Design Needed

**Comment by jonathanKingston** [comment]
@jvehent is there a way for me to get hold of said robin hood logo files? (being from nottingham this is amazing!)

**Comment by jvehent** [comment]
I wish I knew who made it. I found the sticker somewhat randomly at mozlando.

**Comment by elioqoshi** [comment]
Hey @jvehent thanks for requesting this!

I need to let you know that we do not create logos for teams within Mozilla within our new branding strategy. We will be able to create a wordmark for you though (FoxSec probably not due to it not being consistent and having a name as if is a product).

We will be able to create artwork as well for Stickers and other swag (but not stating it as a logo so to speak).

@mart3ll can give more details on that as well

**Comment by jvehent** [comment]
Thanks @elioqoshi ! I'll be happy with a cool looking sticker, I don't think our team needs an official logo to use in external communication or anything like that. We use the standard Mozilla design in the security blog and on our wiki pages.

**Comment by jvehent** [comment]
Does anyone have time to work on this? I'm not sure what the correct process is here, and I absolutely understand it's best effort, but I thought having something for Hawaii would have been cool.

**Comment by andrralv** [comment]
I can/will. Hopefully we can get a few design submissions and choose
whatever looks nicer for everyone.

2016-10-25 16:17 GMT-03:00 Julien Vehent [:ulfr] <notifications@github.com>:

**Comment by elioqoshi** [comment]
I would love to help here, but the next weeks are really booked for me. @parag9d can you help here?

**Comment by parag9d** [comment]
Hey, @elioqoshi  I am caught up with Testpilot work currently, but @radhika1210 is willing to take up this project. She is a new contributor and this is gonna be her first Mozilla project. Check out her works at https://www.behance.net/RadhikaGemawat. @jvehent, please coordinate with her on this :)

**Comment by Aastha14** [comment]
![final foxsecgradients](https://cloud.githubusercontent.com/assets/20784948/20015335/1700590a-a2e1-11e6-9e77-375652bbdd50.jpg)

This is something I tried, please see if it works. Also, let me know if any changes are required too!

**Comment by Aastha14** [comment]
![png with back foxsec](https://cloud.githubusercontent.com/assets/20784948/20015466/a03e47ae-a2e1-11e6-943d-bfd60fa3334c.png)

@jvehent here is something I tried, couldn't come up with the robin hood of course, but I tried to portray our beloved Foxy as the agent of Mozilla who works and supports security. Please, comment and let me know if any changes are required. :)

**Comment by mijanurrahman** [comment]
Thanks @Aastha14 . You did well (y)
But please try to follow Mozilla Style Guide (https://www.mozilla.org/en-US/styleguide/)

Though I am not a designer, but I am suggesting all of to you make something which represents something secure and unhackable.

**Comment by Aastha14** [comment]
@mijanurrahman As far as the sticker is concerned, I guess there is a style guide for official Logos. Whereas, its not the same for stickers (Please correct me if I'm wrong). Also, Thankyou.

**Comment by dyvik100** [comment]
@Aastha14 Great job (y) it's looking great. As far as i know there is no style guide for stickers, so need not worry about it.

**Comment by jvehent** [comment]
@Aastha14 I like it a lot! The fox looks great. I wonder if the green would look better a little darker?
One question about the hat is if we want to be portrayed as police/security officer. Maybe it's alright? Maybe we could try with another type of hat, like a [ranger one](https://arches.files.wordpress.com/2012/08/img_0606.jpg)?

At any rate, this is awesome! Thanks a lot for designing it!

**Comment by Aastha14** [comment]
@jvehent Yes, I shall make the required changes and get back in few hours. No issues, as I should deliver what's required. :)

**Comment by Aastha14** [comment]
![foxsecjvehent](https://cloud.githubusercontent.com/assets/20784948/20028643/aa4c313a-a35d-11e6-9af9-fa31581b96cc.png)
looks good enough?

**Comment by jvehent** [comment]
I think I liked the lighter green one better after all. Maybe others could share their opinion too?
@Aastha14: what do you think of the hats?

**Comment by ST6Daniel** [comment]
I like the Sheriff hat, what about using blue color somewhere in the shield?

**Comment by Ryuno-Ki** [comment]
Hm, there's something with the eyes … maybe the shadow below it? Is he tired?

The skin looks like as if there was some kind of wind (blowing from the left to the right). Maybe the hat can reflect that, too?

**Comment by Aastha14** [comment]
Was just playing around with shadows not trying to make him look tired, ofcourse. Regarding the hat,  maybe I'll try to make some changes.  @jvehent guess I liked the hat, do you have any more ideas? 
Regarding the blue color, I'm not sure where shall it fit in,  though I will try it on.

**Comment by jvehent** [comment]
I really like both, to be honest. @Aastha14: I'm inclined to trust your artistic judgment on which adjustments look best.

**Comment by Aastha14** [comment]
@jvehent,  let's go forward with the fox and the ranger hat ? I like both the colours, be it the lighter green or the darker one. I'll share the source files soon. Incase you change your mind during the print, you may get it changed. :) thankyou.

**Comment by jvehent** [comment]
That works for me. Would the ranger hat look better if it was a tiny bit smaller? How about adding the Firefox Logo to it, like you did on the cop hat? I'm wondering, not sure if that would look good.

**Comment by Aastha14** [comment]
@jvehent I tried on the Mozilla Logo on the sheriff hat, doesn't look that good. I'll try posting a picture of the same, making the hat little bit smaller doesn't go appropriate for the size of the fox head. If this doesn't work out, why not go with the 1st option?

**Comment by jvehent** [comment]
Hello @Aastha14, did you, by any chance, have time to make these little adjustments?

**Comment by Aastha14** [comment]
Yes, I did make the changes @jvehent But I'm unable to upload the files, because I don't have the access. Shall I mail you the file until then? @elioqoshi please enlighten me on this.

**Comment by jvehent** [comment]
You could email them to me at jvehent at mozilla dot com
Thank you!

**Comment by Aastha14** [comment]
@jvehent I've mailed it to you, though a little too late I suppose. Apologies.

**Comment by jvehent** [comment]
I have received the files. Thanks a lot @Aastha14 !

**Comment by elioqoshi** [comment]
I would suggest to keep working on the sticker a bit, it's quite off from Mozilla style guidelines :)
If you link to it here I can give it a look.
