### ISSUE TITLE
Upload Innovation Toolkit postcards from MozFest

### ISSUE THREAD

**Issue by hmitsch** [mozilla/OpenDesign#89]
## Goal: 
Upload the (beautiful!) **Innovation Toolkit postcards** which were handed out at MozFest 2016 to a public repo. This way they can be **remixed in the future**.

## Info: 
Let's create a new folder **Open-Innovation-Toolkit/Leaflets/**

## Style Information: 
n/a

## Deadline: 
Overdue (should have happened before or during MozFest)

## Tag: 
Info

## Other information: 
Collaborating on this with @ivonnekn, @flekkowich and @elioqoshi.

**Comment by hmitsch** [comment]
Done: https://github.com/mozilla/OpenDesign/tree/master/Open-Innovation-Toolkit/Leaflets

**Comment by ioana-chiorean** [comment]
Thanks @hmitsch !
