### ISSUE TITLE
Logo for Leadership Toolkit

### ISSUE THREAD

**Issue by emmairwin** [mozilla/OpenDesign#90]
## Goal: 
A logo for the Leadership Toolkit.
We're forking the Innovation Toolkit website, so something to replace theirs:   https://toolkit.mozilla.org/

## Info: 
On a wordpress fork of Innovation Toolkit

## Style Information: 
Content is learning resources for  community mobilizers.

## Deadline: 
December 3rd

## Tag: 
[Design Needed]
I might also need some wordpress theming support but not sure yet.

**Comment by parag9d** [comment]
Hi, @emmairwin...this project looks really cool. Is the new website design already done?
If not, I would like to help in that :)

**Comment by elioqoshi** [comment]
I can take this on

**Comment by emmairwin** [comment]
@parag9d I need the logo, but I'll also need to make the fork look like...not a fork, so will need to change some design components.
This is to demo our toolkit content in Hawaii, whether or not it persists into 2017 will be another decision, so I don't want to take your time doing a lot of design work, other than I need help to make the fork unique.  Instance will be ready on Friday.

**Comment by emmairwin** [comment]
Thanks @elioqoshi

**Comment by amadejhp** [comment]
Is logo still needed? Or only that fork thing? Would it be good logo to make it look like tool  box with something more specificly related to this project on it?
(I am a bit new here, so I'm sorry if I'm doing something wrong).

**Comment by elioqoshi** [comment]
@amadejhp thanks for asking, and no worries :)
I had a go at this but wasn't satisfied. Feel free to suggest alternatives

**Comment by amadejhp** [comment]
I've put aside that toolbox design and created this: (a bit separated icons, but maybe it could be an inspiration...)

![toolbox2](https://cloud.githubusercontent.com/assets/25230774/22163188/1531c55c-df52-11e6-810c-864efb167873.jpg)

**Comment by barrosgeraldo** [comment]
Closing, since I talked to Emma today and the project is stopped for now.
