### ISSUE TITLE
Logo for @intenttoship Twitter account

### ISSUE THREAD

**Issue by autonome** [mozilla/OpenDesign#91]
## Goal: 

The intenttoship Twitter account will automatically tweet any time Gecko or Blink announces a new feature shipping in their web engines.

I would like a logo and background image for that Twitter account 😀

## Info: 

https://twitter.com/intenttoship

## Style Information: 

Here are some reference designs related to generally-web-like things, and both of the rendering engines

http://www.webstandards.org/
https://www.w3.org/
http://webfoundation.org/
https://developer.mozilla.org/en-US/docs/Mozilla/Gecko
http://www.chromium.org/blink

## Deadline: 

No hurry!

## Tag: 
[Design Needed]

**Comment by andrralv** [comment]
Here's a first try for the logo: [image](http://i.imgur.com/I2y1Juu.png)

It's a simple logo, the concept is that colors correspond to an alert or notification.

**Comment by autonome** [comment]
Hi André, thanks for the design! I specifically want something that conveys
"web" not a specific browser. This idea is that this isn't about Firefox,
this is about web developers knowing what's coming soon to all the browsers.

**Comment by elioqoshi** [comment]
@parag9d you have time for a proposal for this?

**Comment by barrosgeraldo** [comment]
@autonome do you still need this logo?

**Comment by autonome** [comment]
I'd love a better logo, yes :D

**Comment by elioqoshi** [comment]
Revitalizing this, very sorry about that, we are spread too thin.

**Comment by AnXh3L0** [comment]
Hi @autonome, I created an icon and a header image for the twitter account. Have a look below, comments are welcome :)

![header_twitter](https://user-images.githubusercontent.com/25004151/32720029-9e890956-c862-11e7-8b04-c87536df2d35.png)
![twitter_icon](https://user-images.githubusercontent.com/25004151/32720030-9eb57ffe-c862-11e7-8594-bd228ad5f6ba.png)

**Comment by autonome** [comment]
Thanks @AnXh3L0!

I love the strong lines and strong contrast. Style and visual design aesthetic is excellent, nothing to change.

From a content perspective, I'd like to change one major thing:

This design tells a visual story that says "Chrome and Mozilla".

This isn't really correct - if the project was about only two engines, the design would either be Google/Mozilla, Chrome/Firefox, Blink/Gecko. The project is about all the engines - right now I've got Gecko, Blink, Webkit and Edge support.

So what I'd like the design to visually convey is "New features and changes in *all* the engines that run the web".

I'm totally fine with having zero logos at all, or all four logos (though it might need to scale in the future!).

Is that enough info for a revision?

Thanks again for helping out with this!

**Comment by AnXh3L0** [comment]
Thanks for the feedback @autonome. Reading the original issue posted it said Gecko/Blink, that's why I thought it was just for two engines, but I will have a look into it and create something else :)

**Comment by AnXh3L0** [comment]
Here are the new files @autonome, have a look.

![header](https://user-images.githubusercontent.com/25004151/32782293-da90f26e-c93f-11e7-9438-f0ba5740299e.png)
![icon](https://user-images.githubusercontent.com/25004151/32782294-dba0a8ca-c93f-11e7-854d-8bc4031c6c95.png)

You can download and use them directly in Twitter, they are the exact size for that social media.

**Comment by autonome** [comment]
Yessss, this is excellent, thanks so much! +1 on the concept, and thanks for continuing the designhacking on this :D

A few more tweaks I'd like like try out:

* Can you reduce the visual noise a bit by removing the inner circles noted on the screenshot below?

* Can you expand the gear and globe size to fill more of the space?

* Can you tweak the shape of the continents in the globe a bit? A bit more definition would be reduce visual ambiguity, making the shape more instantly visually recognizable as earth.

* Can you make a version with only one motion line on each side?

<img width="395" alt="screen shot 2017-11-14 at 20 54 02" src="https://user-images.githubusercontent.com/50103/32783371-1327ab52-c97e-11e7-81e0-70ca4eb73108.png">

**Comment by autonome** [comment]
Also, as the main purpose will be icons - most people see it through tweets, can you drop a few icon sizes in so we can see how it works when far smaller?

**Comment by elioqoshi** [comment]
![image](https://user-images.githubusercontent.com/5436686/32784369-f1c2b6ca-c94e-11e7-8c93-6caf8aaffe87.png)

![image](https://user-images.githubusercontent.com/5436686/32784495-47ef2aba-c94f-11e7-9843-4f6879871df1.png)

@autonome updated this here. Here is it how it looks on Twitter:

![image](https://user-images.githubusercontent.com/5436686/32784563-7906e336-c94f-11e7-8be4-001616c907ce.png)

**Comment by autonome** [comment]
Cool, thanks for the changes Elio! This is almost where it needs to be.

* Can you remove the belts that extend to the edges? The prior version didn't have those, and I thought it was cleaner and visually stronger that way. I think they're more noisy (and also make the viewer start wondering exactly what kind of engine this is!).

* I think the globe change is good, but I'd rather not have it prefer any continent over another. Fake continents are fine, I'd just like a bit more definition to them (as you did here with smaller crisper edge lines), so they are less blob-like.

**Comment by elioqoshi** [comment]
@autonome is this what you had in mind?

![image](https://user-images.githubusercontent.com/5436686/32786886-6be21a30-c955-11e7-9945-ce6bce6e01f8.png)

**Comment by autonome** [comment]
YES! The only tweaks I see are:

* Playing with the line weights to see how thinner lines overall effect the
feel

* Comparing against a version that expands globe and gear to fill more of
the space

But honestly, I'd ship this as-is and be ok. Thanks so much to both of you
:D

**Comment by AnXh3L0** [comment]
Maybe something like this @autonome?

![header2](https://user-images.githubusercontent.com/25004151/32788129-4eff861e-c950-11e7-96f6-b90c79cb5dfe.png)
![icon2](https://user-images.githubusercontent.com/25004151/32788130-4f90ea1e-c950-11e7-8e72-cd407447dad0.png)

**Comment by autonome** [comment]
Yes, that's fantastic. Thanks @AnXh3L0 😍

**Comment by elioqoshi** [comment]
Fantastic @AnXh3L0! Can you push these to the repo please?

**Comment by AnXh3L0** [comment]
Sure @elioqoshi. Here they are: https://github.com/mozilla/OpenDesign/tree/master/2017/Graphics/Intent_to_ship_Twitter

**Comment by elioqoshi** [comment]
@autonome I guess we can close this, thanks for your patience!

**Comment by autonome** [comment]
Thanks y'all, I really appreciate your work on this 👍
