### ISSUE TITLE
T-shirt design + Logo for Mozilla's research speech recognition team

### ISSUE THREAD

**Issue by andrenatal** [mozilla/OpenDesign#92]
## Goal: 
We'd like to have a logo + design for our team's tshirt

## Info: 
For a T-shirt and maybe stickers

## Style Information: 
That's up to you!

## Deadline: 
Before end of December, please?

## Tag: 
[Design Needed]

**Comment by Tess-welhazi** [comment]
My suggestion 
![image](https://cloud.githubusercontent.com/assets/20952652/21396998/66af3d0a-c7a2-11e6-989e-deff6018fc8b.png)
Sorry for the quality it's just a sketch at this point. Is it too cartoon-ish?

**Comment by kdavis-mozilla** [comment]
😄

I'm a graphics novice. But I've a question, would this be able to be reproduced at smaller sizes with all the fox details being preserved?

**Comment by Tess-welhazi** [comment]
Sure once i recreate it in vector. I just tend to sketch the idea at my usual art software first.

**Comment by elioqoshi** [comment]
Seems a bit rough still (the fox is hardly recognizable)

@raphaeck might have some sketches as well?

**Comment by Raphseck** [comment]
Hey guys!
@elioqoshi yes, i can create some sketches. : )))

**Comment by kdavis-mozilla** [comment]
@andrenatal according to @elioqoshi we can't have a logo yet as we are not a product yet. So we have to close this.

**Comment by elioqoshi** [comment]
@kdavis-mozilla again, we are free to do artwork and designs so a T-Shirt Design is fine here (as long as we don't create a new logo per se)

**Comment by kdavis-mozilla** [comment]
@elioqoshi Thanks, but no thanks.

We'd want a coherent branding across t-shirts, websites, presentations...and without a logo that's not possible.

**Comment by elioqoshi** [comment]
Better to wait a bit more until the new branding rolls out then :)

**Comment by Tess-welhazi** [comment]
@kdavis-mozilla Ah, i thought this was only for T-shirts and stickers

**Comment by barrosgeraldo** [comment]
@andrenatal, Olá! Do you still need this artwork?

**Comment by kdavis-mozilla** [comment]
@barrosgeraldo Andre is no longer on the speech recognition team.

I'm currently unclear as to what is and is not allowed with respect to designs. From the above it seems like a shirt design is fine but a logo design is not allowed. Is this still the case? 

If this is still the case what does one have to do officially have a logo designed?

**Comment by barrosgeraldo** [comment]
@elioqoshi, please, do you have the information he's asking for?

**Comment by andrenatal** [comment]
@barrosgeraldo  yes we need!

**Comment by elioqoshi** [comment]
Again, logos for internal projects will usually have no icons according to the new guidelines, so closing this.
