### ISSUE TITLE
Logo design for Mozilla machine learning research group

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/OpenDesign#93]
## Goal: 
Logo design for the Mozilla machine learning research group

## Info: 
Targeted formats web sites, stickers, shirts, billboards in Times Square

## Style Information: 
I like the Google research logo
![rgicontransparent](https://cloud.githubusercontent.com/assets/12054740/21302877/ded0fba0-c5ba-11e6-8f47-60b11d62990f.png)
Also the "double vision" look of
![cc4-logo-design](https://cloud.githubusercontent.com/assets/12054740/21303033/eceea326-c5bb-11e6-9350-b23877237046.png)
However, at the same time the logo should suggest machine learning

## Deadline: 
January 16, 2017

## Tag: 
Design Needed

**Comment by Kiladel** [comment]
Well here's a sketch of what i have in mind 
![image](https://cloud.githubusercontent.com/assets/24366853/21351834/fff65e56-c6be-11e6-8c20-3204ca5fd1dc.png)

**Comment by kdavis-mozilla** [comment]
Wow, @Kiladel thanks!

Let me see what the rest of the team @mozilla/research-machine-learning thinks.

**Comment by reuben** [comment]
Random idea: [grid of convolution filters](http://cs231n.github.io/assets/cnn/weights.jpeg) that align to make a wordmark or symbol for the logo.

**Comment by kdavis-mozilla** [comment]
@Kiladel One thought I had on the current sketch is, the colors could be a bit more bold, going more towards orange and blue of Firefox or the red of the original dino logo. Just so it "pops" a bit more.

**Comment by Tess-welhazi** [comment]
Recolored. which one do you prefer?

![image](https://cloud.githubusercontent.com/assets/20952652/21390419/3482fa4e-c787-11e6-871d-d3c3ec207272.png)

![image](https://cloud.githubusercontent.com/assets/20952652/21390448/5e4d6206-c787-11e6-9c73-00a62bc1ee9d.png)

**Comment by kdavis-mozilla** [comment]
@Kiladel The first

**Comment by Tess-welhazi** [comment]
@kdavis-mozilla Alright, working it

**Comment by kdavis-mozilla** [comment]
This is like magic! Thanks!

**Comment by Tess-welhazi** [comment]
@kdavis-mozilla You're welcome ^_^
the svg file link here. (i'm not sure about the font you can change it)
https://drive.google.com/file/d/0B_tjMPSXw78eZTlGX1pJbjVmeHM/view?usp=sharing

**Comment by kdavis-mozilla** [comment]
Thanks! I'll run them by the team.

**Comment by elioqoshi** [comment]
@kdavis-mozilla Why do we need a logo here? Logos are reserved for products and established proejcts at Mozilla. Maybe you just need a design for swag?

@Tess-welhazi the design seems quite off our Mozilla guidelines, I wouldn't suggest going that way.

@parag9d do you have a suggestion here?

**Comment by kdavis-mozilla** [comment]
@elioqoshi We are an established project at Mozilla. We have a group of 6 full time Engineers working on this.

**Comment by elioqoshi** [comment]
@kdavis-mozilla  I do know that, but according to Brand Guidelines that's not the bar.

https://wiki.mozilla.org/Engagement/Brand/Why_Do_We_Have_Brand_Guidelines
https://wiki.mozilla.org/Engagement/Brand/Brand_and_Identity_Guide

And the new brand identity will be rolled out in a few weeks anyway. so you'd need to change anything you have right now soon again.

**Comment by kdavis-mozilla** [comment]
@elioqoshi If those are the official rules.

**Comment by elioqoshi** [comment]
@kdavis-mozilla Yeah. We will have news next month hopefully when the new brand identity rolls out, so please feel free to remind us again at that time
