### ISSUE TITLE
Re-evaluate the usage of hand gestures in Mozilla branding images

### ISSUE THREAD

**Issue by gueroJeff** [mozilla/OpenDesign#94]
## Goal: 
Currently the branding images within https://blog.mozilla.org/opendesign/arrival/ use had gestures that could be interpreted as culturally vulgar or offensive to people. As hand gesture meanings are not universal but highly subjective based on the audience's culture, I suggest re-evaluating whether to include hand gestures in any branding imagery.

## Info: 
Here is a guide to some of the more well-known offensive hand gestures around the world. http://www.huffingtonpost.com/2014/03/17/the-global-guide-to-hand-_n_4956860.html

## Tag: 
[Question, Staff Support Needed]

**Comment by elioqoshi** [comment]
@timotay Can we look into this?

**Comment by barrosgeraldo** [comment]
I have not seen such gestures around Mozilla's campaigns anymore, has anyone reported directly to the branding team?

**Comment by Timotay** [comment]
Hi Geraldo,
The hand gestures in question were part of our initial design exploration. They are no longer a part of our brand guidelines. This bug can be closed.
Thanks,
Tim

(all thumbs)

**Comment by barrosgeraldo** [comment]
You're welcome. Closing.
