### ISSUE TITLE
Content overlapps Image on large screens

### ISSUE THREAD

**Issue by lkappeler** [mozilla/OpenDesign#95]
I guess it's designed to act as it does but it does look quiet bad in the newest [blogpost](https://blog.mozilla.org/opendesign/arrival/)
(not sure if this is the right place to report...)

![screen shot 2017-01-18 at 17 33 55](https://cloud.githubusercontent.com/assets/3371760/22073244/22635e2e-dda5-11e6-8d9a-9428da32f5b4.png)

**Comment by elioqoshi** [comment]
Hmm I think this has been changed now? It's kind of difficult to get it right on all resolutions though.

**Comment by lkappeler** [comment]
Still looks the same for me, tested in incognito mode with disabled cache.
There is a negative margin of -10% for the content container, for everything over 600px.
Removing that style would imo fix the problem.
![screen shot 2017-01-20 at 11 32 34](https://cloud.githubusercontent.com/assets/3371760/22146456/00ec0bae-df05-11e6-8485-e64bc4982d0c.png)

**Comment by elioqoshi** [comment]
Probably not a huge priority, but @Timotay might be able to delegate this

**Comment by MichaelKohler** [comment]
@elioqoshi @Timotay is the source for the blog design available somewhere? If so, pointing @lkappeler into the right direction on where he could find it would be enough I think ;)

**Comment by elioqoshi** [comment]
I'm not aware of it, but I hope so.

**Comment by lkappeler** [comment]
For sure I can make  a PR if someone can tell me where to find the code

**Comment by barrosgeraldo** [comment]
Hi @lkappeler, the code is here: https://github.com/craigcook/frontierline-theme
