### ISSUE TITLE
2 New T-Shirt Designs for Mozilla l10n

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/OpenDesign#98]
I was asked by the Mozilla l10n team to create 2 new T-Shirt Designs focused around localization. There is no additional action needed here, rather than me documenting the process here to keep in line with our open source principles.

## 1. Firefox Word Cloud

The first design will be a word cloud made out of mojibakes in different alphabets and scripts which will make up the Firefox logo. It would look something like this (kinda like a mosaic) but in various alphabets and scripts:

![cloud words mockup](https://cloud.githubusercontent.com/assets/5436686/22155606/48689d14-df30-11e6-8574-dca31142105b.jpg)

The final version would be a bit more detailled as I will be able to use different shaped characters for various parts of the fox.

## 2. Lion Cub and male lion sitting together.

The 2nd design would be a bit more abstract and include an illustration of a little lion cub trying to roar and beside him a fully grown male lion looking at him in an amused yet fatherful way. Due to the l10n "pun" and the lion being a reference to it, we chose to have the lion as a mascot here.

A mockup of how this would look like would be something along those lines:

![sketch](https://cloud.githubusercontent.com/assets/5436686/22155781/00df1bde-df31-11e6-90ad-8ccf47ff2e93.jpg)
![stance](https://cloud.githubusercontent.com/assets/5436686/22155782/00fbee6c-df31-11e6-9db6-8bb654b36c86.jpg)

The style of the illustration will be close to the one by Sean Martell in the Firefox Comic at All Hands Hawaii in December 2016:

![2](https://cloud.githubusercontent.com/assets/5436686/22155843/3c20e510-df31-11e6-9ea9-344a7f4f6757.jpg)

![1](https://cloud.githubusercontent.com/assets/5436686/22155883/5765ab3a-df31-11e6-9c4c-6232a552807f.jpg)

## Deadline

Both designs should be finished by 3rd February 2017 to ensure they are printed on time.

**Comment by elioqoshi** [comment]
@raphseck will help with the Lion illustration here as well :)

**Comment by amadejhp** [comment]
Will lion be made in vectors or hand drawn?

**Comment by elioqoshi** [comment]
Hand drawn and converted into vectors

**Comment by Tess-welhazi** [comment]
I'd love to help with the lion illustration if possible. I love that art style.

**Comment by Raphseck** [comment]
Hey guys! how are you?
Here the draw
What do you think?
![lions](https://cloud.githubusercontent.com/assets/14264676/22271848/ed0c3538-e27d-11e6-887a-b195f52f8d04.png)

**Comment by amadejhp** [comment]
I think it looks great :) 
I tried doing this also myself but mostly just for practice, and yours is beter ;) realy well made

**Comment by Raphseck** [comment]
thank you so much @amadejhp 
: )))

**Comment by elioqoshi** [comment]
![lions-01](https://cloud.githubusercontent.com/assets/5436686/22400933/88ee999a-e5c2-11e6-993c-27c82add0e90.png)

Slightly Tweaked :)

Good to go. Will send in mockups soon

**Comment by elioqoshi** [comment]
Finished. The l10n team was happy with this :)

![preview-01](https://cloud.githubusercontent.com/assets/5436686/22783222/21f7f2c4-eecb-11e6-8ff7-73233e1e2e03.jpg)

![preview-01](https://cloud.githubusercontent.com/assets/5436686/22783231/2eb0be74-eecb-11e6-9958-b8c253dacf45.jpg)

**Comment by simonrcodrington** [comment]
Loving the logo made from various words. The lion one is pretty awesome also :)

**Comment by Tess-welhazi** [comment]
The logo with many words looks great, the lions though not so much.

**Comment by elioqoshi** [comment]
Redoing these with the new Firefox logos:
https://github.com/mozilla/OpenDesign/issues/188
